### ISSUE TITLE
client.Records.getList not working

### ISSUE THREAD

**Issue by burggraf** [pocketbase/js-sdk#1]
No matter what parameters I pass, `client.Records.getList` doesn't seem to work.  Here's some sample code that **should** work, AFAIK:

```js
const getCars = async () => {
	client.Records.getList('cars', 1, 3, 
            { filter: 'year > 1960', sort: 'year' })
	.then(function (list) {
		// success...
		console.log('list', list)
	})
	.catch(function (error) {
		// error...
		console.error('getlist error', error)
	})
}
```
This throws an error:

```
Cars.tsx:20 getlist error null
(anonymous) @ Cars.tsx:20
Promise.catch (async)
getCars @ Cars.tsx:18
newProps.onClick @ createRoutingComponent.tsx:98
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
```

**Comment by ganigeorgiev** [comment]
I've just tested it locally and it works as expected (you could also set the client url to the live demo for tests, https://pocketbase.io).

Could you check the API response in Inspect tool > Network tab in your browser?
I suspect that the collection list rule requires admin authentication (this is the default when creating a new collection) and the above error should be a 401 error response, but I'm not sure why in your example the the "console.error" is printing `null` for the error argument.

**Comment by burggraf** [comment]
You're right.  It does work.  However, this is the code that was causing my problem:

```js
const getCars = async () => {
    client.Records.getList('cars', 1, 3, 
        { filter: 'year > 1960', sort: 'year' })
        .then(function (list) {
            console.log('list', list)
        })
        .catch(function (error) {
            console.error('getlist error', error)
        })

    client.Records.getFullList('cars', 200 /* batch size */, {
        filter: 'year >= 1960',
        sort: 'year',
    })
        .then(function (records) {
            console.log('records', records)
        })
        .catch(function (error) {
            console.error('records error', error)
        })
}
```

So I think there's still a bug -- if you make two calls like this, one after another, one of the calls fails.  Interestingly, it's the first one that fails in this case, presumably because the second call is overwriting the first one?

**Comment by burggraf** [comment]
Thanks.  This was, of course, not a real-world use case -- I was just testing the available methods to see how they worked.  The results were just unexpected, but documentation will help with that.  Cool.

**Comment by denox55** [comment]
> Tidak peduli parameter apa yang saya lewati, `client.Records.getList`sepertinya tidak berfungsi. Berikut beberapa contoh kode yang **seharusnya** berfungsi, AFAIK:
> 
> ```js
> const getCars = async () => {
> 	client.Records.getList('cars', 1, 3, 
>             { filter: 'year > 1960', sort: 'year' })
> 	.then(function (list) {
> 		// success...
> 		console.log('list', list)
> 	})
> 	.catch(function (error) {
> 		// error...
> 		console.error('getlist error', error)
> 	})
> }
> ```
> 
> Ini melempar kesalahan:
> 
> ```
> Cars.tsx:20 getlist error null
> (anonymous) @ Cars.tsx:20
> Promise.catch (async)
> getCars @ Cars.tsx:18
> newProps.onClick @ createRoutingComponent.tsx:98
> callCallback @ react-dom.development.js:3945
> invokeGuardedCallbackDev @ react-dom.development.js:3994
> invokeGuardedCallback @ react-dom.development.js:4056
> invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
> executeDispatch @ react-dom.development.js:8243
> processDispatchQueueItemsInOrder @ react-dom.development.js:8275
> processDispatchQueue @ react-dom.development.js:8288
> dispatchEventsForPlugins @ react-dom.development.js:8299
> (anonymous) @ react-dom.development.js:8508
> batchedEventUpdates$1 @ react-dom.development.js:22396
> batchedEventUpdates @ react-dom.development.js:3745
> dispatchEventForPluginEventSystem @ react-dom.development.js:8507
> attemptToDispatchEvent @ react-dom.development.js:6005
> dispatchEvent @ react-dom.development.js:5924
> unstable_runWithPriority @ scheduler.development.js:468
> runWithPriority$1 @ react-dom.development.js:11276
> discreteUpdates$1 @ react-dom.development.js:22413
> discreteUpdates @ react-dom.development.js:3756
> dispatchDiscreteEvent @ react-dom.development.js:5889
> ```

**Comment by ganigeorgiev** [comment]
Added a [Caveats](https://github.com/pocketbase/js-sdk#caveats) section in the readme.

@denox55 if your are experiencing issue with the SDK, please comment or open a new issue and I'll investigate it more thoroughly.
