### ISSUE TITLE
auth record verification email request

### ISSUE THREAD

**Issue by bikedel** [pocketbase/js-sdk#106]
hello
I successfully create and authenticate a user. The verification email gets sent and I receive it. 

The link to verify is pointing to localhost?  How do I change it to point to my server?

http://localhost:8090/_/#/auth/confirm-verification/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2xsZWN0aW9uSWQiOiJtaHFuM2JlZWN0c3A3OTgiLCJlbWFpbCI6ImJpa2VkZWxAbWFpbC5jb20iLCJleHAiOjE2NzE0NzMyOTAsImlkIjoicWphcTA1amx4ZGt2NXdqIiwidHlwZSI6ImF1dGhSZWNvcmQifQ.NxVzDjLXP-OARySj044RR6jWuN7ujhh98pUMsd6uX2g

**Comment by ganigeorgiev** [comment]
By default all email templates uses the "Application url" defined in:
Admin UI > Settings > Application

![settings](https://i.imgur.com/IFgUdI6.png)

Additionally, you can fully change the email url (eg. pointing to your custom page) by updating the "Action url" in the email template settings:

![template](https://i.imgur.com/vm1mgxM.png)

**Comment by bikedel** [comment]
big thanks for the quick response
