### ISSUE TITLE
Validate user/admin token

### ISSUE THREAD

**Issue by RadekPelikan** [pocketbase/js-sdk#107]
Maybe I don't understand the concept fully, but I would like to have a option to validate my token.

I use the API from pocketbase to connect to DB and I can not find a endpoint for validating a token. I don't want to auth with password to get a new token or making some nonsensical request, for example to view the records to check if it's valid. Is there some way to validate a user/admin auth token?

Thanks

**Comment by ganigeorgiev** [comment]
We don't have an endpoint that will validate only the token at the moment (it could be added eventually with https://github.com/pocketbase/pocketbase/issues/718).

The easiest way to validate a token would be to call `refresh` (eg. `await pb.admins.refresh()`). It throws an error on missing/invalid/expired AuthStore token.
