### ISSUE TITLE
Realtime API error: EventSource is not defined

### ISSUE THREAD

**Issue by JeysonFlores** [pocketbase/js-sdk#108]
**Environment:**
 - **SO**:  Ubuntu 22.04
 - **NodeJS version**:  v18.12.1
 - **PocketBase version**:  0.9.2

Hello. I'm new to PocketBase and Node. I was doing some tests in my localhost so I tried to test the Realtime API. I just followed the code in the **[API Preview]** section of my `employees` model:
```JavaScript
import PocketBase from 'pocketbase';

const pb = new PocketBase('http://127.0.0.1:8090');


// (Optionally) authenticate
await pb.collection('users').authWithPassword('my@email.com', '12345678');

// Subscribe to changes in any employees record
pb.collection('employees').subscribe('*', function (e) {
    console.log(e.record);
});


// Unsubscribe
pb.collection('employees').unsubscribe('*'); // remove all '*' topic subscriptions

```

However it throws this error:
```
ReferenceError: EventSource is not defined
    at n.initConnect (file:///home/jeyson/Proyectos/NodeJS/pb_test/node_modules/pocketbase/dist/pocketbase.es.mjs:1:32094)
    at file:///home/jeyson/Proyectos/NodeJS/pb_test/node_modules/pocketbase/dist/pocketbase.es.mjs:1:31804
    at new Promise (<anonymous>)
    at n.<anonymous> (file:///home/jeyson/Proyectos/NodeJS/pb_test/node_modules/pocketbase/dist/pocketbase.es.mjs:1:31702)
    at file:///home/jeyson/Proyectos/NodeJS/pb_test/node_modules/pocketbase/dist/pocketbase.es.mjs:1:1905
    at Object.next (file:///home/jeyson/Proyectos/NodeJS/pb_test/node_modules/pocketbase/dist/pocketbase.es.mjs:1:2010)
    at file:///home/jeyson/Proyectos/NodeJS/pb_test/node_modules/pocketbase/dist/pocketbase.es.mjs:1:947
    at new Promise (<anonymous>)
    at i (file:///home/jeyson/Proyectos/NodeJS/pb_test/node_modules/pocketbase/dist/pocketbase.es.mjs:1:692)
    at n.connect (file:///home/jeyson/Proyectos/NodeJS/pb_test/node_modules/pocketbase/dist/pocketbase.es.mjs:1:31592)
```
It doesn't matter if I change the suscribe event to subscribe to an ID or whatever, it always throws that error.
If anyone has a clue about what could be wrong here I'll be glad to test it. Thanks!

**Comment by JeysonFlores** [comment]
Fixed

**Comment by jonmaestas** [comment]
@JeysonFlores - What did you do to fix this? I tried adding `EventSource` to my project, but I couldn't get it working.

As a temporary solution, I'm using `setInterval` with polling, but I would much rather have a real-time subscription to the collection.

**Comment by ganigeorgiev** [comment]
@jonmaestas Node doesn't have native EventSource implementation and you need to use a polyfill, eg:

```js
// npm install eventsource --save
global.EventSource = require('eventsource');
```

This and other node caveats could be found in the readme of the JS SDK - https://github.com/pocketbase/js-sdk#nodejs-via-npm.
