### ISSUE TITLE
Remove many records

### ISSUE THREAD

**Issue by ndaidong** [pocketbase/js-sdk#109]
Is it posible to delete multi records with only one API call?

**Comment by ganigeorgiev** [comment]
No, this is not possible at the moment.
You have to send individual requests for each record. The upcoming v0.10 release will come with major performance improvements and the cost of processing multiple requests is greatly reduced (it will be available sometime next week).

Bulk transactional create/update/delete is in the [roadmap](https://github.com/orgs/pocketbase/projects/2) and will be implemented as part of #48 sometime in the future.

**Comment by ndaidong** [comment]
@ganigeorgiev thank you.
