### ISSUE TITLE
Cannot import pocketbase from component in Nuxt

### ISSUE THREAD

**Issue by zkzkatz** [pocketbase/js-sdk#112]
<img width="586" alt="image" src="https://user-images.githubusercontent.com/119627195/208823951-eafcfaaa-1461-47e0-b310-d827b8728ae1.png">
From inside a component, this is the error I get. It still functions but provides no types
However when I do the same from inside a file in the plugins directory it imports.

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce the issue with Nuxt3. Could you provide a little more context - what nuxt, node, ts versions you are using and/or provide a minimal reproducible repo?

It could also be a result of conflicting import path if you have placed the PocketBase executable inside your frontend project (you can try renaming it to `pocketbase_bin` or similar).

**Comment by zkzkatz** [comment]
"nuxt": "3.0.0",
"pocketbase": "^0.9.0"
Node v16.15.0
not so sure about the ts version

I originally had the executable named pocketbase.exe in the root folder, but separate from the src/ directory. I eventually renamed it, deleted .nuxt, package-lock.json, node_modules and reinstalled everything fresh. It could be a vetur extension issue because the import worked in a .ts file one folder away rather than the .vue file maybe
I managed to figure out the sdk through a different method by using pinia.

**Comment by ganigeorgiev** [comment]
I've downgraded my node to 16 (it shouldn't have effect on this, but to match with your env) and I still cannot reproduce the issue in sublime and vim with the standard lsp plugins.

I suspect that it is a vscode or vetur issue. Vetur even has an faq entry for this error - you may also want to check https://vuejs.github.io/vetur/guide/FAQ.html#vetur-crash.
