### ISSUE TITLE
Unable to upload base64 encoded files

### ISSUE THREAD

**Issue by guyver2** [pocketbase/js-sdk#115]
Hi,

I'm a fairly new user to pocketbase and I'm having trouble creating records with image files that are base64 encoded fom a typescript app.

I have my image stored in a string that looks like this:
`"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAAAaGVY....`
The image is correct as I use the same string in an <img> tag and it shows nicely.
 
I found the following base64 to Blob conversion function online (https://stackoverflow.com/a/61321728) but I am unable to make it work.
Here is a copy of my code:
```
  function DataURIToBlob(dataURI: string) {
        const splitDataURI = dataURI.split(',')
        const byteString = Buffer.from(splitDataURI[1], 'base64').toString();
        const mimeString = splitDataURI[0].split(':')[1].split(';')[0];

        console.log(mimeString) // "image/png"

        const ia = new Uint8Array(byteString.length)
        for (let i = 0; i < byteString.length; i++)
            ia[i] = byteString.charCodeAt(i)

        return new Blob([ia] ,{ type: mimeString })
      }

      

  async function save() {
    const formData = new FormData();
    formData.append("text", text);
    formData.append("owner", currentUser.model.id);

    let blob = DataURIToBlob(cover);

    formData.append("cover", blob);
    await pb.collection('stories').create(formData);
  }
```

The cover field is not mandatory, if I comment out `formData.append("cover", blob);`, then the record gets properly created.
But if I leave it in I get the following error message:

```
code : "validation_invalid_mime_type"

message : "The following mime types are only allowed: image/jpg,image/jpeg,image/png,image/svg+xml,image/gif."
```

I tried modifying the `DataURIToBlob` function to remove the mimetype, adding a filename to `formData.append("cover", blob, "cover.png")`. But the outcome is always the same.

I also set the debug flag when starting  pocketbase executable but the logs shown are basically the same as what is shown in the web browser logs.

**Comment by ganigeorgiev** [comment]
Are you using the native browser `FormData` or a polyfill?

You can also try instead of `Blob` to append a `File` instance created from it, eg.:

```js
formData.append("cover", new File([blob], "originalFilename.png", { type: "image/png" }));
```
_(note: the frontend submitted mimetype doesn't really matter; we validate the mimetype server-side based on the first couple bytes)_

**Comment by guyver2** [comment]
Thanks for the help, turns out my issue was in the base 64 to Blob conversion function. Somewhere in the process some chars where converted to values way above the max value of 255 for a unit8. 

Here is a modified version that works just fine for my use case:

```
function base64StringToBlob(dataURI: string): Blob {
        const splitDataURI: string[] = dataURI.split(','); // splits prefix "data:image/png;base64,"
        const buf: Buffer = Buffer.from(splitDataURI[1], 'base64');
        return new Blob([buf]);
      }      

  async function save() {
    const formData = new FormData();
    formData.append("text", text);
    formData.append("owner", currentUser.model.id');

    let blob = base64StringToBlob(cover);

    formData.append("cover", blob, 'cover.png');
    await pb.collection('stories').create(formData);
  }
```
