### ISSUE TITLE
EventSource is not defined

### ISSUE THREAD

**Issue by diamonddev01** [pocketbase/js-sdk#116]
![image](https://user-images.githubusercontent.com/76881234/209425698-5bea954c-7289-4c68-aa4e-7cfbc8cc0128.png)
![image](https://user-images.githubusercontent.com/76881234/209425701-277fa76e-0760-40fc-ac25-8e1bace1909e.png)

Error seems to be with subscribing to a collection from what I can see

**Comment by ganigeorgiev** [comment]
Node doesn't have native EventSource implementation and you'll need to use a polyfill. I recommend https://github.com/EventSource/eventsource:

```
// npm install eventsource --save

cjs
global.EventSource = require('eventsource');

// or as esm import
import EventSource from "eventsource";
global.EventSource = EventSource;
```

This and other node caveats you can find in https://github.com/pocketbase/js-sdk#nodejs-via-npm.
