### ISSUE TITLE
Improvement: Update SvelteKit example

### ISSUE THREAD

**Issue by lukasbachlechner** [pocketbase/js-sdk#119]
I was trying for hours to fix an issue with another service that is also handled in `hooks.server.ts`, which also sets cookies – until I found out that this line

```ts
 // send back the default 'pb_auth' cookie to the client with the latest store state
response.headers.set('set-cookie', event.locals.pb.authStore.exportToCookie());
```

overwrites all previously set headers. Maybe we could update the docs to just append the new cookie header?

```ts
 // send back the default 'pb_auth' cookie to the client with the latest store state
response.headers.append('set-cookie', event.locals.pb.authStore.exportToCookie());
```

**Comment by ganigeorgiev** [comment]
I've updated the SvelteKit example to use `append`.
