### ISSUE TITLE
Not an issue: I made an NPX tool for this

### ISSUE THREAD

**Issue by SpideyZac** [pocketbase/js-sdk#123]
Hi just wanted to make sure it was okay with you if I keep this super simple (and I mean simple) NPX script up. https://github.com/SpideyZac/create-pocketbase-app. It's just a script where you can easily install the 'pocketbase.exe' file into your project and can also specify the version and device. If you would like it to be taken down just let me know or would like changes, I'm happy to do so.

**Comment by ganigeorgiev** [comment]
I don't see why I would have anything against it.
It is completely OK users to create external packages, extend or modify PocketBase.
