### ISSUE TITLE
not working with next.js/react

### ISSUE THREAD

**Issue by lonelil** [pocketbase/js-sdk#125]
Hello there, 

I am currently trying to pull data for posts from pocketbase and display them, but every time I add pocketbase code, nextjs/react will throw an error saying

`Error: Objects are invalid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.`

Even though I am not displaying the data, I am just logging into the console. 

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/51315646/210905235-6192162d-48c8-4716-9ba9-7d06e9df66b6.png">

I have been trying to debug this for 2 hours with no luck, any help will be appreciated!

**Comment by ganigeorgiev** [comment]
I don't think this is related to the SDK.

The error indicates that you are returning a `Promise` (eg. you have `async` in your function declaration).

If you are still not able to resolve, feel free to provide an example code that causes the error and I'll investigate it in more details.
