### ISSUE TITLE
Login fails in SvelteKit

### ISSUE THREAD

**Issue by Gregor-code** [pocketbase/js-sdk#126]
I am trying to use the login action in the script provided above to log in to my application, but I am encountering an error. When I try to log in, the code fails at the **const authData** line with the following **error: ClientResponseError 0: Something went wrong while processing your request**.

**login/+page.server.js:**

`export const actions = {
    login: async ({request, locals}) => {
        const body = await Object.fromEntries(await request.formData())
        try {
            const authData = await locals.pb.collection('users').authWithPassword(
                body.email,
                body.password,
            );

            if(!locals.pb?.authStore?.model?.verified){
                locals.pb.authStore.clear()
                return {
                    notVerified: true
                }
            }
        } catch(err){
            console.error(err);
        }
    }
}`

I have tried multiple times and made a few changes to the code, but the issue persists. I have also noticed that there is no **cookie** being created when I try to log in.

I am following the instructions in this YouTube video as my source: [SvelteKit & Pocketbase](https://www.youtube.com/watch?v=vKqWED-aPMg&t=664s). I would appreciate any help in resolving this issue. Thanks!

**Comment by ganigeorgiev** [comment]
Without the error stack I'm not sure what is the reason for the error.

You can try to log the original error, aka. `console.log(err.originalError)`.
`ClientResponseError 0` usually indicates "local" error, either from [autocancellation](https://github.com/pocketbase/js-sdk#auto-cancellation) or maybe a connection error, aka. the node-server/browser cannot establish a connection with the PocketBase server (_if you are testing on localhost with node17+ make sure to use `127.0.0.1` instead of `localhost` because of #21_).

**Comment by Gregor-code** [comment]
This is the error from err.originalError:

`TypeError: fetch failed
    at fetch (pathToProject\node_modules\undici\index.js:105:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async login (/src/routes/login/+page.server.js:7:30)
    at async handle_action_request (pathToProject\node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:143:16)
    at async render_page (pathToProject\node_modules/@sveltejs/kit/src/runtime/server/page/index.js:63:20)      
    at async resolve (pathToProject\node_modules/@sveltejs/kit/src/runtime/server/index.js:356:17)
    at async Object.handle (pathToProject\src\hooks.server.js:18:19)
    at async respond (pathToProject\node_modules/@sveltejs/kit/src/runtime/server/index.js:229:20)
    at async pathToProject\node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:444:22 {
  cause: Error: connect ECONNREFUSED ::1:8090
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1471:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 8090
  }
}`

**Comment by ganigeorgiev** [comment]
Yep, `ECONNREFUSED` confirms that this is the same as in #21.

Try to replace your PocketBase connect url from `localhost` to `127.0.0.1` and it should work, aka:

```js
new PocketBase("http://127.0.0.1:8090")
```
