### ISSUE TITLE
Get id on create

### ISSUE THREAD

**Issue by Bilalm354** [pocketbase/js-sdk#132]
I have two collections. "Answers" and "questions". Answers contains a reference to the id of the question. 

I want to create a question record and an associated answer record. I would like to get the id of the question when I create it but the create function only returns the record and not the response so I can't get the id. 

Is there a workaround for this? 

Thanks

**Comment by ganigeorgiev** [comment]
@Bilalm354 I'm closing the issue because I don't think it is related to the SDK, but feel free to provide more details what you are trying to do and I'll investigate it.
