### ISSUE TITLE
[ReferenceError: Can't find variable: EventSource] React Native

### ISSUE THREAD

**Issue by k3j123** [pocketbase/js-sdk#133]
Im trying to get Pocketbase running on React Native using Typescript. Everything works fine until I set up subscribe.

I've added : `npm install eventsource --save`
and then I add: `
  import eventsource from 'eventsource';
  global.EventSource = eventsource;
`
To my pocketbase.service.ts file.

This I get a new error: `
The package at "node_modules/eventsource/lib/eventsource.js" attempted to import the Node standard library module "url".
It failed because the native React runtime does not include the Node standard library.`

I'll get this error for url, events, https and http.

Any advice on how to fix would be greatly appreciated.

**Comment by ganigeorgiev** [comment]
I think this is similar to https://github.com/pocketbase/pocketbase/discussions/1176.

In short, you can try with a different polyfill, eg. https://www.npmjs.com/package/react-native-sse:

```js
import EventSource from "react-native-sse";

// or globalThis depending which is available
global.EventSource = EventSource;
```
