### ISSUE TITLE
[React Native]: Can't find variable: EventSource

### ISSUE THREAD

**Issue by anhtuank7c** [pocketbase/js-sdk#135]
React Native doesn't seem to support EventSource.

![image](https://user-images.githubusercontent.com/3163410/214209368-a09efe9d-e188-4437-a088-50f5b62b9b62.png)

Should we do something like this `https://www.npmjs.com/package/react-native-event-source` to be able to support Server-Sent Events on React Native?

https://github.com/pocketbase/js-sdk/blob/b123521190adccdfa7c294dad7ecc3d48abe29b3/src/services/RealtimeService.ts#L304

**Comment by anhtuank7c** [comment]
https://github.com/EventSource/eventsource/issues/132
The linked lib from your README file doesn't seem usable for React Native.
Do we have an alternative solution such as socket-io or WebSocket?

**Comment by anhtuank7c** [comment]
I've tried to use this lib to make a connection to PocketBase realtime endpoint, and set view rules to be open for anyone but seem just able to get skipped response.

https://github.com/jordanbyron/react-native-event-source

```
const eventSource = new RNEventSource(`${endpoint}/api/realtime`);
      eventSource.addEventListener(`${job.collectionName}/${job.id}`, (e) => {
        console.tron.log('sse', e);
      });
```

![Screenshot 2023-01-24 at 12 06 50](https://user-images.githubusercontent.com/3163410/214216249-3652f65c-e1ce-4db4-8b8f-f64789f33ded.png)

**Comment by ganigeorgiev** [comment]
You can check https://github.com/pocketbase/pocketbase/discussions/1176#discussioncomment-4308357.

```js
import EventSource from "react-native-sse";

// or globalThis depending which is available
global.EventSource = EventSource;
```

I'll consider updating the README with a note for React Native sometime later today.
