### ISSUE TITLE
Is the sdk available from an cdn and if not is it planned to make it available from an cdn ?

### ISSUE THREAD

**Issue by Adri11n** [pocketbase/js-sdk#139]

**Comment by ganigeorgiev** [comment]
You should be able to use any public JS CDN service like jsdelivr, cdnjs, statically, etc.

Here is an example with jsdelivr:

- UMD: https://cdn.jsdelivr.net/gh/pocketbase/js-sdk@0.10.1/dist/pocketbase.umd.js
- ESM: https://cdn.jsdelivr.net/gh/pocketbase/js-sdk@0.10.1/dist/pocketbase.es.mjs

**Comment by Adri11n** [comment]
Thx

**Comment by Adri11n** [comment]
Is there also a not minified version available ?
