### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by KBarreto23** [pocketbase/js-sdk#14]
[Unhandled promise rejection: ReferenceError: Can't find variable: EventSource]

**Comment by ganigeorgiev** [comment]
When you use the realtime service (aka. `client.Realtime`), for node environments you'll have to install an EventSource polyfill beforehand, for example https://github.com/EventSource/eventsource.

This is mentioned in the Definitions section in the README, but I'll move it somewhere more visible.

**Comment by z3cka** [comment]
I was able to solve this by adding `const EventSource = require('eventsource')` to the top of `node_modules/pocketbase/dist/pocketbase.cjs.js`, but doing it this way just doesn't feel right. 

I've never used a polyfil in this context before. Any tips on how to "install an EventSource polyfill" for a project running in node would be greatly appreciated.

I'm loving PocketBase. Cheers!

**Comment by ganigeorgiev** [comment]
@z3cka Hi, there shouldn't be a need to edit the bundle file. It should work just fine if you attach the `EventSource` polyfill to the global context, eg.:
```
global.EventSource = require('eventsource');
```

**Comment by z3cka** [comment]
That did the trick! Thanks!

**Comment by ganigeorgiev** [comment]
I've updated the README with notes about the node polyfills and examples how to load them - https://github.com/pocketbase/js-sdk#nodejs-via-npm with notes.

@KBarreto23 If you are still experiencing issues loading the SDK, please let me know and I'll investigate it further.

**Comment by KBarreto23** [comment]
thanks, i will try it

**Comment by gideonip** [comment]
I have followed the instruction, but still I cannot make it work. it keeps asking to install url, https, http, etc.. similar to [this issue](https://github.com/facebook/react-native/issues/12890).  

I tried an alternative : [rn-eventsource](https://github.com/adamchel/rn-eventsource), and it seems working, but I receive this error : Something went wrong while processing your request. Do you know how I can debug at client side?

**Comment by iskaa02** [comment]
For anyone stumbling on this, newer versions of react native includes flipper (a debugger) by default, a network plugin for flipper  make SSE not working, You can easily comment the following lines in `android/app/src/debug/java/ReactNativeFlipper.java` to disable the plugin
```java
  ...
public class ReactNativeFlipper {
  public static void initializeFlipper(Context context, ReactInstanceManager reactInstanceManager) {
    if (FlipperUtils.shouldEnableFlipper(context)) {
      final FlipperClient client = AndroidFlipperClient.getInstance(context);

      client.addPlugin(new InspectorFlipperPlugin(context, DescriptorMapping.withDefaults()));
      client.addPlugin(new ReactFlipperPlugin());
      client.addPlugin(new DatabasesFlipperPlugin(context));
      client.addPlugin(new SharedPreferencesFlipperPlugin(context));
      client.addPlugin(CrashReporterPlugin.getInstance());

      NetworkFlipperPlugin networkFlipperPlugin = new NetworkFlipperPlugin();
      
      
      // try to comment this code
      ________________________
      NetworkingModule.setCustomClientBuilder(
        new NetworkingModule.CustomClientBuilder() {
          @Override
          public void apply(OkHttpClient.Builder builder) {
            builder.addNetworkInterceptor(new     FlipperOkhttpInterceptor(networkFlipperPlugin));
          }
        }
      );
      _______________________


      client.addPlugin(networkFlipperPlugin);
      client.start();
      ...
    }
    ...
  }
```
