### ISSUE TITLE
Create a public method to check if there are any realtime subscriptions for topic

### ISSUE THREAD

**Issue by goknsh** [pocketbase/js-sdk#141]
I'm using [TanStack Query](https://tanstack.com/query/latest) to setup realtime stores for collections and records, and I need a way of figuring out if there are any realtime subscribers for a topic before I can mark a query to be stale after the last TanStack Query store subscriber unsubscribes.

Ideally, something like this would be made public:
https://github.com/pocketbase/js-sdk/blob/b123521190adccdfa7c294dad7ecc3d48abe29b3/src/services/RealtimeService.ts#L193-L209

Let me know if you're open to making something like this happen. If you want, I'd be happy to try and whip up a PR.

**Comment by ganigeorgiev** [comment]
It is possible to make the method "public" but I'm not sure that I understand the use case for it.

Could you provide a code sample/pseudo code with the expected workflow?

**Comment by goknsh** [comment]
Sure, here's a realtime record store for Svelte:

```typescript
export const createRecordQuery = <T extends Record = Record, TQueryKey extends QueryKey = QueryKey>(
	collection: ReturnType<Client['collection']>,
	id: string
): CreateQueryResult<T | null, ClientResponseError> => {
	const queryClient = useQueryClient();
	const queryKey = [collection.collectionIdOrName, id];

	const store = createQuery<T | null, ClientResponseError, T | null, TQueryKey>({
		staleTime: Infinity, // the "cached" record will never be stale as long as we are connected to realtime
		refetchOnReconnect: 'always', // always fetch the record again from the server when the browser is back online
		queryKey,
		queryFn: async () => await collection.getOne<T>(id, queryParams)
	});

	const unsubscribePromise = collection
		.subscribe<T>(id, (data) => {
			createRecordQueryCallback(
				queryClient.getQueryData<T | null>(queryKey) ?? null,
				data,
				collection,
				queryParams
			)
				.then((r) => {
					queryClient.setQueryData<T | null>(queryKey, () => r);
				})
				.catch(() => {
					// mark query as stale if an error has occurred
					queryClient.invalidateQueries({ queryKey, exact: true });
				});
		})
		.catch(() => {
			// mark query as stale if an error has occurred
			queryClient.invalidateQueries({ queryKey, exact: true });
			return async () => {};
		});

	return {
		subscribe: (...args) => {
			let unsubscriber = store.subscribe(...args);
			return () => {
				(async () => {
					await (await unsubscribePromise)();
					if (collection.client.hasSubscriptionListeners(`${collection.collectionIdOrName}/${id}`)) {
						// mark query as stale after there are no relatime subscribers
						// since we won't received any realtime updates for this record
						queryClient.invalidateQueries({ queryKey, exact: true });
					}
				})();
				return unsubscriber();
			};
		}
	};
};
```

**Comment by ganigeorgiev** [comment]
Thanks for the code sample but I'm still not sure that I understand what "stale" means in the above context and why you have to check the subscriptions.

I have added it in my todo, but for now I'm reluctant to expose explicitly more realtime methods because I'm planning a refactoring in the near future (_the `EventSource` dependency will be removed and eventually support for `expand` and `filter` in addition to the topic may be added_) and I want to keep the API surface minimal since I'm still not sure about the implementation details yet.

As a workaround, you can try accessing the "private" marked methods dynamically since the visibility modifiers are usually not checked in this case, eg.:

```ts
pb.realtime["hasSubscriptionListeners"]("...")
```

**Comment by goknsh** [comment]
Here, "stale" means that the data cached on the client-side is not in sync with the server-side database. When I call `queryClient.invalidateQueries`, TanStack Query will mark the query as stale (a query is identified by `queryKey`), and stale queries are refetched automatically in the background when new instances of the query mount or the network is reconnected.

I need to check the subscriptions because I need to be able to mark the query as stale only when there are no realtime subscriptions for that topic (avoiding unnecessary refetches).

I'll try and use the workaround for now. Thanks!
