### ISSUE TITLE
TypeScript Integration

### ISSUE THREAD

**Issue by BahaaElboraey** [pocketbase/js-sdk#147]
Hello there, I wish if I know how to integrate this sdk to a typescript enabled Sveltekit app

**Comment by ganigeorgiev** [comment]
Could you elaborate a little more?

The SDK already exports most of the internal typing definitions.

You can find SSR SvelteKit example in https://github.com/pocketbase/js-sdk#ssr-integration.

To enable types for the `locals.pb` instance you can just update your `app.d.ts`:

```ts
// src/app.d.ts
import PocketBase from "pocketbase";

declare global {
    declare namespace App {
        interface Locals {
            pb: PocketBase
        }
    }
}
```

**Comment by ganigeorgiev** [comment]
I'm closing the issue since this should be already supported.

If you are still having troubles running the SDK in a TypeScript project feel free to provide a code sample and/or tsconfig and I'll try to investigate it in more details.
