### ISSUE TITLE
Possibility for "authWithOAuth2" to bind to specified existing user

### ISSUE THREAD

**Issue by bloor** [pocketbase/js-sdk#148]
If I understood correctly and from what implentations I did, authWithOAuth2 automatically creates a new user if the email does not exist. There is no option to bind the provided auth to an existing account.

Study case: I create account using a gmail, but then I want to loggin (bind) twitch as social to same account. BUT my twitch is on another email, a yahoo mail.

So currently i cannot create a list of Connections (like discord has) for current user. 

In my case i.m using twitch auth keys and google keys ( if provider by user ) to link and offer him some extra features from his youtube, twitch streams.

**Comment by ganigeorgiev** [comment]
>  There is no option to bind the provided auth to an existing account.

Outside of the godocs, this at the moment is not documented very well, but you can link an OAuth2 account to an existing user as long as:

- the OAuth2 account is not already linked to another user
- there is a valid `Authorization` header sent with the `authWithOAuth2` request (aka. the user is already authenticated)
- the OAuth2 authentication happens in the same auth collection as the user

Or in other words, the following should work:

```js
await pb.collection("users").authWithPassword("test@example.com", "1234567890")
...
await pb.collection("users").authWithOAuth2(...)
```

**Comment by bloor** [comment]
Ok. I.ll try again, maybe i missed something. Thankyou.
