### ISSUE TITLE
errorDetails content

### ISSUE THREAD

**Issue by BegenchDev07** [pocketbase/js-sdk#149]
Hi guys ! I love this project and thank you guys for this project. I have a small question regarding the error handling. Is there any possible way to access the _errorDetails_ message from js-sdk or are there any solutions regarding this topic ?

**Comment by ganigeorgiev** [comment]
If you mean the `meta.errorDetails` field that is available in the logs, then No since it could contain sensitive information.

If you want to access the detailed public safe error message and data (_if available_), you can `try/catch` your API calls and inspect the error object:

```js
try {
    await pb.collection("example").authWithPassword(...);
} catch (err) {
    console.log(err.data) // the API json error response (this will be soft-deprecated in favour of `response` in the near future)
    console.log(err.originalError) // the raw/plain js error
}
```

**Comment by BegenchDev07** [comment]
Oh great thanks. I've made my way around it. This is how i did it. 
`try{
  //something here
} catch(error:any){
 for(const key in error.data.data){
     alert(error.data.data[key].message);
  }
}` 

it will alert the`meta.errorDetails`
