### ISSUE TITLE
export "RecordService" for TypeScript

### ISSUE THREAD

**Issue by humanfriend22** [pocketbase/js-sdk#153]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `pocketbase@0.11.0` for the project I'm working on.

I was passing around a `collection` returned by `pb.collection('COLLECTION_NAME')` & as I was using TypeScript, I needed to strongly type the argument & I found that the function above returns `RecordService` so I exported it.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/pocketbase/dist/pocketbase.es.d.mts b/node_modules/pocketbase/dist/pocketbase.es.d.mts
index 5dddb52..5fdcf1b 100644
--- a/node_modules/pocketbase/dist/pocketbase.es.d.mts
+++ b/node_modules/pocketbase/dist/pocketbase.es.d.mts
@@ -483,7 +483,7 @@ interface RecordSubscription<T = Record> {
     action: string;
     record: T;
 }
-declare class RecordService extends CrudService<Record> {
+export declare class RecordService extends CrudService<Record> {
     readonly collectionIdOrName: string;
     constructor(client: Client, collectionIdOrName: string);
     /**
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by ganigeorgiev** [comment]
The types should be exported in [v0.11.1 release](https://github.com/pocketbase/js-sdk/releases/tag/v0.11.1).
