### ISSUE TITLE
How to use Views for custom sql statements?

### ISSUE THREAD

**Issue by Mashiane** [pocketbase/js-sdk#158]
Hi there

Do we perhaps have examples in the js-sdk that addresses how to use Views?

Thank you so much.

**Comment by ganigeorgiev** [comment]
There is no special syntax or apis regarding the views since it is treated as read-only collection (aka. has only list/search and getOne() actions).

For SDK examples and docs of the supported actions, you can check the "API Preview" panel of your view collection.
