### ISSUE TITLE
Fr: Creation of collections of 'view' type by code

### ISSUE THREAD

**Issue by Mashiane** [pocketbase/js-sdk#159]
Hi

In the documentation on, https://pocketbase.io/docs/api-collections/, there is code to ceate a 'base' collection type.

![image](https://user-images.githubusercontent.com/5799306/222154670-06d579ed-814b-457e-b502-845b4774b9a6.png)

Is it possible to extend this for one to ceate a collection of 'view' type and specify their SQL for it?

Thank you so much.

**Comment by ganigeorgiev** [comment]
The above is just an example. I'll consider updating the documentation sometime in the future with more details, but the view collection creation is similar (you can refer to the body params description below the code samples).

In general, when creating a view collection via the API the SQL query must be passed in the `options.query` prop. The schema is generated automatically so you can leave it empty. For example:

```js
await pb.collections.create({
    name: "example",
    type: "view",
    listRule: null,
    viewRule: "@request.auth.id != ''",
    options: {
        query: "select id, name from posts",
    },
})
```

**Comment by ganigeorgiev** [comment]
I've updated the [Create collection](https://pocketbase.io/docs/api-collections/) example and added some more info to the request body parameters table.
