### ISSUE TITLE
How can I check if a token is valid?

### ISSUE THREAD

**Issue by oscadev** [pocketbase/js-sdk#165]
I have a collection that I have set so that only my node backend with admin permissions can modify, but I want users that are logged in to be able to modify the collection (through the node backend that runs some special logic). I can pass the user's token to the backend, but how can I check that the token is valid to prove the user is logged in?

**Comment by ganigeorgiev** [comment]
We don't have a dedicated token verification endpoint.

Instead you can send the token with the `authRefresh()` call. It throws an error on invalid or expired token, on success - returns a new token token with refreshed `exp` claim and up-to-date user data.

```js
pb.authStore.save(yourToken, null);

await pb.collection("users").authRefresh();
```
