### ISSUE TITLE
Issue with Import statement in Javascript

### ISSUE THREAD

**Issue by jspann93** [pocketbase/js-sdk#168]
Hello there! I'm a very inexperienced webdev so I apologize if this isn't the right forum for this, but I've looked everywhere and am currently at a loss. I'm trying to build a basic webpage that allows users to create a soccer lineup. I've been working on linking it with PocketBase so I can keep track of how many times each player and formation is selected. Essentially, when users hit the submit button, I'd like to update a count associated with each player name in my database. However, I'm running into an error I've been unable to resolve.

When I deploy my app (using fly.io), I get the following error message:

Uncaught TypeError: Failed to resolve module specifier "pocketbase". Relative references must start with either "/", "./", or "../".

That's referring to this line from from my Javascript file where I initially try to import PocketBase. I took this code straight from the Pocketbase Javascript SDK.

import PocketBase from 'pocketbase';

When I change that line of code to the filepath in my project where the PocketBase JS file is stored, or when I point it to the cdn, I get a different error message.

import PocketBase from '/js-sdk-master/dist/pocketbase.umd.js';

Uncaught SyntaxError: The requested module '/js-sdk-master/dist/pocketbase.umd.js' does not provide an export named 'default' (at lineup.js:5:8)

I'm sure I'm missing something silly but I feel like I've tried everything and can't figure it out. Using curly braces around PocketBase didn't work, I've tried a few different methods of formatting my script element in the HTML file, etc. Any help would be greatly appreciated and, again, I apologize if this isn't the right place for a question like this (feel free to delete this if that's the case).

<script src="/js-sdk-master/dist/pocketbase.umd.js"></script>
<script src="lineup.js" type="module"></script>

https://github.com/jspann93/USSoccerLineup

**Comment by ganigeorgiev** [comment]
Here is an example how to load and initialize the SDK if you want to load it manually via a script tag:


1. UMD

    ```html
    <script src="https://cdn.jsdelivr.net/gh/pocketbase/js-sdk@latest/dist/pocketbase.umd.js"></script>
    <script type="text/javascript">
        const pb = new PocketBase("https://example.com")

        ...
    </script>
    ```

2. ESM

    ```html
    <script type="module">
        import PocketBase from 'https://cdn.jsdelivr.net/gh/pocketbase/js-sdk@latest/dist/pocketbase.es.mjs'

        const pb = new PocketBase("https://example.com")
        ...
    </script>
    ```

**Comment by jspann93** [comment]
Thank you for the help! Your comment "if you want to use UMD, remove the type="module" from your script tag and the import statement inside it." was the one that did it for me. I didn't realize that the import statement wasn't required if I was loading the SDK manually with the script tag. When I deleted the type="module" and import statement, the page loaded fine. Thank you so much!
