### ISSUE TITLE
Bug: Cannot save when a column is called export

### ISSUE THREAD

**Issue by jerebtw** [pocketbase/js-sdk#169]
In a collection there is a column named "export" and when I try to edit this row, the admin UI loads forever and gives the following error message:

```bash
Uncaught TypeError: d.export is not a function
    at A (index-08378882.js:138:1285)
    at HTMLFormElement.$ (index-08378882.js:138:728)
    at HTMLFormElement.<anonymous> (index-08378882.js:1:3299)
```

**Comment by ganigeorgiev** [comment]
The fields in the SDK were aliased as part of the [v0.13.0 release](https://github.com/pocketbase/js-sdk/releases/tag/v0.13.0).

The error in the Admin UI will be fixed together with the upcoming PocketBase v0.14.0 release (most likely sometime next week).
