### ISSUE TITLE
Update record based on name field

### ISSUE THREAD

**Issue by jspann93** [pocketbase/js-sdk#170]
I am trying to understand how to update the 'count' field of a particular record based on the 'name' field. 

Here's the setup for my collection. Each record represents a player, which has a name (string) and a count (int). 
<img width="824" alt="image" src="https://user-images.githubusercontent.com/111022851/226954534-865a52e1-cf6c-4ce1-929e-da8814075d6a.png">

I can successfully create new records, but I can't figure out how to edit an existing record to increase the count.

In the code below, I check whether item, a string representing the name of the current player, is in a list of the names in the database called namesinDB. If if is, I try to increment the count by 1. If it is not, I create a new record with the name=item and count=1. That latter part successfully creates new records, but once a record exists, I can't seem to update the count. I believe the update function searches for a record by it's ID. Is there a way to search by a different value (name, in this case)? 

<img width="709" alt="image" src="https://user-images.githubusercontent.com/111022851/226955824-76ef65bd-39e5-4179-b9a8-88c24577f5ea.png">

console.log(item);
        //If the record already exists, increment the count
        if (namesinDB.includes(item)){
          console.log("Updating the count for " + item);
          var record1 = await pb.collection('men_player_selections').update('name' = item, {
            count: +1,
          });
        }
        //Otherwise, create the record
        else{
          //console.log("Creating a record for " + item);
          var record1 = await pb.collection('men_player_selections').create({
            name: item,
            count: 1,
          });

**Comment by ganigeorgiev** [comment]
In order to update a record you need to provide its `id` (aka. `update(id, data)`).

If you want to update a record using a different identifier, you can first fetch it with `getFirstListItem(filter)`.

**Comment by jspann93** [comment]
Thanks for the help!

The problem I'm having with this method is using getFirstListItem to select a record in which the name isn't hard coded. 

If I hard code a name in like "Test Player", it works fine:
var record = await pb.collection('men_player_selections').getFirstListItem('name="Test Player"');

But what I really want is to by able to search for the name stored in the variable called item. When I try it this way, I get an error. Using double quotes around "item" also wouldn't work because it would search for a record whose name is literally "item". What's the correct syntax in this case?
var record = await pb.collection('men_player_selections').getFirstListItem('name=item');

<img width="654" alt="image" src="https://user-images.githubusercontent.com/111022851/226971857-fbcd2358-07d1-401e-b1bc-a43d40bc45cf.png">

**Comment by jspann93** [comment]
Sorry, here's the error:
<img width="965" alt="image" src="https://user-images.githubusercontent.com/111022851/226972849-e730b4c1-e644-43fd-8426-d572be71eca2.png">

<img width="642" alt="image" src="https://user-images.githubusercontent.com/111022851/226972969-8255d6eb-bc37-4355-9b3d-4443d2dd0673.png">

**Comment by ganigeorgiev** [comment]
You can use [Template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) (backticks) to embed your dynamic value, something like:

```js
let name = 'item';
let record = await pb.collection('men_player_selections').getFirstListItem(`name="${item}"`);
```

_(note that the name value must be wrapped in a single or double quotes, otherwise it will be treated as identifier)_

**Comment by jspann93** [comment]
That works perfectly. You are an absolute legend. Thank you so much for the help!!! :)
