### ISSUE TITLE
Trouble with user registration

### ISSUE THREAD

**Issue by Ponkhy** [pocketbase/js-sdk#174]
Hello,

how can a user register/create an account themself?
By my understanding I should be able to just use this to achive it, since there is no specific registration function.
```js
await pb.collection('users').authWithPassword(email, password);
```

Unfortunately I'm always getting this error.
![image](https://user-images.githubusercontent.com/43121732/228004157-ad53303e-7598-413d-83d6-b8352e34b4bc.png)

Am I misunderstanding something here, or is there actually no way a user can create a account themself?
Many thanks!

**Comment by ganigeorgiev** [comment]
You can call `await pb.collection('users').create({...})`.

Note that to allow anyone to register, the `users` Create API rule must be empty.

**Comment by Ponkhy** [comment]
> You can call `await pb.collection('users').create({...})`.
> 
> Note that to allow anyone to register, the `users` Create API rule must be empty.

Perfect, thank you for the quick response!
I didn't think about to create a user like a normal record.
