### ISSUE TITLE
Why throw an error in the getFirstListItem function instead of just returning undefined?

### ISSUE THREAD

**Issue by Uziniii** [pocketbase/js-sdk#175]
https://github.com/pocketbase/js-sdk/blob/efa9f6ada350a3d6666e54a4140548a555d95427/src/services/utils/BaseCrudService.ts#L101

It would be simpler to return an undefined to mean that the query did not find anything.

**Comment by ganigeorgiev** [comment]
For consistency with the other "find one" type of methods. It is mentioned in the jsdoc comment:

> For consistency with `_getOne`, this method will throw a 404 ClientResponseError if no item was found.
