### ISSUE TITLE
Links behaving weirdly, seems like something to do with auth | PocketBase + SvelteKit

### ISSUE THREAD

**Issue by NerdvanaNC** [pocketbase/js-sdk#177]
I'm building a simple ToDo app to familiarize myself with the process (I'm fairly new to this), and I'm running into a weird issue involving links.

### Context

Here's some info about my project:

```
"@sveltejs/kit": "^1.5.0",
"vite": "^4.0.0",
PocketBase: v0.13.4
```

I'm only interacting with PocketBase on SvelteKit's server side, following the guidelines in the docs for working with SSR (Create a new PocketBase instance for each server-side request, etc).

My `hooks.server.js` file is nearly identical to the example in the docs; I've included it at the end for review.

### The Problem

Whenever I click a link in the project, it does nothing. Not even the usual behavior of an `<a>` tag on a static website. This lasts for a second or two, and then the link behaves as expected.

I've noticed that the link doesn't work until the following message is logged to the console, and then works fine:

`Cookie “pb_auth” has been rejected because it is already expired.`

_I've only been able to recreate this issue when the user is not logged in. Once the user is authenticated, both the issue and the console warnings go away._

### My theory

I believe this has something to do with how SvelteKit pre-fetches information from `<a>` tags. When I hover over a link in the project, the browser's status bar doesn't show anything, up until a second later SvelteKit is done (I assume) pre-fetching data.

Hovering over a link is also when the `Cookie “pb_auth” has been rejected because it is already expired.` is logged to the console (because SvelteKit runs the server hooks at that time again). Once that message has been logged to the console, the browser's status bar works correctly and clicking the link works as expected. But prior to this, clicking the link has no effect.

### What I've tried/thought about

I've thought about disabling pre-fetching, or changing it to `tap` instead of `hover`, but I feel that this would be a band-aid fix. What I'm really interested in knowing is how I can optimize/change/fix my implementation of PocketBase so that this issue doesn't happen at all; because I'm assuming I'm doing something wrong.

### Code Review

`hooks.server.js`
```
import PocketBase from 'pocketbase';

// https://github.com/pocketbase/js-sdk#ssr-integration

export async function handle({ event, resolve }) {
  // 1. Create a new PocketBase instance for each server-side request.
  event.locals.pb = new PocketBase('http://127.0.0.1:8090');

  // 2. "Load/Feed" your pb.authStore with data from the request cookie.
  event.locals.pb.authStore.loadFromCookie(event.request.headers.get('cookie') || '');

  // 2.5. Validate the user store we've received from the cookie.
  if (event.locals.pb.authStore.isValid) {
    try {
      await event.locals.pb.collection('users').authRefresh();
    } catch (_) {
      event.locals.pb.authStore.clear();
    }

    event.locals.user = structuredClone(event.locals.pb.authStore.model);
  } else {
    event.locals.user = null;
  }

  // 3. Perform your application server-side actions. I. E., let SvelteKit do its thing and resolve the event.
  const response = await resolve(event);

  // 4. Before returning the response to the client, update the cookie with the latest pb.authStore state.
  response.headers.append('set-cookie', event.locals.pb.authStore.exportToCookie());

  // 5. Return the response as handled by SvelteKit with the additional auth payload appended.
  return response;
}

// We can now access the authStore on the server by using "locals.user"
```

### Summary (tl;dr)

Links in the project don't work until SvelteKit is done pre-fetching data, and my presumption is that creating a new instance of PocketBase on every server request + validating the authStore from a cookie is causing a 1~2s bottleneck.

**Comment by ganigeorgiev** [comment]
I think I found the culprit. The issue doesn't seem related to PocketBase (you can comment for example the server hook and check the login/register links).

I'm not sure if it is a bug in SvelteKit or just an implementation detail of how preload/prefetch works when interactive elements (`button`, `a`) has interactive children, which usually is not allowed by spec:

> from https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element:
> **... there must be no [interactive content](https://html.spec.whatwg.org/multipage/dom.html#interactive-content-2) descendant and no descendant with the [tabindex](https://html.spec.whatwg.org/multipage/interaction.html#attr-tabindex) attribute specified.**

Or in other words, in `Avatar.svelte`:

```svelte
<div class="absolute right-10 top-10">
  <button class="btn btn-ghost mr-4"><a href="/login">Login</a></button>
  <button class="btn btn-primary"><a href="/register">Register</a></button>
</div>
```

replace with:

```svelte
<div class="absolute right-10 top-10">
  <a class="btn btn-ghost mr-4" href="/login">Login</a>
  <a class="btn btn-primary" href="/register">Register</a>
</div>
```

aka. don't wrap `a` tags inside `button` (or the opposite).

**Comment by ganigeorgiev** [comment]
Actually, the issue is not exactly the btn>a wrapping, but the fact that the `a` element is NOT the entire button, just the text. This is why when you hover or click on the a element it works.

But in any case, if you want the entire `button` to be a link, remove the wrapping and move the `btn` classes to the `a` element.

**Comment by NerdvanaNC** [comment]
Damn. :laughing: 

Thank you so much for your help, I wouldn't have tracked this down myself. I realize now that hovering over the `<a>` tag was working just fine, and hovering over the `<button>` tag was doing nothing.

The `console.warnings` had me worried.

Thanks again! :pray:
