### ISSUE TITLE
Create admin via migrations

### ISSUE THREAD

**Issue by Ponkhy** [pocketbase/js-sdk#178]
Hello,

would it be possible to create a admin user with a fixed email and password with a `.js` migration file and if yes how would that look like?

Many thanks!

**Comment by ganigeorgiev** [comment]
Create a blank migration with `./pocketbase migrate create "create_admin"`.

And edit the file with something like:

```js
migrate((db) => {
  const admin = new Admin()

  admin.email = "test@example.com"
  admin.setPassword("1234567890");

  return Dao(db).saveAdmin(admin)
}, (db) => {
  const dao = new Dao(db)

  const admin = dao.findAdminByEmail("test@example.com")

  return dao.deleteAdmin(admin)
})
```
