### ISSUE TITLE
Why Admin's avatar property has type of number and not of string?

### ISSUE THREAD

**Issue by Verrok** [pocketbase/js-sdk#180]

**Comment by ganigeorgiev** [comment]
It is an index of a predefined set of avatar images.

The only purpose of the admin avatars are just to differentiate more easily the individual admin accounts. Eventually in the future we may replace them with something else (eg. autogenerated color coded intials) but for now I don't see much point of investing time of doing it.

**Comment by Verrok** [comment]
> It is an index of a predefined set of avatar images.
> 
> The only purpose of the admin avatars are just to differentiate more easily the individual admin accounts. Eventually in the future we may replace them with something else (eg. autogenerated color coded initials) but for now I don't see much point of investing time doing it.

Thanks
