### ISSUE TITLE
Can't see users token for auth

### ISSUE THREAD

**Issue by Ebibeck** [pocketbase/js-sdk#185]
![IMG_20230415_214515_573.jpg](https://user-images.githubusercontent.com/92293938/232255001-ca55823f-e4b9-4249-98cf-2c87f36914e0.jpg)

**Comment by ganigeorgiev** [comment]
I don't understand what do you mean.

You can access the token after authorization either by inspecting the auth response or `pb.authStore.token`.

If that doesn't help, please elaborate and/or provide a code sample that illustrates what you are trying to do.

**Comment by Ebibeck** [comment]
When I authenticate my user the token doesn't show

**Comment by ganigeorgiev** [comment]
@Ebibeck Where do you expect it to show? Could you share a code sample (not an image) what you are doing?

**Comment by ganigeorgiev** [comment]
@Ebibeck If you haven't already, please check https://pocketbase.io/docs/authentication/.

**Comment by Ebibeck** [comment]
If you login a user your response you will get back is a jwt and and the user model right?
Am just getting the user model not the token

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it calling:

```js
const authData = await pb.collection('users').authWithPassword('YOUR_USERNAME_OR_EMAIL', '1234567890');

console.log(authData.token)
// or 
console.log(pb.authStore.token)
```

If you need further help, please at least provide a code sample to understand what you are doing.

**Comment by Ebibeck** [comment]
Ok

**Comment by Ebibeck** [comment]
I think I have got it to work thanks for the help... I appreciate
