### ISSUE TITLE
OAuth2 Issue

### ISSUE THREAD

**Issue by Ponkhy** [pocketbase/js-sdk#188]
Hello,

I'm currently trying to implement a Discord authentication into my app, but I'm always getting the following error.
Does anyone have an idea what could cause it?

```json
{
  "errorDetails": "code=400, message=Unmarshal type error: expected=string, got=object, field=provider, offset=13, internal=json: cannot unmarshal object into Go struct field RecordOAuth2Login.provider of type string",
  "errorMessage": "An error occurred while loading the submitted data."
}
```

Used code:
```js
await pb.collection('users').authWithOAuth2Code({ provider: name, code: code, codeVerifier: codeVerifier, redirectUrl: redirectUrl });
```

Many thanks!

**Comment by ganigeorgiev** [comment]
`authWithOAuth2Code` arguments are positional, aka. you need to pass each argument value one by one:

```js
await pb.collection('users').authWithOAuth2Code(name, code, codeVerifier, redirectUrl);
```

Alternatively, if you are using PocketBase v0.15+, you can also use the simplified "all in one" `authWithOAuth2` call as shown in https://pocketbase.io/docs/authentication/#oauth2-integration.

**Comment by Ponkhy** [comment]
> `authWithOAuth2Code` arguments are positional, aka. you need to pass each argument value one by one:
> 
> ```js
> await pb.collection('users').authWithOAuth2Code(name, code, codeVerifier, redirectUrl);
> ```
> 
> Alternatively, if you are using PocketBase v0.15+, you can also use the simplified "all in one" `authWithOAuth2` call as shown in https://pocketbase.io/docs/authentication/#oauth2-integration.

Yea I've tried that too and also didn't work, I got this:
```json
{
  "errorMessage": "oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\": \"invalid_grant\", \"error_description\": \"Invalid \\\"redirect_uri\\\" in request.\"}"
}
```
Unfortunately I cannot use the new method with `authWithOAuth2`, since it's running on server side.

**Comment by ganigeorgiev** [comment]
Are you sure that you are passing the correct redirect url as it is configured in your OAuth2 app (note that some provider treat `127.0.0.1` and `localhost` as different hosts)?

Could you provide a code sample?
