### ISSUE TITLE
How to create a constraint using the sdk?

### ISSUE THREAD

**Issue by Darkmift** [pocketbase/js-sdk#189]
Hi,

Trying to look over the docs and cant find a way to make a constraint of multiple fields...

Would appreciate your help.

**Comment by ganigeorgiev** [comment]
Could you elaborate what do you mean?

If you want to apply a filter for 1+ fields you can combine the filter expressions with `&&` (AND) or `||` (OR) operators:

```js
await pb.collection.getList(1, 30, {
    filter: "fieldA > 30 && fieldB = 'test'"
});
```

**Comment by Darkmift** [comment]
> Could you elaborate what do you mean?
> 
> If you want to apply a filter for 1+ fields you can combine the filter expressions with `&&` (AND) or `||` (OR) operators:
> 
> ```js
> await pb.collection.getList(1, 30, {
>     filter: "fieldA > 30 && fieldB = 'test'"
> });
> ```

I mean adding a unique constraint

like so

```sql
CREATE TABLE internship_instructor_relation (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    instructorId INTEGER NOT NULL,
    internshipId INTEGER NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (instructorId, internshipId),
    FOREIGN KEY (instructorId) REFERENCES instructors(id),
    FOREIGN KEY (internshipId) REFERENCES internships(id)
);
```

**Comment by ganigeorgiev** [comment]
If you are using PocketBase v0.14+, you can add index or unique constraints from the _Admin UI > {your collection} > "Edit collection" (settings cogwheel) > "New index"_:

![edit_collection](https://i.imgur.com/LqjogwT.png)

![index_popup](https://i.imgur.com/RlytUoc.png)

---

If you want to add the index via the JS SDK, you can send it as part of the collection create/update data, something like:

```js
await pb.collections.update("ID_OR_NAME", {
    indexes: [
        "CREATE INDEX `idx_rYevjnT` ON `example` (..)",
    ],
});
```
_For all available collection data props you can check https://pocketbase.io/docs/api-collections/._

**Comment by Darkmift** [comment]
I am using this for a while...is there a migration I need to follow? 

The ui does not.have these options.

**Comment by Darkmift** [comment]
Hey,

Thank you for your help!

![image](https://user-images.githubusercontent.com/12433441/235346964-abf70aa6-5140-4fa9-ad30-f41e4edfbb21.png)

It seems the ui is v0.13
I replaced the exe with `pocketbase_0.15.2_windows_amd64.zip`

and ran  `npm i pocketbase@latest`
which installed: ` "pocketbase": "^0.14.3",`

I get :

```
./pocketbase.exe serve
panic: Failed to apply migration 1679943781_add_indexes_column.go: indexes: (1: Failed to create index idx_unique_sedczgl5 - constraint failed: UNIQUE constraint failed: members.email (2067)..).

goroutine 25 [running]:
github.com/pocketbase/pocketbase/cmd.NewServeCommand.func1(0xc000004f00?, {0x1937d98?, 0x0?, 0x0?})
        /home/runner/work/pocketbase/pocketbase/cmd/serve.go:38 +0xeae
github.com/spf13/cobra.(*Command).execute(0xc000004f00, {0x3294790, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc000342300)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/pocketbase/pocketbase.(*PocketBase).Execute.func2()
        /home/runner/work/pocketbase/pocketbase/pocketbase.go:172 +0x65
created by github.com/pocketbase/pocketbase.(*PocketBase).Execute
        /home/runner/work/pocketbase/pocketbase/pocketbase.go:170 +0xf9
        ```
        
       I would appreciate your help...let me know if you need any other info

**Comment by ganigeorgiev** [comment]
Make sure that you don't have `members` records with empty or duplicated `email` field value.

**Comment by Darkmift** [comment]
Thak you!
after finding the duplicate and removing the serve with new exe did apply and now I see the new UI features <3
