### ISSUE TITLE
Feature request: fetch options

### ISSUE THREAD

**Issue by kennethklee** [pocketbase/js-sdk#19]
Can we add default fetch options such as `{follow: 'manual'}`. See https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#supplying_request_options

I've put pocketbase behind an SSO proxy. When auth is needed, the proxy redirects to a login page.

In that case, doing any fetch request (i.e. `Records.getList`) will automatically follow the redirect and hit a valid html login page, which fails silently. doesn't even throw an error.

my proposal is adding something like:

`client.setDefaultFollow('manual')`
`client.setDefaultCredentials('include')`
`client.setDefaultCache('no-cache')`

And also to throw an error if `response.status >= 300`.

**Comment by ganigeorgiev** [comment]
This was recently discussed in https://github.com/pocketbase/js-sdk/issues/18.
I would consider adding a way to set a default `fetch` configuration options in the next minor version of the SDK (somewhere around next week).

About following redirects and throwing if `response.status >= 300` - you usually want to follow redirects because, depending of your network infrastructure, there could be several non-auth layers before reaching the application (eg. load balancer).
I'm not sure how easy is to customize the SSO proxy you are using, but in my opinion the more correct way to resolve the issue with the silently failing redirect would be to redirect to the login page with 401/403 and you'll be able to catch the error.

**Comment by kennethklee** [comment]
awesome!

> About following redirects and throwing if response.status >= 300 - you usually want to follow redirects because, depending of your network infrastructure, there could be several non-auth layers before reaching the application (eg. load balancer).

a user in that scenario can leave the default, `follow: 'redirect'`, and redirect responses will never be encountered, only the final response.

thinking about it, we're checking for successful client responses, so a check for `response.ok` would be technically correct. as per https://developer.mozilla.org/en-US/docs/Web/API/Response/ok.

if checking for successful client responses is not possible, perhaps expose the response object? or any of the following would do: response.ok, response.status, response.redirected. though, this would likely be the most difficult option.

**Comment by ganigeorgiev** [comment]
@kennethklee In the recent [v0.3.0 release of the SDK package](https://github.com/pocketbase/js-sdk/releases/tag/v0.3.0), you could make use of the `beforeSend` and `afterSend` functional hooks to adjust, inspect, throw, etc. the request and response data:

```js
const client = new PocketBase('http://localhost:8090');

client.beforeSend = function (url, reqConfig) {
    // For list of the possible reqConfig properties check
    // https://developer.mozilla.org/en-US/docs/Web/API/fetch#options
    reqConfig.headers = Object.assign(reqConfig.headers, {
        'X-Custom-Header': 'example',
    });

    return reqConfig;
};

client.afterSend = function (response, data) {
    // do something with the response state
    console.log(response.status);

    return Object.assign(data, {
        // extend the data...
        "additionalField": 123,
    });
};
```

More details you could find in the docblock comment of the function hooks - https://github.com/pocketbase/js-sdk/blob/d87034337ff3ce24c972a45646db12236e86a2cf/src/Client.ts#L21-L63

The above should cover your use case and enables you to throw on 200 response or to disable following redirects.

**Comment by kennethklee** [comment]
awesome, thanks for exposing the response object!
