### ISSUE TITLE
Having trouble uploading files

### ISSUE THREAD

**Issue by Fattigman** [pocketbase/js-sdk#191]
I am trying to automate uploading of local files to a pocketbase collection for storage. I am running this script with node:
```js
const fs = require(‘fs’);
async function main() {
  const pocketbase = (await import(‘pocketbase’)).default;
  const pb = new pocketbase(‘<pocketbase_url>‘);
  const formData = new FormData();
  // Read files from local system
  const files = fs.readdirSync(‘<path/to/folder>’);
  files.forEach(file => {
    formData.append(‘multiqc_report’, fs.readFileSync(`<path/to/folder/${file}`));
  });
  // Upload and create new record
  const createdRecord = await pb.collection(‘projects’).update(‘<obj_id>’,formData);
  console.log(createdRecord);
}
main();
```
I get 200 response but no file is uploaded. The formData object looks like what I would expect it to:
```FormData
FormData {
  [Symbol(state)]: [
    {
      name: 'multiqc_report',
      value: '<!DOCTYPE html>\n' +
        '<html lang="en">\n'...1285808 more characters
     }
  ] 
}
```
Where 'multiqc_report' is the field which the data should be stored.
Versions:
pocketbase: 0.10.4
pocketbase js sdk: 0.14.3
node: v18.13.0

Can someone please point out what I am doing wrong?

**Comment by ganigeorgiev** [comment]
The `FormData` file field value must be a [`Blob`](https://developer.mozilla.org/en-US/docs/Web/API/Blob) or [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File) instance, aka. you could try:

```js
formData.append("file", new Blob([fs.readFileSync(`<path/to/folder/${file}`)]), "something.png");
```

**Comment by Fattigman** [comment]
That worked! Thank you very much!
