### ISSUE TITLE
Consider changing or documenting RecordAuthResponse.token returned from Oauth to make intended usage clearer?

### ISSUE THREAD

**Issue by jjgmckenzie** [pocketbase/js-sdk#194]
In the context of Oauth, RecordAuthResponse.token could reasonably be interpreted to refer to an "access token" provided in response from some APIs

I foolishly assumed this, and had to wait until my second cup of coffee kicked in before I realized why all my authorization requests were being denied.

**Comment by ganigeorgiev** [comment]
I've added a JSDOC comment to the response interface in the `develop` branch to clarify the `token` usage.

https://github.com/pocketbase/js-sdk/blob/ded8f1b680b0d76259ca96f24db3be3d8fead83d/src/services/RecordService.ts#L15-L27
