### ISSUE TITLE
ClientResponseError: Something went wrong while processing your request

### ISSUE THREAD

**Issue by Dredious** [pocketbase/js-sdk#195]
Afternoon, 

Pretty sure its me, I am just trying to use a computer separate to my local machine to test but im getting the ClientResponseError.

I'm guessing it is a CORS issue as on my local machine the realtime works fine. I am just running pocketbase standard 127.0.0.1:8090 and 0.0.0.0:8090.

Not sure what the solution is.

**Comment by ganigeorgiev** [comment]
You can wrap the call with `try/catch` inspecting error object to see if there is more detailed message, eg:

```js
try {
    await pb.collection("example").getList(1, 30);
} catch (err) {
    console.log(err.response)
    console.log(err.originalError)
}
```

**Comment by Dredious** [comment]
Yeh I get Error: Failed to establish realtime connection, and before that Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:8090/api/realtime.

**Comment by ganigeorgiev** [comment]
> Can you add trusted IP's to Pocketbase?

I'm not sure that I understand what do you mean. PocketBase by default allows all origins (aka. `*`), unless you've explicitly set the `--origins` flag.

Are you sure that your localhost is accessible from the network you are testing?

**Comment by ganigeorgiev** [comment]
I don't know how to reproduce it.

Are you able to access the Admin UI when you try with `http://yourlocalip:8090/_/`?
Note that when you initialize the JS SDK you have to use also the public address (in your case your local ip instead of 127.0.0.1/localhost)

Alternatively, you can also expose your localhost with something like [ngrok](https://ngrok.com/).

**Comment by Dredious** [comment]
Ok in my svelte app i have a hooks.server.ts running a handle function.

```js
export const handle = (async ({ event, resolve }) => {
    event.locals.pb = new PocketBase('http://192.168.1.15:8090');
    const response = await resolve(event);
    return response;
}) satisfies Handle;
```

and pocketbase is also running on http://192.168.1.15:8090'
I can access the Admin UI from my dev computer and the second computer.
However on my second computer I can use Realtime or update the database.

<img width="878" alt="Screenshot 2023-05-17 at 9 21 56 am" src="https://github.com/pocketbase/js-sdk/assets/4412512/29bbb3a2-3177-4fe0-8b64-dfe3ea34db63">

Looks like RealTime runs separately on 127.0.0.1 plus CORS issue.

**Comment by Dredious** [comment]
Ok solved it, the issue is you need to have a PocketBase instance on the client side to, I was trying to pass it around using the handle function as that runs on every request.
