### ISSUE TITLE
Any way to run SQL queries using SDK?

### ISSUE THREAD

**Issue by hackertron** [pocketbase/js-sdk#196]
Hello, is there a way to run sql queries using sdk or in pocketbase in general ? 
I am trying to avoid manually creating database schema by dashboard using clicks etc

**Comment by ganigeorgiev** [comment]
Executing raw SQL statements with the JS SDK is not supported.

If you want to manage your schema programmatically, you can check https://pocketbase.io/docs/migrations/.
