### ISSUE TITLE
Database rollback on error

### ISSUE THREAD

**Issue by hamsyy60** [pocketbase/js-sdk#197]
Hello I have the following question : 
If i run multiple queries in one js function and one of them erorrs, is there any premade function to rollback every query in that function 

example: 

function(){

pb.createname ....

pb.createuser(name = pb.createname). //this crashes

pb.addUserToGroup(user = pb.createuser)

}

in this case the pb.addUserToGroup wont run anyways because the 2nd query crashed but the "pb.createname" worked and I want to rollback it because the function worked only partly

i hope you understood my problem 

Thank you

**Comment by ganigeorgiev** [comment]
The web APIs currently doesn't support transactions. At the moment the only way to submit a transaction is to [register a custom route with Go](https://pocketbase.io/docs/router/#register-new-route) and wrap your queries within [`app.Dao().RunInTransaction()`](https://pocketbase.io/docs/database/#transaction).

Bulk transactional create/update/delete APIs will be implemented in the future as part of https://github.com/pocketbase/pocketbase/issues/48.
