### ISSUE TITLE
How to filter one to many relation?

### ISSUE THREAD

**Issue by MuhammadKhizar7** [pocketbase/js-sdk#199]
Here is my code for filtering 
```js
  const getList = async (
    page,
    perPage,
    location = 'mdk7ej7t9oiqxcy',
    service = ''
  ) => {
    return useAsyncData(async (nuxtApp) => {
      const record = await nuxtApp.$pb
        .collection('profile')
        .getList(page, perPage, {
          sort: 'created',
          expand: 'user, service, operation_areas',
          filter: `service="${service}" || operation_areas="${location}"`,
        })
      return structuredClone(record)
    })
  }

```
service work as it is one-to-one relation but operation_areas is one-to-many relationship it is not work as its array of ids
```sql
SELECT COUNT(DISTINCT [[profile.id]]) FROM `profile` WHERE (([[profile.service]] = '' OR [[profile.service]] IS NULL) OR [[profile.operation_areas]] = 'mdk7ej7t9oiqxcy')
```
also did not work when I use only ```  filter: ` operation_areas="${location}"`,```

**Comment by ganigeorgiev** [comment]
Multi-relation field values are stored as serialized json, so if you want to check only whether one of the relation has the location id, you can do something like:

```js
filter: `service="${service}" || operation_areas.id ?= "${location}"`,
```
(_the `?` operator prefix converts the expression to "any/at least one of" condition_)

**Comment by MuhammadKhizar7** [comment]
Thanks for quick response. One more thing it did not work when default value is  empty

**Comment by MuhammadKhizar7** [comment]
sure 
```js
const getList = async (page, perPage, service = '', location = '') => {
    return useAsyncData(async (nuxtApp) => {
      console.log(service, location)
      const record = await nuxtApp.$pb
        .collection('profile')
        .getList(page, perPage, {
          sort: 'created',
          expand: 'user, service, operation_areas',
          filter: `service="${service}" || operation_areas.id ?="${location}"`,
        })
      return structuredClone(record)
    })
  }
```
location and service is empty string

**Comment by ganigeorgiev** [comment]
Sorry, I'm still not sure that I understand what do you mean.

In case `location` is empty, the filter will require `service="${service}"` to be true OR return only records with empty `operation_areas`.
I've tested it locally with a sample multi-relation field and similar condition and it works fine for me. If you want to disallow returning records with empty `operation_areas` you can add an extra check, but please note that this is true also for `service` field if it is not required:

```js
service="${service}" || (operation_areas:length >0 && operation_areas.id ?="${location}")
```

If you are not experiencing this, please file a new [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) with more details about your setup - PocketBase and JS SDK versions and ideally a minimal reproducible example with exported collections configuration (_you can export your collections from the Admin UI > Settings > Export collections_).
