### ISSUE TITLE
Feature request (Low Priority): additional values for the Auth ClientResponseError

### ISSUE THREAD

**Issue by sagudelo1200** [pocketbase/js-sdk#20]
Thank you for creating this project! it looks amazing!

The values I suggest to add to the response 400 would be the following:

When a user logs in via email and password:
- EMAIL: User not found: if the email sent is not an existing user.
- PWD: Incorrect password: If the user exists but the email/password combination does not work.

When a user is created via (POST /api/users):
- EMAIL: User already exists: if the email is already in use (user or admin model).
- PWD: Invalid password: If the password does not meet certain criteria (minimum 8 characters, combination of numbers and letters, etc).

It is worth mentioning that I did not test all these 400 response values, only those of Auth via Email but I based on the API documentation, and there it does not indicate these response values.

**Comment by ganigeorgiev** [comment]
Hi,

The admin and user auth error responses are intentionally generic to avoid accounts enumeration (eg. when a malicious user tries to guess the admin/user email and password).

The error message for such cases by default is something like "Failed to authenticate.", but when in debug mode (aka. started with `--debug`) you'll find a little more details in the error response object (eg. missing user, invalid password, etc.). The more detailed errors are also available in the "Log requests tab in the Admin UI"
