### ISSUE TITLE
[Help] Single script tag inline include sdk and import LocalAuthStore

### ISSUE THREAD

**Issue by pnmcosta** [pocketbase/js-sdk#200]
Hi,

Probably not 100% related to this project, but more so on how to import assets in a browser, but I searched wide and couldn't find the correct answer, or I didn't use the right terms 🤣 - hopefully I could have some direction here.

I'm working on a project that I need to have a single js script to be included in a checkout page that should import PB's sdk to interact with my project's API.

My `script.js` is essentially injecting pb's sdk from a CDN and once it loads I initialize a global with an instance of PB:

```
var s = doc.createElement('scr' + 'ipt');
s.onload = function () {
    window.__PB = new PocketBase("https://my-pb.instance.com/")
}
s.src = 'https://cdnjs.cloudflare.com/ajax/libs/pocketbase/0.15.0/pocketbase.umd.js';
s.integrity = 'sha512-+T0HuIsFk1XAoh1ew6z8uRnPFM80Hwu3e7+ARaOdk3b20kTh6tf68wfq3NsCgSPa8Sl9qafAD8BPcHazcnptGw==';
s.referrerPolicy = 'no-referrer';
s.crossOrigin = 'anonymous';
document.getElementsByTagName('head')[0].appendChild(s);
``` 

This works great, but I want to override the LocalAuthStore key to something unique other than `pocketbase_auth` but I'm unable to access it in anyway from the umd import.

Should I be using any other format instead? This is meant for as wide browser support as possible, potentially even mobile. I'm more experienced with backend than frontend, hence the noob question! 

Thank you for any help in advance.

**Comment by ganigeorgiev** [comment]
You can try with the ESM bundle. It has a good browsers support - https://caniuse.com/?search=ESM. For example:

```html
<script type="module">
    import PocketBase, { LocalAuthStore } from 'https://cdn.jsdelivr.net/gh/pocketbase/js-sdk@master/dist/pocketbase.es.mjs'

    const pb = new PocketBase("http://127.0.0.1:8090", new LocalAuthStore("something"));
    
    ...
</script>
```

Alternatively, if you really want to use the UMD bundle, one slightly hacky workaround would be to change the "private" `authStore.storageKey` prop:

```html
<script src="https://cdn.jsdelivr.net/gh/pocketbase/js-sdk@master/dist/pocketbase.umd.js"></script>
<script type="text/javascript">
    const pb = new PocketBase("http://127.0.0.1:8090");
    // the field is technically marked "private" but you still should be able to access it
    // if you get a lint warning you can try changing it to dynamic prop, eg. pb.authStore["storageKey"] = ...
    pb.authStore.storageKey = "test";

    ...
</script>
```

**Comment by pnmcosta** [comment]
Superb, many thanks, the UMD solution works for me.
