### ISSUE TITLE
Pocketbase client with NodeJS and TS compile error

### ISSUE THREAD

**Issue by teddybee** [pocketbase/js-sdk#202]
I would like to use a small nodejs app to seed a Pocketbase collection.

The errors that I got with tsc:
```
node_modules/@types/eventsource/dom-monkeypatch.d.ts:8:11 - error TS2430: Interface 'Event' incorrectly extends interface '{ readonly bubbles: boolean; cancelBubble: () => void; readonly cancelable: boolean; readonly composed: boolean; composedPath(): [(EventTarget | undefined)?]; readonly currentTarget: EventTarget | null; ... 10 more ...; readonly type: string; }'.
  Types of property 'cancelBubble' are incompatible.
    Type 'boolean' is not assignable to type '() => void'.

8 interface Event {
            ~~~~~

node_modules/pocketbase/dist/pocketbase.es.d.mts:475:60 - error TS2304: Cannot find name 'EventListener'.

475     unsubscribeByTopicAndListener(topic: string, listener: EventListener): Promise<void>;
                                                               ~~~~~~~~~~~~~

node_modules/pocketbase/dist/pocketbase.es.d.mts:908:31 - error TS2304: Cannot find name 'RequestInit'.

908 interface SendOptions extends RequestInit {
                                  ~~~~~~~~~~~

node_modules/pocketbase/dist/pocketbase.es.d.mts:971:28 - error TS2304: Cannot find name 'Response'.  

971     afterSend?: (response: Response, data: any) => any;
                               ~~~~~~~~
```
node: 18.x,
typescript: 4.9.5, 
pocketbase: 0.15.0,
my tsconfig file:
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "NodeNext",
    "lib": [
      "esnext"
    ],
    "allowJs": true,
    "outDir": "build",
    "rootDir": "src",
    "strict": true,
    "noImplicitAny": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    //"skipLibCheck": true
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules"
  ]
}
```
Is there anything that I missed, or pocketbase not working with "server side"? 
I authenticate my seeder as a regular pb user.

**Comment by ganigeorgiev** [comment]
PocketBase should work fine server-side with eventually some polyfill that maybe required depending on your env as listed in https://github.com/pocketbase/js-sdk#nodejs-via-npm.

I suspect that the error is something related to the TS config. I'll try to investigate it a little bit later this week.

**Comment by ganigeorgiev** [comment]
@teddybee Could you create a minimal reproducible repo or at least attach your `package.json` so that I can try to recreate the issue?

Notice that the first error is something related to the eventsource polyfill types and it is possible that some of your dependencies are conflicting.

**Comment by ganigeorgiev** [comment]
I was able to reproduce the issue (kind of) when loading `@types/eventsource`. It something with event source types is conflicting with the native types but I'm not sure what exactly.

As a workaround, you can:
- remove the explicit `lib` definition from your tsconfig
- use require statements to avoid the "missing eventsource types" error (eg. `const eventsource = require("eventsource")`; you may have to install `@types/node`).

OR if you don't use the realtime subscriptions apis you can just remove the eventsource dependency.

I'll close the issue for now as I don't think a change is required in the SDK, but if you are still not able to resolve the issue, feel free to let me know and I'll try to investigate it further.
