### ISSUE TITLE
DateTime presentation is different than JS Date

### ISSUE THREAD

**Issue by teddybee** [pocketbase/js-sdk#203]
I have a DateTime field in my collection schema.
I send up a Date typed field (typescript), but when I get back the stored object the DateTime field changed. Some unit tests failed in my project.
```
+   endTime: '2023-07-24T17:00:00.000Z', //plain TS object that I sent in
-   endTime: '2023-07-24 17:00:00.000Z', //object get back form pb.create without a T
 ```
 
 Is it a bug, or I can set the format in the backend somehow?
 The first one is the ISO_8601 format.

**Comment by ganigeorgiev** [comment]
The `date` field format can't be changed at the moment.

Note that the format is in ISO8601 just the time delimiter is empty space. This was done for backward compatibility in order to minimize the breaking changes - https://github.com/pocketbase/pocketbase/issues/472#issuecomment-1255056640.

**Comment by teddybee** [comment]
Ok, but isn`t it could be done in the js client`s code to get the same?

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand what do you mean.

The `date` field value is stored and returned as plain string in the format "Y-m-d H:i:s.uZ". This format is not configurable at the moment.

**Comment by teddybee** [comment]
A simple change in the client (side) lib that solves the incompatiblity with the JS Date.

**Comment by ganigeorgiev** [comment]
> A simple change in the client (side) lib that solves the incompatiblity with the JS Date.

We can't safely change it, because as mentioned previously, the date value would be stored differently and it will not be consistent (eg. when you perform a web search using the `filter` parameter you'll have to convert the date back to the original).

**Comment by teddybee** [comment]
The T is compulsory according to W3C
https://www.w3.org/TR/NOTE-datetime

**Comment by ganigeorgiev** [comment]
This is not a specification of iso8601. A lot of tools support both empty space and `T` as separator as earlier versions of the standard allowed omitting the `T`.
The reason why we use space is for backward compatibility reasons, explained in https://github.com/pocketbase/pocketbase/issues/472#issuecomment-1255056640.

Once we add contextual support to the filters syntax, which will allow us to do date value normalizations behind the scene when one of the operands is a `date` field, we may change the format to the more standard one.
