### ISSUE TITLE
Feature request: Fetch client

### ISSUE THREAD

**Issue by Fractal-Tess** [pocketbase/js-sdk#207]
Using meta frameworks like SvelteKit sometime fetch calls to be made via the special `fetch` provided by the framework in load files. It would be nice if there is an API that allows the pocketbase instance to use an explicitly provided `fetch` function.

**Comment by ganigeorgiev** [comment]
This will be implemented soon as part of the planned JS SDK refactoring (_together with the custom headers and request options_).

_I'll keep the issue open for easier tracking._

**Comment by ganigeorgiev** [comment]
Closing as it was implemented in `v0.17.0-rc1`.
For details and feedback please check the discussion in the main repo - https://github.com/pocketbase/pocketbase/discussions/3134.
