### ISSUE TITLE
Help: How can I use JSDoc instead of TypeScript for Custom Record Types?

### ISSUE THREAD

**Issue by renatocaliari** [pocketbase/js-sdk#208]
How can I use JSDoc instead of TypeScript for Custom Record Types? Is it possible?

----
Reference:
- Custom Record types: https://github.com/pocketbase/js-sdk#custom-record-types

**Comment by ganigeorgiev** [comment]
I don't think an easy way as with the TypeScript generics but there are several options you can try:

- Use inline `/** @type ... */` above each call:
   ```js
   /** @type Promise<Something> */
   const result = pb.collection("example").getList(1, 25);
   ```

- Create local wrapper function(s) and anotate them with jsdoc:
   ```js
    /**
     * @return {Promise<Something>}
     */
    function getAllExamples() {
        return pb.collection("example").getFullList();
    }
   ```

**Comment by renatocaliari** [comment]
That's it! thank you @ganigeorgiev .
