### ISSUE TITLE
The WeChat applet imports pocketbase through npm, and the AbortController is undefined when using await pb.collection

### ISSUE THREAD

**Issue by dong-lufei** [pocketbase/js-sdk#211]
WeChat applet environment does not have webAPI

So I'm going to use an http request, so what's the maximum perPage size, 500 or 1000, and I have a lot of data and I'd like to request it all at once

**Comment by ganigeorgiev** [comment]
> WeChat applet environment does not have webAPI

I'm not familiar with WeChat and its supported APIs, but you can try with a `fetch` polyfill, eg:

```js
// npm install cross-fetch --save
import 'cross-fetch/polyfill';
```

> So I'm going to use an http request, so what's the maximum perPage size, 500 or 1000, and I have a lot of data and I'd like to request it all at once

The maximum list/search pagination size at the moment is 500. Note that fetching many items at once may starve your server resources and it may be better to lazy load or batch the requests.

**Comment by dong-lufei** [comment]
@ganigeorgiev I'm in Tencent's wechat mini program
I installed it, but still get the same error.
```sh
npm i pocketbase
npm i cross-fetch
```
import PocketBase from "pocketbase"
import "cross-fetch/polyfill"

onLaunch(async () => {
  console.log("【进入 App Launch】")
  
  const pb = new PocketBase("https://my.com/release")
  console.log("onLaunch-pb", pb)
  const authData = await pb.collection("users").authWithPassword("xxx", "yyy")
  console.log("onLaunch-authData", authData)
})
```
Running result: H5 is normal, but the WeChat applet reports an error:
```
【进入 App Launch】                                                  app.js? [sm]:13 

onLaunch-pb Client {cancelControllers: {…}, recordServices: {…}, enableAutoCancellation: true, baseUrl: "https://...", lang: "en-US", …}                           vendor.js? [sm]:2537 

[Vue warn]: Unhandled error during execution of onLaunch 
  at <App>                                                          vendor.js? [sm]:2537

vendor.js? [sm]:2783 ReferenceError: AbortController is not defined
    at Client.<anonymous> (vendor.js? [sm]:7654)
    at step (vendor.js? [sm]:6665)
    at Object.next (vendor.js? [sm]:6674)
    at vendor.js? [sm]:6611
    at new Promise (<anonymous>)
    at __awaiter (vendor.js? [sm]:6589)
    at Client.send (vendor.js? [sm]:7649)
    at RecordService.authWithPassword (vendor.js? [sm]:7155)
    at _callee$ (app.js? [sm]:14)
    at l (regeneratorRuntime.js:1)(env: Windows,mp,1.06.2306020; lib: 2.32.3)
```
