### ISSUE TITLE
Oauth 2 sometimes not work on Mobile

### ISSUE THREAD

**Issue by hungcrush** [pocketbase/js-sdk#212]
I'm trying Safari and Chrome on my Iphone. Safari is not open anything. Chrome open confirm notice... 

Do you know that? and have any idea for it 😭

**Comment by ganigeorgiev** [comment]
Without a code sample I'm not sure what could be the issue.

I suspect that the popup is being blocked for some reason. You can provide your own url opener by specifying the `urlCallback` prop and/or check the alternatives in https://github.com/pocketbase/pocketbase/discussions/2429.
