### ISSUE TITLE
SSL enabled client requests still showing visible plain text passwords (PB SDK or SvelteKit?)

### ISSUE THREAD

**Issue by consultingninja** [pocketbase/js-sdk#214]
Hello @ganigeorgiev ,
Firstly, I am a big fan of your work. Secondly I have a question.  I have a SvelteKit (v1.20.4) app that I paired with PocketBase (v16.7)  I was curious so I fired up wireshark and was watching traffic as I performed actions.  I noticed the client.collection.create sent a regular http post request with visible plain text password as JSON. I figured no big deal.  I just one way hashed the password using crypto and an env secret.  I then tested SvelteKit in ssl mode and everything with that process worked as expected, but even after enabling ssl the client still sent the request through as a regular http post request.  Is this the expected behavior? This may be a SvelteKit issue too not sure.  Figured I would start with you since I see you replying super fast to everyone (which is awesome fyi).   Thank you for any insights.

mitch (Consulting Ninja)

**Comment by ganigeorgiev** [comment]
>  I just one way hashed the password using crypto and an env secret.

No, you shouldn't hash or encrypt manually the password. The password is hashed on the server using bcrypt and stored in the `passwordHash` field as part of the related users table.

>  after enabling ssl the client still sent the request through as a regular http post request. 

I'm not sure that I understand what do you mean. The JS SDK relies on `fetch` for sending the request. Whether it will use HTTP or HTTPS depends on the url address that is used when initializing the PocketBase client (aka. `new PocketBase('YOUR_URL')`).

I'll close the issue for now as I don't think this is an issue with the JS SDK nor SvelteKit.

**Comment by consultingninja** [comment]
I am attaching some screenshots.  I definitely think something is off.  As you can see from the screenshots all the other communications from Svelte front-end to the SvelteKit backend are all using TLS , but the client is still using plain http to make the post request.
<img width="1249" alt="Screen Shot 2023-07-06 at 7 43 25 PM" src="https://github.com/pocketbase/js-sdk/assets/116985458/5ad0871f-e18f-441b-8bae-b8231d5833f0">
<img width="1249" alt="Screen Shot 2023-07-06 at 7 43 43 PM" src="https://github.com/pocketbase/js-sdk/assets/116985458/3513cb15-5fe4-41e8-bac5-0aa33d7ff158
<img width="1240" alt="Screen Shot 2023-07-06 at 7 42 17 PM" src="https://github.com/pocketbase/js-sdk/assets/116985458/62c414bd-47e7-4b15-8521-074cc3c2b323">
">
<img width="1240" alt="Screen Shot 2023-07-06 at 7 42 43 PM" src="https://github.com/pocketbase/js-sdk/assets/116985458/6d124447-c926-4fe9-aa15-e373961f6af2">

**Comment by consultingninja** [comment]
one picture didn't take
<img width="1249" alt="Screen Shot 2023-07-06 at 7 43 43 PM" src="https://github.com/pocketbase/js-sdk/assets/116985458/7fb0abeb-b8c5-4b6b-816f-2942b37db4cb">

**Comment by consultingninja** [comment]
> > I just one way hashed the password using crypto and an env secret.
> 
> No, you shouldn't hash or encrypt manually the password. The password is hashed on the server using bcrypt and stored in the `passwordHash` field as part of the related users table.
> 
> > after enabling ssl the client still sent the request through as a regular http post request.
> 
> I'm not sure that I understand what do you mean. The JS SDK relies on `fetch` for sending the request. Whether it will use HTTP or HTTPS depends on the url address that is used when initializing the PocketBase client (aka. `new PocketBase('YOUR_URL')`).
> 
> I'll close the issue for now as I don't think this is an issue with the JS SDK nor SvelteKit.

@ganigeorgiev can you check these screens I attached please.

**Comment by ganigeorgiev** [comment]
Again, I don't understand what do you mean. Do you use https when you initialize the PocketBase? Could you share your initialization code?

If you think that this is an issue with the SDK, try to reproduce it by sending plain [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) request.

**Comment by consultingninja** [comment]
Sorry Gani. I missed the 's' in my initialization line. :|
