### ISSUE TITLE
Consider returning a synchronous unsubscribe function when subscribing to a collection

### ISSUE THREAD

**Issue by asynched** [pocketbase/js-sdk#215]
When using realtime collections the js-sdk returns a promise that resolves to the unsubscribe function, using a synchronous approach would simplify the usage of realtime.

With the current API it has to be done this way:

```ts
let unsubscribePromise = pb.collection('posts')
  .subscribe('*', () => {})

unsubscribePromise.then(unsubscribe => unsubscribe())
```

Using a synchronous API would make it much simpler:

```ts
let unsubscribe = pb.collection('posts')
  .subscribe('*', () => {})

unsubscribe()
```

The previous examples are somewhat simple, but having the unsubscribe function as a promise makes it harder to implement realtime usage on some of the current front-end frameworks. In React for example:

```ts
function useRealtime<T>(
  collection: string,
  callback: (event: RecordSubscription<T>) => unknown,
) {
  useEffect(() => {
    let f: () => unknown

    pb.collection(collection)
      .subscribe('*', callback)
      .then((ubsub) => (f = unsub))

    return () => f?.()
  }, [callback])
}
```

**Comment by ganigeorgiev** [comment]
This is by design and there are no plans to change it. The code needs to run async because it needs to send request(s) to the server. Technically it is possible to implement some internal queue that will serialize the async calls but at the end of the day that's why `await` exists.
