### ISSUE TITLE
Collections users use http to send delete response 404

### ISSUE THREAD

**Issue by dong-lufei** [pocketbase/js-sdk#217]
`uni-h5.es.js:19528 DELETE https://service-xxx.com/release/api/collections/users/records/7r3i42n1oymp0ww 404`

Is it because of API rules？

I changed the API rule `id = @request.auth.id` in CRUD to `@request.auth.id! = ""`

Send get and patch successfully, but delete error 404（Use luch-request to send a delete request in the applet）,But using axios to initiate delete under nodejs succeeded

I changed the api's delete rule to null, and luch-request was able to delete the database data, but returned an uncaptured promise

There is the last problem, http to send requests to modify the data you use the patch method, I do not support this many tool framework (wechat small program, uni-app), there is put way

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand what exactly do you mean, but Yes, the 404 error could be a result from unsatisfied Delete API rule. Changing the delete rule to empty string will allow anyone to perform the request. Changing it to `null`, aka. "locking" the field will allow only admins to perform the request. For more details you can check https://pocketbase.io/docs/api-rules-and-filters/#api-rules.

> There is the last problem, http to send requests to modify the data you use the patch method, I do not support this many tool framework (wechat small program, uni-app), there is put way

PocketBase uses `PATCH` for update and there are no plans for now to change it (`PUT` have different semantic). If the platform you are using doesn't support sending `PATCH` requests you can create a request redirect on reverse proxy level (eg. with nginx) OR file an issue in the related platforms.
