### ISSUE TITLE
Is there any way to do deep deletes and updates to JSON fields?

### ISSUE THREAD

**Issue by rohaanhamid** [pocketbase/js-sdk#218]
If that is not possible, is there a way to just run raw queries on the database?

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand what do you mean by _"deep deletes and updates to JSON field"_, but it is not possible to execute raw queries with the web APIs.

Detailed guide how to extend PocketBase with custom server-side code (both Go and JS) will be available with the upcoming PocketBase v0.17.0 release.

**Comment by rohaanhamid** [comment]
@ganigeorgiev I meant updating values inside a JSON object stored in SQLite. You can do it with json functions in SQLite directly like this: https://database.guide/json_set-insert-or-update-values-in-a-json-document-in-mysql/

**Comment by ganigeorgiev** [comment]
No, this is not supported. You can perform the `json` field value modification client-side and then submit the new `json` field value.

Raw SQL `INSERT/UPDATE` statements can be executed only if you use PocketBase as framework (with the next release, there will be also an option to mind to the Go app hooks with JS via [goja](https://pkg.go.dev/github.com/dop251/goja#section-readme); see https://github.com/pocketbase/pocketbase/discussions/2825#discussioncomment-6376210)
