### ISSUE TITLE
Throwing ClientResponseError with Google Auth

### ISSUE THREAD

**Issue by SinaBYR** [pocketbase/js-sdk#220]
I'm trying to authenticate users with their Google accounts. The authentication process is working pretty well. The Google pop up window shows up, and users are able to select their desired google account, and it is also inserting users' info to the "users" table, but the problem is that I'm getting a "ClientResponseError: 0" error thrown in the console. It's not interfering with the authentication process but I have no idea what's up with it.

**index.tsx**
```tsx
import { useEffect } from "react"
import PocketBase from "pocketbase"

export default function Page() {
  const pb = new PocketBase('https://url-for-pocketbase.com')
  pb.autoCancellation(false)
  
  useEffect(() => {
    async function signUp() {
      const authData = await pb.collection('users').authWithOAuth2({ provider: 'google' })
      console.log(authData)  // valid google user account information is present
    }

    signUp()
  }, [])


  return (
    <div>
      <h1>Hello</h1>
    </div>
  )
}
```

**package.json**
```js
"dependencies": {
    "next": "13.3.0",
    "pocketbase": "^0.15.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
  },
  "devDependencies": {
    "@types/react": "18.0.35",
    "@types/react-dom": "18.0.11",
    "eslint": "8.38.0",
    "eslint-config-next": "13.3.0",
  }
```

**Comment by ganigeorgiev** [comment]
`0` status code usually means some client-side error. It could be a result from [auto cancellation](https://github.com/pocketbase/js-sdk#auto-cancellation) or some other JS issue.

To find more details about the error, you can try to wrap the `await` call with `try/catch` and inspect the [error object](https://github.com/pocketbase/js-sdk#error-handling) (and more specifically, `err.originalError`).
