### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by david-plugge** [pocketbase/js-sdk#221]
Hi, I've been working on a project called [typed-pocketbase](https://github.com/david-plugge/typed-pocketbase) to get full autocompletion and I'd love to move that functionality into this package!

I saw some comments about a larger refactoring of the js sdk so I wanted to ask if you need any kind of support.

**Comment by ganigeorgiev** [comment]
Generating types for now remains a low priority as it will be hard to maintain and document while still making API changes. _If time allows it, I may reconsider priotizing it, but no hard promises._

The planned JS SDK refactoring will be consisting mostly of:
- changes of the services definitions to allow specifying custom headers, custom `fetch` function implementations, etc. per request basis (_we'll define function overloads whenever possible to minimize the breaking changes_)
- preparations to all passing `expand` and `filter` to the realtime apis
- eventually removing entirely the custom DTO classes to avoid the need of `structuredClone` calls
- eventually replacing `EventSource` with manual parsed `fetch` stream to avoid the need of polyfill in Node and React Native
- other small DX improvements like builtin base async AuthStore and dedicated React Native one, support for File/Blob as object values, etc.

**Comment by david-plugge** [comment]
Sounds awesome!

Just want to add that this issue wasn´t about asking when or if the typescript stuff will be implemented but rather about getting in touch with you.
I´d love to implement some of the features you mentioned above myself and instead of opening some PR´s i think it makes sense to talk about what and how these things will be implemented.

**Comment by ganigeorgiev** [comment]
Thank you but for now I don't need help with the refactoring.

The code itself is not the issue, it is minimizing the breaking changes, documentation and testing that takes time to implement and in this case external PRs for new features are not helpful as they often require tedious back-forth communication.

Unless it is a blocker, there is nothing wrong of having an external package that implements the things we are missing.
