### ISSUE TITLE
Auto-cancel bug?

### ISSUE THREAD

**Issue by xuancongwen** [pocketbase/js-sdk#222]
The following code is getting auto-canceled, which simultaneously crashes my sveltekit server:

```typescript
const formData = await request.formData(); // NB: Leaving this here so that we can easily access this info for testing

// Create note
const data = Object.fromEntries(formData) as { company: string; creator: string; content: string };
const note = await pb.collection("notes").create(data);

formData.getAll("files").map((file) => {
  const formData = new FormData();
  formData.append("note", note.id);
  formData.append("file", file);

  return formData;
}).forEach(async (record) => {
  await pb.collection("files").create(record);
});
```

I'm trying to understand if this is a bug with autocancel (since I'm unfamiliar with this mechanism... is it basically attempting to enforce idempotent requests?), or if there is a way for me to restructure my code to interact with Pocketbase correctly.

This is currently working when I change the `files.create(record)` to `files.create(record, { "$autoCancel": false })`.

My SvelteKit output looks like this on autocancel:

```bash
ClientResponseError 0: The request was autocancelled. You can find more info in https://github.com/pocketbase/js-sdk#auto-cancellation.
    at new ClientResponseError (file:///Users/xuancongwen/Development/ventureflow/node_modules/pocketbase/dist/pocketbase.es.mjs:1:2306)
    at file:///Users/xuancongwen/Development/ventureflow/node_modules/pocketbase/dist/pocketbase.es.mjs:1:47315
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (/Users/xuancongwen/Development/ventureflow/src/routes/(authenticated)/companies/[id]/+page.server.ts:57:7) {
  url: '',
  status: 0,
  response: {},
  isAbort: true,
  originalError: DOMException [AbortError]: This operation was aborted
      at fetch (/Users/xuancongwen/Development/ventureflow/node_modules/undici/index.js:109:13)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async eval (/Users/xuancongwen/Development/ventureflow/src/routes/(authenticated)/companies/[id]/+page.server.ts:57:7)
}

Node.js v19.4.0
error Command failed with exit code 1.
```

**Comment by ganigeorgiev** [comment]
This is working as intended.

You can find more details about auto cancellation in https://github.com/pocketbase/js-sdk#auto-cancellation.

The above code is triggering the auto cancellation because the default cancelKey (POST + path) for the `create()` call will be the same for all requests in the `forEach` loop.

**Comment by ganigeorgiev** [comment]
On a side-note, please keep in mind that in the above code-sample `forEach()` will not wait for the promises (see the note at the end of pforeach Description](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#description)). If that's not intended a better approach could be to return an array of the promises and to await them with `Promise.all`, eg. something like:

```js
const promises = formData.getAll("files").map((file) => {
  const formData = new FormData();
  formData.append("note", note.id);
  formData.append("file", file);

  // $autoCancel: false should also work but the below could prevent eventual
  // async bugs in client-side code in case the same function is triggered multiple times
  return pb.collection("files").create(record, { "$cancelKey": "note_" +note.id });
});

try {
  await Promise.all(promises);
} catch (err) {
  if (!err.isAbort) {
    console.log("failed to create", err)
  }
}
```

**Comment by xuancongwen** [comment]
Thanks for the response, @ganigeorgiev. Okay, I'm thinking things make sense now, and thanks for the note on forEach. I didn't actually know about that behavior, but in this particular case, that behavior doesn't affect what I'm trying to do fortunately.
