### ISSUE TITLE
In a restful post request, how do I write the associated field data in the request body when adding data

### ISSUE THREAD

**Issue by dong-lufei** [pocketbase/js-sdk#224]
For example, Table A has the field id and xy(the value is "a1b2c3").

I have set field B2 in table B to associate with table A. Now, when adding data in table B, how to write the request body data

```
{
 B2:"a1b2c3"
}
```
This will give you an error：
```
 {
      code: 'validation_missing_rel_records',
      message: 'Failed to fetch all relation records with the provided ids.'
 }
```

**Comment by ganigeorgiev** [comment]
The description is too abstract and I'm not sure that I understand the question.

What is `a1b2c3` in the above?

Please note that relations can be linked using the record **id**(s).

There will be more documentation about this with the next release, but heare is an example:

```js
const post = await pb.colleciton('posts').create({
    'title': 'Lorem ipsum...',
    'tags':  ['TAG_ID1', 'TAG_ID2'],
});
```
In the above the `tags` field is a multiple `relation` field pointing to "tags" collection.

**Comment by ganigeorgiev** [comment]
I'm closing this as I'm not sure if there is anything that can be done here.

Feel free to let me know if the above doesn't help by providing more info about your use case and I'll to help.
