### ISSUE TITLE
How to set the default value of the field of the table

### ISSUE THREAD

**Issue by dong-lufei** [pocketbase/js-sdk#225]
How to set the default value of the field of the table, for example, I set the field id and A2 in table A, then I can set the type of A2 field, then how to set the default value?

**Comment by ganigeorgiev** [comment]
Default values can be set only client-side OR when [using as Go framework](https://pocketbase.io/docs/use-as-framework/) when attaching to the specific [app event hook](https://pocketbase.io/docs/event-hooks/) (_with the next release there will be option to bind to the app hooks with JS too_).

_If you have general questions non-related to the SDK please use the [Discussions in the main repo](https://github.com/pocketbase/pocketbase/discussions)._
