### ISSUE TITLE
Does PocketBase allows to create multiple linked resources in a single operation?

### ISSUE THREAD

**Issue by alveshelio** [pocketbase/js-sdk#228]
Hi,

I have a use case and I'd like to know if PocketBase can handle it.
I want to create a table `Invoices`, this table has a one to many relationship with table `InvoiceSections` and in turn, this table has a one to many relationship with table `InvoiceSectionItems`.

I'd like to know if I can create in a single operation an **Invoice** with multiple **Sections**, each section having multiple **Items** in it.

Thanks

**Comment by ganigeorgiev** [comment]
No, at the moment bulk/transactional operations are not supported via the web APIs (_this eventually will be handled as part of #48_).

If you need transaction support, you'll have to register your own route and handle the operations on your own (see [Use as framework](https://pocketbase.io/docs/use-as-framework/)).

**Comment by cayoub88** [comment]
@ganigeorgiev - will the new experimental JS Hooks support something like that (bulk creating/updating etc)? I know I can create a new endpoint, but unsure the approach. I suppose something like [this](https://pocketbase.io/docs/js-records/#create-new-record), wrapped in a for loop of sorts?

**Comment by ganigeorgiev** [comment]
@cayoub88 Yes, it could be done. For a transaction example you can also check https://pocketbase.io/docs/js-records/#transaction (if you want to create the record with validations you have to use the [`RecordUpsertForm`](https://pocketbase.io/jsvm/classes/RecordUpsertForm.html#setDao) as shown in ["Create new record with data validations"](https://pocketbase.io/docs/js-records/#create-new-record-with-data-validations) with the minor difference that in a transaction you have to explicitly set the dao of the form to use the transactional one, aka. [`form.setDao(txDao)`](); everything else is the same).
