### ISSUE TITLE
Can't upload files bigger then 59900 bytes

### ISSUE THREAD

**Issue by PaulDotterer** [pocketbase/js-sdk#232]
Im really sorry to bother you all again ... 
I have a really strange issue and I cant figure out where the error happens or what the problem is.

I have a SvelteKit App where i want to upload one or more files and save them in PocketBase.
The below code is a SvelteKit form action, everything works as expected for files smaller then 59900 bytes, when a file is bigger then the byte amount the request hangs and i eventually get a timeout with the following error:
```
{
  "errorDetails": "multipart: NextPart: read tcp 127.0.0.1:8090->127.0.0.1:50395: i/o timeout",
  "errorMessage": "Failed to load the submitted data due to invalid formatting."
}
```

```
uploadFiles: async ({ request, locals }) => {
		let data = await request.formData();
		let allFiles = data.getAll('files');
		allFiles.forEach(async (file) => {
			const formData = new FormData();
			formData.append('file', file);
			try {
				const res = await locals.pb.collection('documents').create(formData);
			} catch (err) {
				console.log('Error: ', err);
			}
		});
		return {
			success: true
		};
	}
```
The max byte amount inside PocketBase for the collection field is set to 3000000 bytes so there should not be any issues. Uploading from the Admin dashboard is working just fine. Im also not using any S3 storage, everything is on my machine.
Saving the file to disk works when i just get the file and save it via writeFile.
Also tried it on https://pockethost.io, same issue.

I have also tried a pure client side approach, as stated in the docs.The upload succeeds but i need to make it work from nodejs.
Is this an issue with my code, PocketBase or do i need to dig deeper into node to get more details?

**Comment by ganigeorgiev** [comment]
Since it is working when uploading from the Admin UI, then I don't think this is PocketBase related.

If you have a reverse proxy, double check its configuration.

If you use the node adapter with SvelteKit, check https://kit.svelte.dev/docs/adapter-node#environment-variables-bodysizelimit.

If none of the above helps, feel free to provide more details about your setup and I'll try to investigate it further.

**Comment by PaulDotterer** [comment]
Thank you very much for the prompt reply, the error seems to originate in nodejs.
I had v20.4.0 installed, after uninstalling and installing version 18.12.0 it works as expected. There seems to be an issue already regarding this https://github.com/nodejs/node/issues/49113.
So definitely not a PocketBase issue, but maybe helping someone with the same problem when building with PocketBase + SvelteKit.

**Comment by ganigeorgiev** [comment]
@PaulDotterer It is working fine for me and I'm not able to reproduce the issue locally with Node v20.4.0.

Here is a minimal example:

```js
const formData = new FormData()

// emulate ~100kb text file
formData.append("file", new Blob(["a".repeat(100000)]), "test.txt")

await fetch("http://127.0.0.1:8090/api/collections/example/records", {
    method: "POST",
    body: formData,
})

// or with the SDK
// import PocketBase from 'pocketbase'
// const pb = new PocketBase("http://127.0.0.1:8090")
// await pb.collection("example").create(formData)
```

**Comment by PaulDotterer** [comment]
@ganigeorgiev thank you for taking your time and testing this. I will try it tomorrow and see if I can give any more insights. Have a nice evening!
