### ISSUE TITLE
authStore issues already expired token

### ISSUE THREAD

**Issue by bogdanrbucur** [pocketbase/js-sdk#234]
For the past 2 days, PB gives me expired tokens when first logging in. For example, today, 23 Aug, it issues me tokens expired on 21 Aug. After logging in again, it issues one expired on 22 Aug. On the 3rd try, it issues one expiring in September, which allows me to login.

Because I'm using Next.js, I'm using the `exportToCookie()` method, but that seems irrelevant, as even when decoding the JWT gives an expired date.

Today, 23.08.2023, these are the JWT I get:
1st try: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2xsZWN0aW9uSWQiOiJfcGJfdXNlcnNfYXV0aF8iLCJleHAiOjE2OTI2MTY1ODUsImlkIjoiZzl5enh5ZHUxcWtvNWR2IiwidHlwZSI6ImF1dGhSZWNvcmQifQ.eQNUEp5cLeWMf-o3
z-mioNVz6boICp31-1f55g6jKj0`

2nd try: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2xsZWN0aW9uSWQiOiJfcGJfdXNlcnNfYXV0aF8iLCJleHAiOjE2OTI3MTQyMzIsImlkIjoiZzl5enh5ZHUxcWtvNWR2IiwidHlwZSI6ImF1dGhSZWNvcmQifQ.NZSG9P-verj83ogR
-vdsv7vH1-QWPzgGBUNtjeYPAQc`

3rd try: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2xsZWN0aW9uSWQiOiJfcGJfdXNlcnNfYXV0aF8iLCJleHAiOjE2OTM5ODE4MjEsImlkIjoiZzl5enh5ZHUxcWtvNWR2IiwidHlwZSI6ImF1dGhSZWNvcmQifQ.reGjdgQ9_850ybww
MoN8annQeXKWF4mz_Kd9QF0kg0U`
After the 3rd try it obviously works, as the token is valid.

I've been using the same auth and logout methods for weeks, no change in the code.
Here's my auth method:
```ts
const loginPb = async ({ email, password }: { email: string; password: string }) => {
	let response: PocketbaseLogin = {};

	try {
		const authData = await pb.collection("users").authWithPassword(email, password);

		if (authData) {
			const record = authData.record;
			console.log(`User ${record.name} authenticated`);

			// set the client cookie
			cookies().set("pb_auth", pb.authStore.exportToCookie());

			response.token = authData.token;
			response.name = record.name;
			response.email = record.email;
			response.isAdmin = record.isAdmin;
		}
	} catch (err: any) {
		console.log(`${email} ${err.message}`);
		response.error = err.response;
	}
	return response;
};
```

Logout:
```ts
export const logoutPb = async () => {
	pb.authStore.clear();
	cookies().delete("pb_auth");
};
```

**Comment by ganigeorgiev** [comment]
To rule out local JS setup issue, could you try to authenticate with a Postman, Insomnia, curl, etc. and check again the token?

**Comment by bogdanrbucur** [comment]
> To rule out local JS setup issue, could you try to authenticate with a Postman, Insomnia, curl, etc. and check again the token?
> 
> The auth request must be `POST /api/collections/users/auth-with-password` and json body:
> 
> ```js
> {
>     "identity": email,
>     "password": pass
> }
> ```

Just tried using Thunder client and it responded with valid token. Seems like an issue with my code then. I already provided the auth and logout methods. There's one more method I use to validate the cookie in the Next.js middleware, for every route:
``` ts
export const validateCookie = async (cookie: RequestCookie) => {
	pb.authStore.loadFromCookie(cookie.value);
	console.log("Checked client cookie");

	if (pb.authStore.isValid) {
		console.log("VALID cookie");
		return pb.authStore.model;
	} else {
		console.log("INVALID cookie");
		return false;
	}
};
```

**Comment by ganigeorgiev** [comment]
You can't trust the `validateCookie` function.

`pb.authStore.loadFromCookie` just parses the cookie string and populates the `pb.authStore` instance. **Aka. it doesn't perform any PocketBase requests to validate the token.** This is why in the [SSR examples](https://github.com/pocketbase/js-sdk#ssr-integration) `authRefresh()` is used. It validates the store token against the PocketBase server and on success returns the latest user data and renewed token.

In any case, I don't think this is PocketBase or JS SDK related.

If you think otherwise, please provide a more complete code sample (or ideally a **minimal** reproducible repo) and I'll  try to investigate it.

**Comment by bogdanrbucur** [comment]
Just want to drop in and let you know that after reading the v0.17.0 release notes, I tried adding `cache: "no-store"` to the auth method and that did the trick.

```js
let authData = await pb.collection("users").authWithPassword(email, password, { cache: "no-store" });
```

So the problem was Next.js cache, which was issuing me expired tokens, but using the above, I always get new tokens on every login.

I also added `cache: "no-store"` to the `authRefresh` method and this seems to work fine for me, along with using Next.js middleware:

```js
export const validateCookie = async (cookie: RequestCookie) => {
	// validate the client cookie with Pocketbase
	pb.authStore.loadFromCookie(cookie.value);
	console.log("Checked client cookie");

	if (pb.authStore.isValid) {
		console.log("VALID cookie");
		// refresh the auth store and return the latest update cookie to the middleware
		// middleware will update it on the client
		await pb.collection("users").authRefresh({ cache: "no-store" });
		return pb.authStore.exportToCookie();
	} else {
		console.log("INVALID cookie");
		return false;
	}
};
```

Thanks for the support and for the active maintenance of the project.
