### ISSUE TITLE
Record Type issues since latest version

### ISSUE THREAD

**Issue by Fischer96** [pocketbase/js-sdk#238]
Hey,

i used to create my types in this pattern:

```typescript
import { Record } from 'pocketbase';

export type Note = {
  title: string;
  content?: string;
  images: File[];
  isArchived: boolean;
} & Record;
```

But one of the last versions changed some stuff and i wonder how to get the exact same functionality now. You introduced this `RecordModel` in version `0.17.0` which seemed like the new way to do it but that doesn't add the common fields to my type like `id`, `created`, `updated` and so on. Do i have to add those manually now?

**Comment by ganigeorgiev** [comment]
You can use the `RecordModel` interface, it contains the default fields.

To import TS types you can also use the `import type { RecordModel } from "pocketbase"` notation.

To learn more about the v0.17+ changes, you can check the [CHANGELOG](https://github.com/pocketbase/js-sdk/blob/master/CHANGELOG.md) OR the discussion https://github.com/pocketbase/pocketbase/discussions/3134.
