### ISSUE TITLE
Feature request: Support transactions

### ISSUE THREAD

**Issue by kisinga** [pocketbase/js-sdk#242]
The current implementation doesnt expose transaction support. I know this would take a lot of integration with the server, but would be a nice quality fo life feature to support

**Comment by ganigeorgiev** [comment]
This was discussed several times in the main repo. Bulk/transactions support for the web APIs is in my todo and eventually will be implemented as part of https://github.com/pocketbase/pocketbase/issues/48, but for now is on hold and left aside.

If you want to handle transactions on app level, you could check:
- (Go) https://pocketbase.io/docs/go-records/#transaction
- (JS `pb_hooks`) https://pocketbase.io/docs/js-records/#transaction
