### ISSUE TITLE
Delay in Real-time Updates with PocketBase SDK in Angular Applications After Idle Time

### ISSUE THREAD

**Issue by nicetomytyuk** [pocketbase/js-sdk#246]
### Issue Description
When using the PocketBase SDK in an Angular application, I've observed a delay in real-time updates after the page has been idle for a few minutes. Specifically, changes made to a table that a component is subscribed to are not immediately reflected in the view/template.

### Steps to Reproduce

- Create a new Angular project.
- In the ngOnInit method of a component, subscribe to changes in a table.
- Inside the subscription, fetch and update some data to bind it to the template.
- Allow the page to remain idle for several minutes.
- Return to the page and make some changes to the table you're subscribed to.

### Expected Behavior
The changes to the table should be immediately reflected in the view/template.

### Actual Behavior
Although the object returned by the promise confirms the update, the view takes several seconds to detect and reflect the change.

### Root Cause Analysis
Upon investigation, the issue appears to be related to Angular's ngZone. The delay is resolved when fetching operations are wrapped in ngZone.run().

### Code Sample

```
ngOnInit() {
  this.backend.getPocketBaseInstance()!.collection(Collections.Queue).subscribe('*', (update: RecordSubscription<QueueResponse>) => {
    if (update.record.group != this.group!.id) return;
    this.ngZone.run(() => {
      this.getData();
    });
  });
}

getData() {
  this.backend.getWaitingQueueEntries(this.group!.id).then(data => {
    if (data) this.waitingEntries = data;
  });
  this.backend.getServingQueueEntries(this.group!.id).then(data => {
    if (data) this.servingEntries = data;
  });
}
```
### Suggested Fix
One possible solution could be to update the SDK functions to return observables instead of promises, to ensure that changes are immediately reflected in the view.

**Comment by ganigeorgiev** [comment]
I don't understand what do you mean by _"return observables instead of promises"_, but there are no plans to change the SDK's return results.

I haven't used Angular in ages and I'm not what exactly is the problem with `Promise` and what else to recommend.

**Comment by nicetomytyuk** [comment]
The issue was open, to notificate about the issue and its possible resolution, the "suggested fix" was linked as you said to the return results, but I can understand that there are no plans to change it in the SDK, btw it can be solved on the Angular project side by forcing the `ngZone` as I've mentioned in the question.

> I don't understand what do you mean by "return observables instead of promises", but there are no plans to change the SDK's return results.

The issue is that Angular doesn't handle correctly the change detection of an external `Promises` but it can hook automatically only `Observables`

> I haven't used Angular in ages and I'm not sure what exactly is the problem with `Promise` and what else to recommend.

I've even created a question on [stackoverflow ](https://stackoverflow.com/questions/77202643/angular-slow-template-refresh-with-async-pipe-when-tab-is-in-background/77214358#77214358) with one of possible solutions to that.

**Comment by ganigeorgiev** [comment]
I think there is some misunderstanding.

The `subscribe()` returns only a single `Promise` - that is the unsubscribe function for the specific subscription.

The realtime changes are reflected in the subscription callback. This is not a `Promise`.
Under the hood we use the native [`EventSource` APIs](https://developer.mozilla.org/en-US/docs/Web/API/EventSource).

In any case, the SDK doesn't have any dependencies and relies entirely on native APIs like `fetch` and `EventSource` so technically it should work any JS framework.
If Angular has some quirks with its reactivity then this should be solved on the Angular side.

**Comment by nicetomytyuk** [comment]
Oh, actually I've been trying to combine both, realtime and `getFullList`. When in realtime the data is notified about some changes, I was trying to fetch all the data again from the table with `.getFullList`, as I said with that there are no problems as the data are fetch and received correctly from both realtime and the promise.

Btw as you said Angular has some quirks with its reactivity.
