### ISSUE TITLE
Record type argument for client

### ISSUE THREAD

**Issue by scriptcoded** [pocketbase/js-sdk#251]
Hey there!

While working on a side project of mine using PocketBase I found it somewhat cumbersome to manually provide types for each record query. I could wrap everything in a data layer but it made me wonder if there was a way to provide one singe type with all types contained to the client, which there wasn't. Would you be interested in a PR providing this functionality? In my mind it shouldn't be too hard (though we all know that's never true). I'm thinking something in the lines of

```ts
import PocketBase from 'pocketbase'

import { PostsRecord, UsersRecord } from './pocketbase-types'

type PocketbaseTypes = {
  records: {
    users: UsersRecord
    posts: PostsRecord
  }
}

const pb = new PocketBase<PocketbaseTypes>('...')
```

It would also open up for tools like [typed-pocketbase](https://github.com/david-plugge/typed-pocketbase) to simply export a single type and have everything typed automagically.

Cheers! :smile:

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand the suggested proposal.

Contributions for new features are welcomed but there are no promises that it will get merged or reviewed in a timely manner (_see also https://github.com/pocketbase/pocketbase/discussions/3271_).

There are plans to provide auto generated type definitions with the JS and Dart SDKs but for now other tasks are with higher priority and it is left aside (_eventually the JS SDK part will be handled as part of https://github.com/pocketbase/js-sdk/issues/152_).

**Comment by scriptcoded** [comment]
That sounds like a good and simple solution. Want me to open a PR for it or will you manage it yourself?

**Comment by ganigeorgiev** [comment]
The above should be supported with [JS SDK v0.18.3 release](https://github.com/pocketbase/js-sdk/releases/tag/v0.18.3).

_The [README](https://github.com/pocketbase/js-sdk#specify-typescript-definitions) was also updated with an example._
