### ISSUE TITLE
htmx

### ISSUE THREAD

**Issue by gedw99** [pocketbase/js-sdk#252]
HTMX is a very simple way to do SSR. Its would be awesome if this is possible with pocketbase.

https://htmx.org/examples/

to give you an idea of how it works here are some golang example frameworks

https://github.com/topics/htmx?l=go&o=desc&s=updated

Here is a nice simple golang htmx example with zero dependencies and a nice GUI

https://github.com/acorello/Contacts.app

just " go run . " and you its working..

**Comment by ganigeorgiev** [comment]
There are no plans for now for builtin htmx integration.

When PocketBase is [used as framework](https://pocketbase.io/docs/use-as-framework/), users have full access to the underlying router (echo) and they can use whatever rendering and template engine they prefer.

The JS SDK repo is intended only as JS client for the [web APIs](https://pocketbase.io/docs/api-records/).

**Comment by gedw99** [comment]
Ok thanks for the answer .

If others find this , 
there are a few GitHub repos already with this integration so that’s partly why I suggested it
