### ISSUE TITLE
This is not a PocketBase issue

### ISSUE THREAD

**Issue by serkan-bayram** [pocketbase/js-sdk#253]
I'm using PocketBase with NextJS App Directory and it creates caches for fetch requests as default, so I was trying to use 
```js
// or fetch only the first record that matches the specified filter
const record = await pb.collection('users').getFirstListItem('someField="test"', {
    expand: 'relField1,relField2.subRelField',
});
```
this get function and it was giving me outdated data, since this List/Search function problably using fetch under the hood it also creates cache and it's not working properly, it's not PocketBase's fault but it would be awesome if you can specify this issue somewhere in the documentation. Thanks!

**Comment by ganigeorgiev** [comment]
You can specify custom fetch options along-side the `expand` prop (_there is brief example in the [Custom request options](https://github.com/pocketbase/js-sdk#custom-request-options) section_).
