### ISSUE TITLE
Js.sdk

### ISSUE THREAD

**Issue by BrandTasticGlobal** [pocketbase/js-sdk#26]

**Comment by BrandTasticGlobal** [comment]
Sdk

**Comment by ganigeorgiev** [comment]
@BrandTasticGlobal Could you elaborate a little more on what is this issue about?

**Comment by ganigeorgiev** [comment]
I'll close the issue, but if you are still experiencing difficulties trying to load the library, feel free to let me know by adding a comment or file a new one.
