### ISSUE TITLE
Back-relation expand not working with "getOne"

### ISSUE THREAD

**Issue by korosu** [pocketbase/js-sdk#260]
I have tested same code with API or "getList" method and it works perfectly
However, when using the 'getOne' method, the code for expand back-relation seems to be ignored

```import pb from "@/app/utils/pb";
export default async function ProductPage({ params }) {
  let product;
  async function getProduct(product_id) {
    const record = await pb
      .collection("new_products")
      .getOne(product_id, { expand: "test(product_id)" });
    console.log(record);
    return record;
  }

  try {
    product = await getProduct(params.product_id);
  } catch {
    console.log("error");
  }
  return <div>{product.name}</div>;
}
```

**Comment by ganigeorgiev** [comment]
I'm using heavily expand with both direct and indirect/back relations, so I don't think it is a PocketBase or JS SDK issue.

Double check that:

- there is no cache involved (_if you use Next.js note that they have custom global `fetch` implementation that has cache enabled by default_)
- make sure that your API request satisfy the View API rule of the related collection

To rule out JS SDK issue, you can also try sending the request directly with the equivalent web API.

If the above doesn't help, feel free to paste your collections configuration as json (_Admin UI > Settings > Export collections_) and I'll have a more detailed look.

**Comment by korosu** [comment]
> I'm using heavily expand with both direct and indirect/back relations, so I don't think it is a PocketBase or JS SDK issue.
> 
> Double check that:
> 
> * there is no cache involved (_if you use Next.js note that they have custom global `fetch` implementation that has cache enabled by default_)
> * make sure that your API request satisfy the View API rule of the related collection
> 
> To rule out JS SDK issue, you can also try sending the request directly with the equivalent web API.
> 
> If the above doesn't help, feel free to paste your collections configuration as json (_Admin UI > Settings > Export collections_) and I'll have a more detailed look.



> I'm using heavily expand with both direct and indirect/back relations, so I don't think it is a PocketBase or JS SDK issue.
> 
> Double check that:
> 
> * there is no cache involved (_if you use Next.js note that they have custom global `fetch` implementation that has cache enabled by default_)
> * make sure that your API request satisfy the View API rule of the related collection
> 
> To rule out JS SDK issue, you can also try sending the request directly with the equivalent web API.
> 
> If the above doesn't help, feel free to paste your collections configuration as json (_Admin UI > Settings > Export collections_) and I'll have a more detailed look.

Thank you a lot for your hint and sorry for incorrect issue, it was Next.js cache problem,I had encountered once before in an another situation
