### ISSUE TITLE
Better reporting of code errors, JSDoc throws annotation

### ISSUE THREAD

**Issue by pepa-linha** [pocketbase/js-sdk#262]
Hi, according to the documentation

https://github.com/pocketbase/js-sdk?tab=readme-ov-file#error-handling

in fact, [every method on the collection](https://github.com/pocketbase/js-sdk/blob/master/src/services/utils/CrudService.ts) can throw a `ClientResponseError` error, which is fine, but I would expect such information in the code to catch such errors.

I would therefore expect an annotation for such methods

`@throws {ClientResponseError}`

What do you think?

(For example, such an error can occur if I do not have a server with Pocketbase running. In short, all calls must be wrapped in a try-catch.)

**Comment by ganigeorgiev** [comment]
Note that every `Promise` can throw, but I'll document the exception with the next minor release sometime later today.
