### ISSUE TITLE
[Bug or Doc suggestion] Auth with password "field" option unexpected behavior

### ISSUE THREAD

**Issue by MarArMar** [pocketbase/js-sdk#266]
Using "pocketbase": "0.18.0",

This is in the admin documentation of "Auth with password"
```
fields | String | Comma separated string of the fields to return in the JSON response         (by default returns all fields). For example:          ?fields=id,expand.relField.id,expand.relField.created
```

I tried, and finally made it work with this : 
```
{ fields: 'token,record.id,record.email' }
```

So either change the documentation to reflect the  "record.id,record.email" instead of "id,email", or change the way the fields work in the JS SDK

**Comment by ganigeorgiev** [comment]
It is intended behavior. I'll consider updating the documentation with the next release.
