### ISSUE TITLE
How do I retrieve field values from pocketbase records?

### ISSUE THREAD

**Issue by ItsTerm1n4l** [pocketbase/js-sdk#267]
Im trying to build a website using pocketbase for the backend and svelte for the frontend JS, I have created records like so;
![20231212_17h41m13s_grim](https://github.com/sveltejs/kit/assets/118511626/e5244250-6c21-411e-85e8-f6d5bfc884b5)
and I need to get the value of the name field of all the records in the parts collection and display them in a dropdown box in my site, how do I do this?
Thank You.

**Comment by ganigeorgiev** [comment]
You can call `getList()` (for paginated records list) or `getFullList()` (for all collections records):

```js
const records = await pb.collection("parts").getFullList();
```

Note that by default new collections have "Admin only" API rules. You can manage the permissions to your collection from the _collection settings (cogwheel) > API rules_.

For more details and examples you can explore the "API Preview" section of the collection or explore the generic web API docs at https://pocketbase.io/docs/api-records/.

If you need further help, for general usage questions please consider opening a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) instead.
