### ISSUE TITLE
.listAuthMethods() results in svelte warning

### ISSUE THREAD

**Issue by Phillor** [pocketbase/js-sdk#268]
Hi there,

I'm just here to mention that calling listAuthMethods() on the user collection works as expected but throws a warning in the console when using with svelte.
![image](https://github.com/pocketbase/js-sdk/assets/6738174/eeefe3c1-dbd7-4e54-9033-bf59d11ce096)

I hope it helps to optimize the SDK further. Thank you for your work!

**Comment by ganigeorgiev** [comment]
This is not an SDK issue. The SDK uses the native `fetch` or whatever global `fetch` is available.

SvelteKit has their own extended/custom `fetch` that you can pass to the SDK call if you want to with the `fetch` `SendOptions` - https://github.com/pocketbase/js-sdk?tab=readme-ov-file#custom-request-options.
