### ISSUE TITLE
OPTIONS in each XHR request increases latency enormly (15 times)

### ISSUE THREAD

**Issue by step135** [pocketbase/js-sdk#269]
Your SDK has a bug as in each request it calls primarily OPTIONS request. It should be avoided. In one call I had OPTIONS request 700 ms (sometimes 1500 ms) and GET request 50 ms, totally 750 ms. When I called REST API endpoint by `fetch` function I received the result in 50 ms, not 700 ms !!!

**Comment by ganigeorgiev** [comment]
There is no bug, there something else going on but without reproducible example I don't know how to help you.

We don't send `OPTIONS` requests, the client/browser is doing that automatically. The SDK uses `fetch` under the hood so there shouldn't be any difference from manually invoking the same method or through the SDK.
