### ISSUE TITLE
Misleading TypeScript errors when using the included SvelteKit SSR example

### ISSUE THREAD

**Issue by ollema** [pocketbase/js-sdk#27]
<img width="922" alt="Screenshot 2022-08-26 at 13 04 57" src="https://user-images.githubusercontent.com/31876997/186890645-f2bab093-47e8-4cb5-b10b-24b3b973144c.png">

```
Property 'loadFromCookie' does not exist on type 'AuthStore | BaseAuthStore'.
  Property 'loadFromCookie' does not exist on type 'AuthStore'.
```

This is due to the fact that the `authStore` property of the client has the type `AuthStore | BaseAuthStore` but `AuthStore` was never updated to include the new methods.

**Comment by ganigeorgiev** [comment]
Just to let you know that the previously discussed changes are available in the [v0.6.1 release](https://github.com/pocketbase/js-sdk/releases/tag/v0.6.1).
