### ISSUE TITLE
getOne with empty string returns result

### ISSUE THREAD

**Issue by Laecherlich** [pocketbase/js-sdk#271]
Hey, I noticed that calling `collection('...').getOne('')` returns all data of the table in pages the same as `getFullList`. 
Its not a big problem for me, I will just add a check before but I wanted to let you know :).

**Comment by ganigeorgiev** [comment]
It will fallback to `getList()` but I agree that is not expected behavior.

Should be fixed in [v0.20.2](https://github.com/pocketbase/js-sdk/releases/tag/v0.20.2).
