### ISSUE TITLE
How to use generics for extending PocketBase collection types?

### ISSUE THREAD

**Issue by ChrisMGeo** [pocketbase/js-sdk#278]
Hello, I'm making an app using pocketbase and typescript, and was trying to type out the collections as per docs, however using a generic instead. This seems to add the right collections but only has the type safety if I use `collection<"name">("name")` and not `collection("name")`. If I comment the default one with any string, it works but obviously gets rid of compatibility with any generic string.
```typescript
export interface TypedPocketBase<T extends { [x: string]: RecordModel }> extends PocketBase {
  collection(idOrName: string): RecordService
  collection<K extends keyof T>(idOrName: K): RecordService<T[K]>;
}
```

**Comment by ganigeorgiev** [comment]
I don't think this is a SDK issue, or at least I don't understand the described problem.

I've copied locally the example from the [Specify TypeScript definitions](https://github.com/pocketbase/js-sdk?tab=readme-ov-file#specify-typescript-definitions) section and it works fine for me.

If you are still not able to identify the culprit, please provide a more complete code sample, the version of TS and its configuration that you use.

**Comment by ChrisMGeo** [comment]
> I don't think this is a SDK issue, or at least I don't understand the described problem.
> 
> I've copied locally the example from the [Specify TypeScript definitions](https://github.com/pocketbase/js-sdk?tab=readme-ov-file#specify-typescript-definitions) section and it works fine for me.
> 
> If you are still not able to identify the culprit, please provide a more complete code sample, the version of TS and its configuration that you use.

Here is my complete code sample (I'm using Next.js 14):
```typescript
// types/pocketbase.ts
import PocketBase, { type RecordService, type RecordModel } from "pocketbase";

export interface TypedPocketBase<T extends { [x: string]: RecordModel }> extends PocketBase {
  collection(idOrName: string): RecordService
  collection<K extends keyof T>(idOrName: K): RecordService<T[K]>;
}

export type Room = {
  title: string;
  description: string;
} & RecordModel;
```
```typescript
// consts/pocketbase.ts
import type { Room, TypedPocketBase } from '@/types/pocketbase';
import PocketBase from 'pocketbase';

const db = new PocketBase("http://127.0.0.1:8090") as TypedPocketBase<{
  rooms: Room;
}>;
if (process.env.NODE_ENV === "development") db.autoCancellation(false);
export { db };
```
Here is what goes wrong when I use it:
Without using `<"rooms">`:
![image](https://github.com/pocketbase/js-sdk/assets/44679968/207867c9-dd72-4d43-bef0-04bdda80172e)
With using `<"rooms">`:
![image](https://github.com/pocketbase/js-sdk/assets/44679968/6ff129a4-71d9-44b2-8e7f-865c8f698434)

TypeScript version in package.json:
```
 "typescript": "^5"
```
TSConfig (Next.js):
```json
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
```

**Comment by ChrisMGeo** [comment]
I'm assuming this has something to do with how the definition in the type uses `<K extends keyof T>`?

**Comment by ganigeorgiev** [comment]
I think I understand what you are trying to do but I'm not sure what is the best way to approach it as I'm not so versatile with TypeScript.

The problem with just using `K extends keyof T` is that in your case that will be the key of the map (aka. "room"), but you want both key and value. Following this one possible workaround could be to try something like:

```typescript
collection<K extends keyof T, M extends T[K]>(idOrName: K): RecordService<M>;
```

Testing locally the above complile but again I'm not sure if this is the best way to do it and you may have a better chance resolving your issue asking in the TypeScript support channel for help.

**Comment by ChrisMGeo** [comment]
Thanks! Sorry I assumed this was an sdk issue.

**Comment by ganigeorgiev** [comment]
Also I forgot to mention that the above work for me only if I remove the plain fallback "_collection(idOrName: string): RecordService_" (I'm not sure exactly why?):

```ts
export interface TypedPocketBase<T extends { [x: string]: RecordModel }> extends PocketBase {
  collection<K extends keyof T, M extends T[K]>(idOrName: K): RecordService<M>;
}
```

**Comment by ChrisMGeo** [comment]
Oooh didn't know that keeping it last had that effect. Thanks again for the help!
