### ISSUE TITLE
didnot work in 

### ISSUE THREAD

**Issue by akram0bellir** [pocketbase/js-sdk#280]
react native can not export pb et can not ues         const records = await pb.collection('users').getList(); 
dont read in         console.log("records",records);

**Comment by ganigeorgiev** [comment]
I don't know how to help you as the description is unreadable.

Also note that `getList` will return a pagination result and the records will be available under the `items` key.

If that doesn't help, please at least elaborate and provide some code sample showing how do you initialize the SDK (a **minimal** repo with snack.expo.dev could also help).
