### ISSUE TITLE
Add additional Query Parameters to OAuth2 Login Flow

### ISSUE THREAD

**Issue by ytsdv** [pocketbase/js-sdk#283]
Currently there seems to be no way to add custom query parameters to the OAuth url of a provider.
I stumbled on this issue while using discord as oauth provider and trying to skip the authentication step if the user already authenticated once.
Discord lets you skip the authentication screen if you provide the query parameter `prompt=none`  [discord docs](https://discord.com/developers/docs/topics/oauth2#authorization-code-grant-authorization-url-example).
As i am seeing it this option could be added to the config object you pass to `authWithOAuth2`

**Comment by ganigeorgiev** [comment]
You can specify your own `urlCallback` and do anything with its url argument.

```js
await pb.collection("users").authWithOAuth2({
    provider: "discord",
    urlCallback: (url) => {
        // modify the url, for example by converting it to URL: https://developer.mozilla.org/en-US/docs/Web/API/URL 
        // ...
        window.open(url, "popup_window", "width=500,height=500,resizable,menubar=no");
    },
})
```

Other OAuth2 config options could be added eventually as part of https://github.com/pocketbase/js-sdk/issues/265 but for now remains a low priority.

**Comment by jlopezvaldez** [comment]
Over a year later, but specifying my own `urlCallback` helped me in retrieving the `refreshToken` from the OAuth flow.

`  urlCallback: (url) => {
          const urlObj = new URL(url);
          urlObj.searchParams.set('access_type', 'offline');
          urlObj.searchParams.set('prompt', 'consent');

          window.open(
            urlObj.toString(),
            'oauth_popup',
            'width=500,height=600,resizable,menubar=no'
          );
        },`
