### ISSUE TITLE
Can't get authWithOAuth2Code storing pocketbase_auth in storage?

### ISSUE THREAD

**Issue by Stolson** [pocketbase/js-sdk#287]
I have a pretty straightforward callback hook working like so - the user gets inserted into the users collection:

```
export const GET = async ({ locals, url, cookies }) => {
	try {
		await locals.pb
			?.collection('users')
			.authWithOAuth2Code(provider.name, code, expectedVerifier, redirectURL);
		await locals.pb.collection('users').authRefresh();
		console.log(locals.pb.authStore); // I see my user in the authStore here
	} catch (err) {
		console.log('Error logging in with OAuth2 user', err);
	}

	throw redirect(303, '/');
};
```

And I have my hooks.server.ts pulled from the [docs](https://github.com/pocketbase/js-sdk/tree/master?tab=readme-ov-file#ssr-integration):

```
import { PUBLIC_PB_URL } from '$env/static/public';
import Pocketbase from 'pocketbase';

export async function handle({ event, resolve }) {
	event.locals.pb = new Pocketbase(PUBLIC_PB_URL);

	console.log('Cookies:' + event.request.headers.get('cookie'));

	// load the store data from the request cookie string
	event.locals.pb.authStore.loadFromCookie(event.request.headers.get('cookie') || '');

	try {
		// get an up-to-date auth store state by verifying and refreshing the loaded auth model (if any)
		event.locals.pb.authStore.isValid && (await event.locals.pb.collection('users').authRefresh());
	} catch (_) {
		// clear the auth store on failed refresh
		event.locals.pb.authStore.clear();
	}

	const response = await resolve(event);

	// send back the default 'pb_auth' cookie to the client with the latest store state
	response.headers.append('set-cookie', event.locals.pb.authStore.exportToCookie());

	return response;
}
```
Now after my callback, I don't see anything from the authModel in the LocalStorage? My `pocketbase_auth` value is always `"{"token":"","model":null}"`. Probably just missing something obvious.

### Things I've tried:

I've put this in the callback hook to try to save the token:
```
const { token } = await locals.pb
    .collection('users')
    .authWithOAuth2Code(provider.name, code, expectedVerifier, redirectURL);
await locals.pb.authStore.save(token);
```

**Comment by ganigeorgiev** [comment]
You can try to export the cookie in your hooks.server.ts with `sameSite: 'Lax'` (by default is 'Strict'):

```js
response.headers.append('set-cookie', event.locals.pb.authStore.exportToCookie({ sameSite: 'Lax' }));
```

See also https://github.com/pocketbase/pocketbase/discussions/903#discussioncomment-4369458, https://github.com/pocketbase/pocketbase/discussions/3849 and other similar discussions.

If that's not the case, please create a _minimal_ reproducible repo and I'll try to investigate in more details.

**Comment by Stolson** [comment]
I figured it out, my callback hook is SSR so I can't touch local storage, but the way SvelteKit wants you to set cookies is not with `setHeaders`:

```
export const GET = async ({ locals, url, cookies }) => {
    ....
};
```

So at the end of my callback, I need to call:

```
const { token } = await locals.pb
    .collection('users')
    .authWithOAuth2Code(provider.name, code, expectedVerifier, redirectURL);
cookies.set('pb_auth', JSON.stringify({ token: token, model: null }), { path: '/' });
```

Since I can't use the serialized one directly.

**Comment by ganigeorgiev** [comment]
I'm confused. `LocalStorage` is not used in a server-side context (unless the runtime implements it, eg. like `Deno`) but in any case it has no relation to whether a cookie will be added to your response.

Note that the above probably works, not because of the `cookies.set` vs `response.headers.append('set-cookie', ...)` usage, but because you are exporting the cookie without the `SameSite` attribute and browsers will fallback by default to `Lax`.

For more information why this is happening you can check the above links and also:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1465402#c6
- https://www.nogginbox.co.uk/blog/strict-cookies-not-sent-by-request
- https://stackoverflow.com/questions/42216700/how-can-i-redirect-after-oauth2-with-samesite-strict-and-still-get-my-cookies
