### ISSUE TITLE
Problem with uploading larger files when not using FormData

### ISSUE THREAD

**Issue by Igloczek** [pocketbase/js-sdk#288]
I'm facing a strange issue with larger (15 MB+) files uploading.

This code works perfectly fine, no errors:
```js
const data = new FormData()

data.append("commentsCount", String(commentsCount))
data.append("savedTime", String(savedTime))

if (file) {
  data.append(
    "files",
    new File([new Blob([JSON.stringify(file)])], `comments.json`),
  )
}

history = await pb.collection("history").update(parentId, data)
```

but when I use a plan object like this:
```js
history = await pb.collection("history").update(parentId, {
  commentsCount: commentsCount,
  savedTime: savedTime,
  files: file && [
    new File([new Blob([JSON.stringify(file)])], `comments.json`),
  ],
})
```

it successfully saves the file in PocketBase, but throws a very cryptic error
```json
"error": {
    "isAbort": false,
    "name": "ClientResponseError 0",
    "originalError": {
        "cause": {
            "code": "EPIPE",
            "errno": -32,
            "syscall": "write"
        }
    },
    "response": {},
    "status": 0,
    "url": ""
},
```
or
```js
"err": {
    "isAbort": false,
    "message": "Something went wrong while processing your request.",
    "name": "ClientResponseError 0",
    "originalError": {
        "message": "fetch failed: write EPIPE",
        "stack": "TypeError: fetch failed
           at node:internal/deps/undici/undici:12618:11
           at async Module.POST (file:///app/dist/server/chunks/pages/history_B-QssYE-.mjs:79:17)
           at async renderEndpoint (file:///app/dist/server/chunks/astro_CeihhVXt.mjs:372:20)
           at async file:///app/dist/server/chunks/_astro-internal_middleware_CDrMLw13.mjs:224:24
           at async callMiddleware (file:///app/dist/server/entry.mjs:976:10)
           at async RenderContext.render (file:///app/dist/server/entry.mjs:1465:22)
           at async NodeApp.render (file:///app/dist/server/entry.mjs:1994:18)
           at async file:///app/dist/server/entry.mjs:2345:24
           at async file:///app/dist/server/entry.mjs:2377:7\ncaused by: Error: write EPIPE
           at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
           at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)
           at writevGeneric (node:internal/stream_base_commons:138:26)
           at Socket._writeGeneric (node:net:950:11)
           at Socket._writev (node:net:959:8)
           at doWrite (node:internal/streams/writable:588:12)
           at clearBuffer (node:internal/streams/writable:766:5)
           at onwrite (node:internal/streams/writable:644:7)
           at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:106:10)
           at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)",
        "type": "TypeError"
    },
    "response": {},
    "stack": "ClientResponseError 0: Something went wrong while processing your request.
       at file:///app/node_modules/.pnpm/pocketbase@0.21.1/node_modules/pocketbase/dist/pocketbase.es.mjs:1:32313
       at async Module.POST (file:///app/dist/server/chunks/pages/history_B-QssYE-.mjs:79:17)
       at async renderEndpoint (file:///app/dist/server/chunks/astro_CeihhVXt.mjs:372:20)
       at async file:///app/dist/server/chunks/_astro-internal_middleware_CDrMLw13.mjs:224:24
       at async callMiddleware (file:///app/dist/server/entry.mjs:976:10)
       at async RenderContext.render (file:///app/dist/server/entry.mjs:1465:22)
       at async NodeApp.render (file:///app/dist/server/entry.mjs:1994:18)
       at async file:///app/dist/server/entry.mjs:2345:24
       at async file:///app/dist/server/entry.mjs:2377:7",
    "status": 0,
    "type": "ClientResponseError",
    "url": ""
},
```

The same code, but with smaller files, works just fine.

**Comment by ganigeorgiev** [comment]
I'm not sure what could be the cause but I don't think this is a PocketBase issue.

`ClientResponseError 0` usually means a client-side error, aka. the request has never reached the PocketBase server.

If you are using Node.js or other server runtime double check whether the server framework you use has body size limits. The same apply if you use a reverse proxy (nginx, apache, etc.)

One way to rule out JS SDK issue is to try to perform the request with plain `fetch`. If it fails then most likely there is something wrong with the JS server configuration.

An alternative to verify that it is not a JS SDK issue is to create a plain HTML file in `pb_public/index.html`:

```html
<!DOCTYPE html />
<html>
<head>
    <meta charset="utf-8" />
    <title>Test</title>
</head>
<body>
    <script type="module">
        import PocketBase from "https://cdn.jsdelivr.net/gh/pocketbase/js-sdk@0.21.1/dist/pocketbase.es.mjs";

        const pb = new PocketBase("http://127.0.0.1:8090");

        // authenticate if needed
        await pb.collection("users").authWithPassword("test@example.com", "1234567890")

        // send the request
        const data = new FormData()

        data.append("commentsCount", String(commentsCount))
        data.append("savedTime", String(savedTime))

        const file = ...
        if (file) {
          data.append(
            "files",
            new File([new Blob([JSON.stringify(file)])], `comments.json`),
          )
        }

        history = await pb.collection("history").update(parentId, data)
        console.log(history)
    </script>
</body>
</html>
```
Navigate to `http://127.0.0.1:8090` in your browser and check the console.

If you still think that this is a JS SDK issue, feel free to create a minimal reproducible repo and I'll try to investigate it further.

**Comment by ganigeorgiev** [comment]
On second read, a reason why the object format may not work is that maybe the `File` detection fails. If you are using Node.js I'm not even sure how it works in the first place because the `File` interface is not available there - https://developer.mozilla.org/en-US/docs/Web/API/File.

**Comment by Igloczek** [comment]
> aka. the request has never reached the PocketBase server

It's reaching the PocketBase server, the files are saving okay, and there are no errors in PocketBase server logs, but yet somehow the try/catch wrapping SDK method call, catches mentioned errors

> double check whether the server framework you use has body size limits

But I'm talking directly with PocketBase instance, using PocketBase SDK, it's not a problem with getting data to PocketBase SDK, otherwise it will fail before reaching the SDK, while the errors are clearly from the SDK.

> The same apply if you use a reverse proxy (nginx, apache, etc.)

I don't have any reverse proxy in front of PocketBase, while as mentored above, it's not traffic that is routing through my app.

> it should work with just the [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob)

It indeed seems to work okay with just Blob, but that way I can't name the file, it's just `blob.json` + whatever PB generate.

**Comment by ganigeorgiev** [comment]
> It's reaching the PocketBase server, the files are saving okay, and there are no errors in PocketBase server logs, but yet somehow the try/catch wrapping SDK method call, catches mentioned errors

Then in this case the request connection most likely was interrupted for some reason from the client (in your case node server). It could be a timeout limit, network connectivity issue, etc.

Without minimal reproducible steps I'm not sure how to help you debug it.

**Comment by ganigeorgiev** [comment]
If the PocketBase server was the reason why the connection was interrupted there should be a log in the Admin UI > Logs. Alternatively you can also start the executable with `--dev` and inspect the stderr output.

But again, there are not enough details to understand why `File` doesn't work with large files (_if the `File` object detection was the problem I expect it to fail with the small files too_), nor why it works with just `Blob`.

**Comment by ganigeorgiev** [comment]
I've tried to reproduce the issue locally but I'm not able to, so I suspect the problem in your case lies somewhere with the node JS setup or running environment.

I've tested the below with PocketBase v0.22.9, JS SDK v0.21.1 and Node.js v21.7.1:

```js
// node test.js

import PocketBase from "pocketbase";

const pb = new PocketBase("http://127.0.0.1:8090")

await pb.collection("example").update("itw00s0akoqgs1j", {
    title: "something 123",
    files: [
        // upload dummy ~20mb file
        new File([new ArrayBuffer(20000000)], "test.txt"),
    ]
})
```
