### ISSUE TITLE
Sveltekit Login & Sign up setup not working properly

### ISSUE THREAD

**Issue by RA9** [pocketbase/js-sdk#29]
Hi boss, 

I followed your pattern regarding setting up pocketbase on SSR but it is not working properly.

![image](https://user-images.githubusercontent.com/20514920/187151704-8504cef5-3958-43ed-939a-aa40ef777ad0.png)

and my login is:
![image](https://user-images.githubusercontent.com/20514920/187152057-a99fa33f-e255-4ef6-bc32-d92c62169d78.png)

Yet the `token` and the user's model are not being stored in LocalStorage

I guess I am doing something wrong but can't tell

**Comment by ganigeorgiev** [comment]
@RA9 LocalStorage is not available on the serverer-side, this is why cookies are used in the example. When using SSR it is expected that the authentication is managed only by the server. If you want to have access to the authentication token, both server-side and client-side, then you'll have to set `httpOnly: false` as cookie option and attach a browser authStore listener to update the cookie via `document.cookie` as shown here - https://github.com/pocketbase/js-sdk/issues/15#issuecomment-1228793115.

If your application is behind an authwall and doesn't need SSR, then my recommendation would be to just use the SDK only within the browser (aka. client-side). LocalStorage will be instantiated by default you'll not have to manage or to any upfront configuration and setup.

**Comment by ganigeorgiev** [comment]
@RA9 Here is a little more complete example if you want to access the authStore from both client-side and server-side:

1. Server-side PocketBase instance

```js
// src/hooks.js

import PocketBase from 'pocketbase';

export async function handle({ event, resolve }) {
    event.locals.pocketbase = new PocketBase("http://127.0.0.1:8090");

    // load the store data from the request cookie string
    event.locals.pocketbase.authStore.loadFromCookie(event.request.headers.get('cookie') || '');

    const response = await resolve(event);

    // send back the default 'pb_auth' cookie to the client with the latest store state
    response.headers.set('set-cookie', event.locals.pocketbase.authStore.exportToCookie({ httpOnly: false }));

    return response;
}
```

2. Client-side (browser) Pocketbase instance

```js
// src/browserClient.js
import PocketBase from 'pocketbase';

const client = new PocketBase("http://127.0.0.1:8090");

client.authStore.loadFromCookie(document.cookie);

client.authStore.onChange(() => {
    document.cookie = client.authStore.exportToCookie({ httpOnly: false });
})

export default client;
```

And then in your client-side components, you just import the above `browserClient.js`:

```js
import client from "src/browserClient.js"

// do somethin

**Comment by jamauro** [comment]
FYI, if you're testing with Safari on localhost you will need to set `secure: false`

```js
response.headers.set('set-cookie', event.locals.pocketbase.authStore.exportToCookie({ httpOnly: false, secure: false }))
```

If anyone knows of a better way, let me know.

**Comment by Vrajs16** [comment]
@jamauro Thank you so much.

**Comment by Vrajs16** [comment]
Actually never mind: [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies)
