### ISSUE TITLE
Missing Auto Completion Realtime - Fields, Filter, Expand

### ISSUE THREAD

**Issue by tobiasbenkner** [pocketbase/js-sdk#296]
Thanks for creating Pocketbase. I really enjoy to work with it.

I came across the realtime subscriptions options fields, filter and expand. https://github.com/pocketbase/pocketbase/releases/tag/v0.20.0-rc. 

I just want to point out that 
- the documentation not saying about it https://pocketbase.io/docs/api-realtime/#set-subscriptions
- and that the autocompletion is not working

Therefore people don't know about this cool feature.

**Comment by ganigeorgiev** [comment]
It is mentioned in the documentation (there is both example with the `options` topic query param and comment about _"other options like expand, custom headers, etc."_ in the SDK examples). I'll consider making it more clear in the near future, but other tasks are with higher priority right now (the documentation will have to be updated anyway after the [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355)).

About the autocompletion - testing with Sublime and the LSP TypeScript plugin it works correctly for me. Make sure that your editor doesn't have cache for some older version of the SDK. For the TS definition see also https://github.com/pocketbase/js-sdk/blob/master/src/services/RecordService.ts#L120.
