### ISSUE TITLE
Running under nodejs environment

### ISSUE THREAD

**Issue by linktohack** [pocketbase/js-sdk#3]
For some reasons, the `axios` module is bundled with `xhrAdapter` even if running under nodejs environment.

The fix is to replace the adapter when initialising the client:

```typescript
import PocketBase from "pocketbase/dist/pocketbase.umd"; // or "pocketbase" if using esmodule
import httpAdapter from "axios/lib/adapters/http.js";

const client = new PocketBase("http://localhost:8090", undefined, undefined, {
  adapter: httpAdapter,
});

(async () => {
  const userData = await client.Users.authViaEmail(
    "user1@REDACTED",
    "REDACTED"
  );
  console.log("userData", userData);
})();

**Comment by linktohack** [comment]
May related, let me know if you're interested in a PR to update the doc/README.

https://github.com/axios/axios/issues/2731

**Comment by linktohack** [comment]
No problem, you can close the issue, hope it will useful if someone in the future are looking for the same problem.

Anyway, very cool project. Carry on! 💯

**Comment by ganigeorgiev** [comment]
I've reworked the bundles situation and update the README to reflect the changes.
In short, to use it with node.js environments, it should be enough to do:
```js
const PocketBase = require("pocketbase");
```

If you are using es6 style imports (you need to have also `"type": "module"` in your `package.json`):
```js
import PocketBase from "pocketbase";
```

I've tested both with node v16.14.0.

If you are still experiencing issue loading the client, please let me know and I'll investigate it further.
