### ISSUE TITLE
Error in docs Autocancelation example wrong

### ISSUE THREAD

**Issue by Raphael2b3** [pocketbase/js-sdk#300]
I just read the auto cancelation chapter of the readme.

https://github.com/pocketbase/js-sdk#auto-cancellation

i noticed that you provided an example for when something should be canceled

![grafik](https://github.com/pocketbase/js-sdk/assets/70175424/aa146965-421c-4705-a5ec-42ac9b599ca1)

but in this example you change the first parameter of each function call, which will change the page of the result.

so i its a different query and shouldnt be cancelled.

**Comment by ganigeorgiev** [comment]
No, it is working correctly because the default request key is `HTTP_METHOD + path`, aka. the query parameters are not included.
