### ISSUE TITLE
Both client and serverside setup, problem with cookie

### ISSUE THREAD

**Issue by Laestry** [pocketbase/js-sdk#301]
My current setup is like this
pb.ts:
```
import PocketBase from 'pocketbase';
import { PUBLIC_DB_URL } from '$env/static/public';

const pb = new PocketBase(PUBLIC_DB_URL);

export default pb;
```

hooks.client.ts:
```
import pb from '$lib/pocketbase/pb';

export async function handle({ event, resolve }) {
	pb.authStore.loadFromCookie(document.cookie);

	if (pb.authStore.isValid) {
		//todo: do something here
	}

	pb.authStore.onChange((token, model) => {
		document.cookie = pb.authStore.exportToCookie({ httpOnly: false });
	});

	return await resolve(event);
}
```

which works great, but sometimes I want to use sveltekits ssr capabilities eg to hydrate the user/other content. The problem I run into is:
After the user logs in using the clientside pb and a cookie is created. When I reload and hooks.server.ts proccesses the cookie, the authstore is not valid for some reason, even though once the client loads, it is valid

hooks.server.ts:
```
export async function handle({ event, resolve }) {
	event.locals.pb = new PocketBase(PUBLIC_DB_URL);
	const cookie = event.request.headers.get('cookie') || '';
	// console.log(cookie);
	event.locals.pb.authStore.loadFromCookie(cookie);

	if (event.locals.pb.authStore.isValid) {
		event.locals.user = serializeNonPOJOs(event.locals.pb.authStore.model);
	} else {
		event.locals.user = undefined;
	}

	const response = await resolve(event);

	//response.headers.set('set-cookie', event.locals.pb.authStore.exportToCookie({ secure: false }));
	//commented this so the cookie won't get erased

	return response;
}
```

The cookie prints in hooks.server.ts.
Maybe I've missed something super obvious? Thank you ahead of time!

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand what is the desired behavior but I don't think this is an issue with the JS SDK.

If you want a mixed (aka. both client-side and server-side access to the PocketBase server) from your SvelteKit app then you'll have to export the cookie with the `httpOnly:false` option from the server-side.

Additionally, I'm not sure what `serializeNonPOJOs` is but note that the JS SDK returns plain JS objects so it shouldn't be necessary.

For a general SSR guide please refer to https://github.com/pocketbase/js-sdk?tab=readme-ov-file#ssr-integration.

_As a side-note, if you are I don't recommend using JS SSR as most likely you'll mess up the security. Some more ramblings on this you could find in https://github.com/pocketbase/pocketbase/discussions/3792#discussioncomment-7620032, https://github.com/pocketbase/pocketbase/discussions/4412#discussioncomment-8575834 and probably others._

If you need further help, please open a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions) in the main repo elaborating more on your use case and the desired outcome.

**Comment by Laestry** [comment]
Thank you for the quick answer, will try that! How come it matters if I export the cookie in hooks.server and not in hooks.client?

**Comment by ganigeorgiev** [comment]
>  how come it matters if I export the cookie in hooks.server and not in hooks.client?

`hooks.client` executes on the client/browser. `hooks.server` executes on the server.

The `HttpOnly` flag allows or forbid **client-side access** to the cookie and it makes sense when it is set from the server-side.

Don't follow blindly some YouTube tutorial as most likely it is already outdated and please check the above linked discussions. If your need further help, open a new one and try to elaborate more clearly on your use case to understand the bigger picture and why you need mixed access in the first place.
