### ISSUE TITLE
pb.authStore.isValid always returning false

### ISSUE THREAD

**Issue by guilhermeguidetti** [pocketbase/js-sdk#302]
Hello!

It was always working, and for some reason now it just returns false. Even using console.log to get the token and using it in Postman, it is valid and returns results.

To save it, I do it in the following way in a Context file:

```js
const url = "https...";
useEffect(() => {
    const store = new AsyncAuthStore({
      save: async (serialized) => AsyncStorage.setItem("pb_auth", serialized),
      initial: AsyncStorage.getItem("pb_auth"),
    });
    const client = new PocketBase(url, store);
    setBackendClient(client);

    backendClient?.autoCancellation(false);
}, []);
```

I don't know why it is returning false since using the token, which is considered invalid, works via Postman and Pocketbase SDK calls.

**Comment by ganigeorgiev** [comment]
If the above is being executed in React Native make sure to update to the latest SDK version.

For more details see https://github.com/pocketbase/pocketbase/issues/5013.

If that's not the case, feel free to provide more details about your environment and where you are testing, and I'll try to investigate it further.
