### ISSUE TITLE
Add some explanatory comments for the 'fields' field

### ISSUE THREAD

**Issue by RainSunMe** [pocketbase/js-sdk#303]
https://github.com/pocketbase/js-sdk/blob/ab68644b4ba586afd6c7659cad5eba9b491bb908/src/services/utils/options.ts#L52

Could you please include some explanatory comments for the 'fields' field to help alleviate any confusion that might arise for newcomers?

```ts
 /**
     * Specifies the fields to include in the response.
     * @example "field,expand.someRelField.subRelField"
     * this will include the field `field` and the nested fields `someRelField.subRelField`
     *
     * @example "*,expand.someRelField.subRelField"
     * this will include all fields and the nested fields `someRelField.subRelField`
     */
 ```

**Comment by ganigeorgiev** [comment]
There is already documentation available in the generic [Web API docs](https://pocketbase.io/docs/api-records/) and the "API Preview" from the Admin UI.

There are plans to change how the JS SDK types are defined so I may consider updating it but for now lets leave as it is.
