### ISSUE TITLE
Ignore trailing slash in base url

### ISSUE THREAD

**Issue by alfredjophy** [pocketbase/js-sdk#304]
Having a trailing slash in the base_url, e.g, `https://pocketbase.xyz/` results in the trailing slash duplicated for the api calls
( `https://pocketbase.xyz//api`). 

This can be mitigated by doing a check on the base url being passed. ( `( new Url(base_url)).origin` )

**Comment by alfredjophy** [comment]
Do let me know, if this is a valid issue, I can make a PR for it. Thanks

**Comment by ganigeorgiev** [comment]
By default the JS SDK will try to normalize the base url to ensure that there is always a trailing slash - https://github.com/pocketbase/js-sdk/blob/master/src/Client.ts#L268

Without details where and what call do you make that the above is causing issues, there are no plans to change the current implementation.
