### ISSUE TITLE
afterSend hook options

### ISSUE THREAD

**Issue by pondrax** [pocketbase/js-sdk#305]
Could you please add options to the `pb.afterSend` hook? 
This way, I can identify which request was made if I want to implement `afterSend` globally, for example to put some UI toast alert if some record is deleted.

(https://github.com/pocketbase/js-sdk/blob/master/src/Client.ts#L360

```javascript
if (this.afterSend) {
    data = await this.afterSend(response, data);
}

**Comment by ganigeorgiev** [comment]
I don't think there is need for it. You can get information about the request from the [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) object (eg. `response.url`).

**Comment by tcmzzz** [comment]
Hi, `Response` object seems not enought to identify `DELETE` or `Update`.
It would be better if we known  the `method` (in `options`).
