### ISSUE TITLE
Post 400 error on browser console with bad user credentials

### ISSUE THREAD

**Issue by marcitqualab** [pocketbase/js-sdk#306]
Hello 

I have implemented the login and signup forms for a new project. I am using this js-sdk in a react project. 
When I test the login with bad credentials i see a POST 400 error log in the browser console, even though I am adding a try catch around the line

```javascript
const authData = await pb.collection('users').authWithPassword('YOUR_USERNAME_OR_EMAIL', '1234567890');
```

This is my login method in the pocketbase.tsx

```javascript
export async function login(username: string, password: string) {
  try {    
    const result = await pbClient.collection("users").authWithPassword(username, password);
    console.log("pb login success",  result);
  } catch (error) {
    console.log("PocketBase error", error);
    console.log("pb login not successful");
  }
}
```

Looks like am not able to properly catch this error or the sdk is sending the error directly to the console?

How can I capture that error log trace so that the end user does not get that error on the browser console?

Many thanks

![pocketbase post 400 console error](https://github.com/user-attachments/assets/44a3be63-2d73-406f-8d79-9a5c5a4be244)

**Comment by ganigeorgiev** [comment]
I don't think there is an issue here. Your `console.log` are printed so the exception has been catched.

The `POST ...` red message you see is just the browser printing the failed network request (you can try emulating the same using a plain `fetch`). If you are using Chrome, you can hide these messages from the _Console settings > Hide network_ checkbox.

![console_settings](https://i.imgur.com/QBXvQWM.png)

**Comment by marcitqualab** [comment]
Ah ok I see, got it. 
Many thanks for the quick response.
