### ISSUE TITLE
jwt token decoded on the frontend

### ISSUE THREAD

**Issue by Tudor036** [pocketbase/js-sdk#307]
Hello, I was looking at the base auth storage and I saw that there is a function `getTokenPayload` imported from the utils folder that simply **decodes the token**. 

From what i understand, this js-sdk is made to work on the frontend, so isn't this some security concern that the jwt is decoded on the client side?

**Comment by ganigeorgiev** [comment]
The token is always validated when sending request to the PocketBase server.

The `getTokenPayload` is just a helper to extract the base64 decoded payload. It doesn't have or serve any security purpose.
