### ISSUE TITLE
Question: how to force to provide a filter on List Search rule to avoid that someone can get full collection

### ISSUE THREAD

**Issue by claudiopostinghel** [pocketbase/js-sdk#318]
Hello,

I'm facing an issue with a specific use case.

I have two collections: CollectionA and CollectionB, with CollectionA related to CollectionB. To retrieve a filtered subset, users currently use:
```
pb.collection("CollectionA").getFullList({
      filter: `CollectionB = "${id}"`,
});
```
The problem is that users could simply remove the filter to access all data, which isn’t secure.

I’ve reviewed the documentation for filter rules, but I’m still having trouble implementing the correct solution.

Is it possible? Or am I using the wrong method?

**Comment by ganigeorgiev** [comment]
I don't see how this is a JS SDK related issue.

I'm lacking context to make sense of the above rule but note that the `filter` query parameters is suitable for client-side filtering.

The access to your collections is managed though the specific collection API rules. If you have read https://pocketbase.io/docs/api-rules-and-filters/ and it is not clear what the List/View/Create/Update/Delete APi rules does than I'm not sure how to explain it better.

In any case, please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) from the main repo for general PocketBase questions as the threaded format for this type of posts.

**Comment by claudiopostinghel** [comment]
Oh, sorry, first time using this channel and I missed I was in the wrong section.

Thank you very much!
