### ISSUE TITLE
Hyphen breaks filter

### ISSUE THREAD

**Issue by ItsVoltz** [pocketbase/js-sdk#319]
When filtering for a string that is hyphenated in my pb instance I get:

`invalid number "-"`

code:

```js
const record = await pb.collection('licenses').getFirstListItem(`key=${key}`);
  ```

**Comment by ganigeorgiev** [comment]
It is not the hyphen. String literals must be wrapped in single or double quotes, aka. the above should be:

```js
const record = await pb.collection('licenses').getFirstListItem(`key="${key}"`);

// or alternatively using filter params
// (https://github.com/pocketbase/js-sdk#binding-filter-parameters)
const record = await pb.collection('licenses').getFirstListItem('key={:key}', { key });
```

**Comment by ItsVoltz** [comment]
> It is not the hyphen. String literals must be wrapped in single or double quotes, aka. the above should be:
> 
> ```js
> const record = await pb.collection('licenses').getFirstListItem(`key="${key}"`);
> 
> // or alternatively using filter params
> // (https://github.com/pocketbase/js-sdk#binding-filter-parameters)
> const record = await pb.collection('licenses').getFirstListItem(pb.filter('key={:key}', { key }));
> ```

Ah okay this is what I was originally doing but the resource always returns not found even though the key matches in the collection
