### ISSUE TITLE
typescript-specific docs?

### ISSUE THREAD

**Issue by erikKeresztes** [pocketbase/js-sdk#32]
any plans on writing docs for typescript usage? looking through the source i can't figure out how to explicitly type things. if it's not implemented yet, i suggest something like what kysely https://github.com/koskimas/kysely does

**Comment by ganigeorgiev** [comment]
I don't think this is necessary and will just clutter the documentation.

Your editor LSP and autocomplention should be enough to guide you which types are available or returned.
