### ISSUE TITLE
 Please replace pb.files.getUrl() with pb.files.getURL()

### ISSUE THREAD

**Issue by calumk** [pocketbase/js-sdk#321]
> Please replace **pb.getFileUrl()** with **pb.files.getURL()**

If you replace it, you then get the following message, which i guess is an error.

> Please replace **pb.files.getUrl()** with **pb.files.getURL()**

**Comment by ganigeorgiev** [comment]
I don't understand what is the issue here.

If you replace `getUrl` with `getURL` the warning should go away (see [FileService.ts](https://github.com/pocketbase/js-sdk/blob/master/src/services/FileService.ts)). You can also test it in the browser with the below `pb_public/index.html`:

```js
<!DOCTYPE html />
<html>
<head>
    <meta charset="utf-8" />
    <title>Test</title>
</head>
<body>
    <script type="module">
        import PocketBase from "https://cdn.jsdelivr.net/gh/pocketbase/js-sdk@v0.22.0/dist/pocketbase.es.mjs"

        const pb = new PocketBase("http://127.0.0.1:8090");

        const a = pb.files.getURL({id: "rid", collectionId: "cid"}, "fname");
        console.log("URL:", a)
    </script>
</body>
</html>
```
