### ISSUE TITLE
authStore.record is undefined

### ISSUE THREAD

**Issue by MrVauxs** [pocketbase/js-sdk#322]
In the recent update, it is said that `authStore.model` has been soft-deprecated in favor of `authStore.record`. However, from my testing `record` doesnt return anything at all, at least when using `authWithPassword`.

<img width="448" alt="Code_86njXQNz1I" src="https://github.com/user-attachments/assets/1ea4cebd-be0e-448f-a266-9edf313e480d">

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it. Here is a plain `pb_public/index.html` that you can test in the browser:

```html
<!DOCTYPE html />
<html>
<head>
    <meta charset="utf-8" />
    <title>Test</title>
</head>
<body>
    <script type="module">
        import PocketBase from "https://cdn.jsdelivr.net/gh/pocketbase/js-sdk@v0.22.0/dist/pocketbase.es.mjs"

        const pb = new PocketBase("http://127.0.0.1:8090");

        await pb.collection("users").authWithPassword("test@example.com", "1234567890")

        console.log("token:", pb.authStore.token)
        console.log("record:", pb.authStore.record)
    </script>
</body>
</html>
```

If you still think that it is a PocketBase issue please provide some steps to reproduce.

**Comment by MrVauxs** [comment]
You closed it just as I was about to come back to close it myself. I believe either npm or vite screwed me over in this instance, everything works.
