### ISSUE TITLE
Feature Request: Add requestKey Support for .subscribe and .unsubscribe Methods

### ISSUE THREAD

**Issue by MaCleodWalker** [pocketbase/js-sdk#325]
## Description
It would be highly beneficial to extend the `.subscribe` and `.unsubscribe` methods in the PocketBase JS SDK to include an optional `requestKey` parameter. This enhancement would provide greater control over event handling, especially in scenarios with multiple subscriptions or when finer granularity is required for managing real-time updates.

## Motivation
The current `.subscribe` and `.unsubscribe` methods rely primarily on collection names and event types, which can lead to challenges in managing subscriptions in complex applications. Adding a `requestKey` would enable developers to:
- Easily differentiate between subscriptions for the same collection or event.
- Simplify the process of unsubscribing from specific subscriptions without affecting others.
- Improve clarity and maintainability of real-time event management in multi-layered applications.

## Proposed Solution
Enhance the `.subscribe` and `.unsubscribe` methods to accept an additional `requestKey` parameter. For example:

```
javascript
// Subscribe with requestKey
pb.collection("myCollection").subscribe("create", (e) => {
    console.log(e);
}, { requestKey: "uniqueKey123" });

// Unsubscribe using requestKey
pb.collection("myCollection").unsubscribe("create", { requestKey: "uniqueKey123" });
```

## Backward Compatibility
The requestKey parameter should be optional to ensure backward compatibility with existing codebases. If not provided, the methods should default to their current behavior.

## Use Cases
Multi-Component Applications: Different components in a frontend application may need independent subscriptions to the same collection or event. A requestKey allows precise management of these subscriptions.
Debugging and Testing: Developers can isolate specific subscriptions during debugging by using unique requestKey values.
Dynamic Applications: In applications where subscriptions are dynamically created and destroyed, requestKey simplifies tracking and managing these operations.

**Comment by ganigeorgiev** [comment]
Also, it seems that you are using `requestKey` for identifying a subscription, but this differ from [how `requestKey` is used in PocketBase](https://github.com/pocketbase/js-sdk?tab=readme-ov-file#auto-cancellation).

If you are trying to cancel a single subscription, you can simply use its returned unsubscribe function.

**Comment by MaCleodWalker** [comment]
Sorry for the confusion in my initial explanation, and thank you for the feedback. I wasn’t suggesting using requestKey as it’s currently implemented in PocketBase; I used it just as an example to explain the idea.

The issue I’m trying to address is when multiple components in an app subscribe to the same collection but with different filters or queries. In the current setup, if one component unsubscribes, it seems to cause all other subscriptions to that collection to lose their real-time connection, even though they are logically independent.

Here’s a practical example:

Component A subscribes to collectionA with filter filterA.
Component B subscribes to the same collectionA but with filter filterB.
Component A unmounts and calls unsubscribe.
Component B loses its subscription, even though it still needs real-time updates.
In this scenario, it would be helpful if the SDK could differentiate between subscriptions so that unsubscribing in one component doesn’t inadvertently cancel other active subscriptions.

I hope this clears up my intent

**Comment by ganigeorgiev** [comment]
> ... if the SDK could differentiate between subscriptions so that unsubscribing in one component doesn’t inadvertently cancel other active subscriptions.

You can use the returned unsubscribe function for this. For example:

```js
const unsub = await pb.collection("example").subscribe("*", (e) => { ... })

...

// on component destroy/unmount call unsub to remove only the specific subscription
unsub()
```

There are no plans to add 3rd method for unsubscribing unless a more prominent use case arise.

**Comment by MaCleodWalker** [comment]
Thanks for clearing that up! I didn’t realize the unsubscribe function from subscribe could handle specific subscriptions like that. If calling it only removes the exact subscription it’s tied to without affecting others, that should fix the issue I’m running into. I appreciate you taking the time to explain it, and sorry for the confusion on my end. Thanks again for the help!
