### ISSUE TITLE
How to manually use + suffix to append new files in plain request?

### ISSUE THREAD

**Issue by anonimusprogramus** [pocketbase/js-sdk#326]
I've read [Files upload and handling](https://pocketbase.io/docs/files-handling/) and successfully done uploading that way.

Now that I'm [ constructing plain request](https://github.com/pocketbase/js-sdk/issues/56#issuecomment-1294155708), I only get some files uploaded, like 1 or 2 instead of all 5 files. I wonder if it was caused by [Auto cancellation](https://github.com/pocketbase/js-sdk#auto-cancellation) :thinking: 

Anyway, here's the code snippet I'm using, thanks.

```typescript
type UploadArgs = {
  uploadId: string;
  files: File[];
};

function uploadFiles({ uploadId, files }: UploadArgs) {
  files.forEach((file) => {
    const formData = new FormData();
    formData.append("files+", file);

    const xhr = new XMLHttpRequest();
    xhr.upload.onprogress = (event) => {
      const percent = Math.round((100 * event.loaded) / event.total);
      setProgress((prv) => ({
        ...prv,
        [file.name]: { percent, done: percent === 100 },
      }));
    };

    xhr.upload.onerror = () => {
      throw new Error("Failed to upload " + file.name);
    };

    xhr.onload = () => {
      console.log(file.name + " uploaded.");
    };

    xhr.open(
      "PATCH",
      "http://localhost:8090/api/collections/upload/records/" + uploadId,
    );
    xhr.setRequestHeader("Authorization", pb.authStore.token);
    xhr.send(formData);
  });
}
```

**Comment by ganigeorgiev** [comment]
Autocancellation apply only if you are using the JS SDK, in the above example it doesn't seem that to be the case.

In any case, without details about your environment, what is your collection structure, what PocketBase version you are using and what actually is the error, I cannot help you.

Couple notes:
- The `+` prepend/append modifier is supported only with PocketBase v0.23+ (you can find your version in the bottom-right corner of the Dashboard); for <= v0.v22.x appending a new file is done by just using its name, in your case just `files`.
- In the above code sample you are sending separate request for each file. A more optimal solution would be to send the files together in a single request (_when using FormData, calling append for the same key will produce an "array" with the set/appended values for that key_).

In any case, for other questions please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions) in the main repo.
