### ISSUE TITLE
authMethods.authProviders is not iterable

### ISSUE THREAD

**Issue by AntoineGermanique** [pocketbase/js-sdk#327]
Starting version 0.22.0 I get "authMethods.authProviders is not iterable" when using the manual code exchange exemple for the authentication with Oauth2. No problem with the 0.21.5.

**Comment by ganigeorgiev** [comment]
There is no longer `authMethods.authProviders` field. JS SDK v0.22+ is compatible only with PocketBase v0.23+ and introduced several breaking changes. Please refer to the [JS SDK release notes](https://github.com/pocketbase/js-sdk/releases) or [JS SDK CHANGELOG](https://github.com/pocketbase/js-sdk/blob/master/CHANGELOG.md) for more details.

If you are using PocketBase <= v0.22.x, then you have to pin your JS SDK version to `<0.22.0`.

For list of the breaking changes that PocketBase v0.23+ introduced and Go/JSVM upgrade guide, please refer to the [PocketBase JS SDK CHANGELOG](https://github.com/pocketbase/pocketbase/blob/master/CHANGELOG.md#v0230) and its related links.

**Comment by AntoineGermanique** [comment]
Ok Thanks ! (The documentation is outdated then ^^ )

**Comment by ganigeorgiev** [comment]
Oh, you mean for the "Manual code exchange"? I'll update it a little bit later today.
