### ISSUE TITLE
OAuth2 urlCallback: window not available inside serverside actions

### ISSUE THREAD

**Issue by A2-NieR** [pocketbase/js-sdk#328]
Hi there,

I am trying to create a configuration frontend for a discord bot that uses pocketbase as a backend. For this I tried combining the generated redirect url from inside the discord developer bot oauth2 settings, which looks like this

`https://discord.com/oauth2/authorize?client_id=CLIENT_ID&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A5173%2Fapi%2Foauth2-redirect&scope=identify+guilds`

with the `authWithOAuth2()` function.

For the frontend I use the Qwik framework. I know you don't specifically support this one, so I am trying to compare it to SvelteKit where possible.

```ts
// src/routes/plugin@auth.ts

import PocketBase from "pocketbase";
import type { RequestHandler } from "@builder.io/qwik-city";

export const onRequest: RequestHandler = async ({
  headers,
  next,
  sharedMap,
  env,
}) => {
  sharedMap.set("pb", new PocketBase(env.get("PUBLIC_BACKEND_URL")));
  sharedMap.get("pb").authStore.loadFromCookie(headers.get("cookie") || "");

  try {
    sharedMap.get("pb").authStore.isValid &&
      (await sharedMap.get("pb").collection("users").authRefresh());
  } catch (_) {
    sharedMap.get("pb").authStore.clear();
  }

  headers.append("set-cookie", sharedMap.get("pb").authStore.exportToCookie());

  await next();
};
```
This file acts as a [middleware](https://qwik.dev/docs/middleware/#sharedmap) and the pb instance is saved inside sharedMap, the equivalent for SvelteKit's event.locals.
With this I try logging in the user:
```ts
// src/routes/index.tsx
import { routeAction$ } from "@builder.io/qwik-city";

export const usePbLogin = routeAction$(
  async (formData, { redirect, sharedMap, env }) => {
    const redirectUrl = env.get("PUBLIC_DISCORD_GENERATED_URL");
    if (!redirectUrl) {
      throw new Error("No redirect URL provided.");
    }

    try {
      const authData = await sharedMap
        .get("pb")
        .collection("users")
        .authWithOAuth2({
          provider: "discord",
          scopes: ["identify", "guilds"],
          redirectURL: "/admin",
          urlCallback: () => {
            throw redirect(302, redirectUrl);
          },
        });

      console.log("authData  authData:", authData);
    } catch (error) {
      console.error(error);
    }
    console.log(sharedMap.get("pb").authStore);
  },
);
```
For the urlCallback it does not matter which url is used, it always results in the same error: `ClientResponseError 0: Something went wrong while processing your request.`
```ts
urlCallback: (url: string) => {
   throw redirect(302, url || redirectUrl);
},
```

After reading some issues and seeing the provided example code for `urlCallback` in them, the problem seems to be that [routeActions](https://qwik.dev/docs/action/) exclusively execute on the server which makes it impossible to access `window`. 

Correct me if I'm wrong but there seem to be two issues:

1. The OAuth2 in the current state does not work when used in server-side actions, since in [similar issues](https://github.com/pocketbase/js-sdk/issues/283#issuecomment-2018526759) I saw you providing examples using `window.open()`, but window is not defined when executing serverside.
(Also, I noticed the readme provides a server-side action for SvelteKit, but there the regular `authWithPassword()` is used there instead).
2. Providing a custom redirect url from the discord developer portal conflicts with the pb generated redirect url?

---

Alternatively, I already was successful using https://authjs.dev/getting-started/authentication/oauth for the OAuth2 using my discord bot url. It enabled me to have users authenticate via discord OAuth2 and use the resulting [access_token](https://authjs.dev/reference/qwik#properties-2) for further calls to the discord api (getting more infos about servers, channels, etc. all necessary for the bot to work).
However right now I am not sure how I could combine this successful authentication (user info) for usage with pocketbase, without the user having to do double authentication to be able to call guarded pocketbase apis.

Can and should the user data from the successful OAuth2 be used inside pocketbase (could be helpful to track user behavior with the bot) or would a better approach be to only have the bot itself be able to communicate with the pb apis?

Thank you in advance and do let me know if you need more info.

**Comment by ganigeorgiev** [comment]
The "all-in-one" OAuth2 flow (`authWithOAuth2`) is intended to be used on the client-side because it needs to maintain a realtime connection to receive the auth data after successull OAuth2 authentication.

If you want to perform the OAuth2 handling on the server-side then you need to follow the "Manual code exchange" flow, aka. the second tab in https://pocketbase.io/docs/authentication/#authenticate-with-oauth2.

In any case this is not a JS SDK or PocketBase issue. In general I don't recommend using PocketBase with JS SSR frameworks because it comes with a lot of complications and most likely you'll messup with the security of your application. Please read https://pocketbase.io/docs/client-side-sdks/#js-ssr-meta-framework-caveats.
