### ISSUE TITLE
trying to implement the js-sdk for nextjs

### ISSUE THREAD

**Issue by z89** [pocketbase/js-sdk#33]
Hey, so I am trying to implement pocketbase using the javascript sdk in next.js . I setup a boilerplate next.js application with pocketbase installed like in the example provided in the README. This is what my index.js looks like: 
```
import PocketBase, { BaseAuthStore } from "pocketbase";

class NextAuthStore extends BaseAuthStore {
  constructor(req, res) {
    super();

    this.req = req;
    this.res = res;

    this.loadFromCookie(this.req?.headers?.cookie);
  }

  save(token, model) {
    super.save(token, model);

    this.res?.setHeader("set-cookie", this.exportToCookie());
  }

  clear() {
    super.clear();

    this.res?.setHeader("set-cookie", this.exportToCookie());
  }
}

export async function getServerSideProps({ req, res }) {
  const client = new PocketBase("http://127.0.0.1:8090");
  client.authStore = new NextAuthStore(req, res);

  // fetch example records...
  const result = await client.records.getList("example", 1, 30);

  return {
    props: {
      result: result,
    },
  };
}

export default function Home({ result }) {
  console.log(result);

  return <h1>test</h1>;
}
```
This causes the following error: 
`error - ReferenceError: AbortController is not defined`

![nextjs error](https://user-images.githubusercontent.com/30657227/190837370-4570a9cd-0fa2-4c5b-8301-e3994f0a250b.png)

I know that you don't officially support any SSR frameworks as the README stated:
`Unfortunately, there is no "one size fits all" solution because each framework handle SSR differently (and even in a single framework there is more than one way of doing things).`

However I am wondering if there is a solution for this error? I tried reading up on AbortControllers, but there are no solutions I could find which wouldn't require me to fork this repo and start making changes, which I'm not technically inclined enough do so & make a pull request. At the moment I can't use the sdk and I am just communicating with the server through the API. Any thoughts or leads to try to fix this?

Once again, thank you for your time and keep up the great work!

**Comment by ganigeorgiev** [comment]
@z89 Could you check what version of node you are using (`node -v`)?

`AbortController` should be already supported node15+. If you are using an older node, then you would have to either upgrade your node, or load a `AbortController` polyfill (I haven't use any, but here is the first one that came up in my search  - https://www.npmjs.com/package/abortcontroller-polyfill).

**Comment by z89** [comment]
the latest nextjs version seems to be node v14.20.0. I tried upgrading it to v15 as well as the latest version but the original error still remains. I had a look at the abortcontroller-polyfill package, however I think I need access to fetch() to include the controller.signal  to abort the controller as shown here:
```
const controller = new AbortController();
const signal = controller.signal;
fetch('/some/url', {signal})
  .then(res => res.json())
  .then(data => {
    // do something with "data"
  }).catch(err => {
    if (err.name == 'AbortError') {
      return;
    }
  });
// controller.abort(); // can be called at any time
```
I not sure which of the pocketbase functions makes the fetch request to have to include the signal:
` const client = new PocketBase("http://127.0.0.1:8090");`
`client.authStore = new NextAuthStore(req, res);`
`const result = await client.records.getList("example", 1, 30);`

I tried creating a new AbortController() and aborting it at various points, but to no avail, because the fetch function doesn't include the signal. I have been playing around with it for a bit, but can't change the original error at all. Thoughts?

**Comment by ganigeorgiev** [comment]
nextjs doesn't come with node. Nextjs is a library/framework and it doesn't come with node. It requires it so that you can work with it (the same way as you have to install a specifyc language/runtime on your computer before installing a framework/library).

Anyway, nextjs should work jist fine with node 16+. Node14 is no longer actively maintained and its official support will end ~ at the beginning of 2023 (check https://endoflife.date/nodejs).

About the polyfill - you need to register it as global - `global.AbortController = AbortController`. But my recommendation is to upgrade your node (you can also use nvm if you want to be able to switch between node versions).
