### ISSUE TITLE
Incorrect detection of an "AbortError"

### ISSUE THREAD

**Issue by tobicrain** [pocketbase/js-sdk#35]
Currently, when I try to create multiple real-time subscriptions (and get an error) the variable 
`isAbort = false`
but
`originalError.message` is equal to "Aborted" and 
`originalError.name` = "AbortError"

**Comment by ganigeorgiev** [comment]
@tobicrain A fix to disable autocancellation for the realtime subscriptions were added in [v0.7.1 release](https://github.com/pocketbase/js-sdk/releases/tag/v0.7.1).

If after the update you are still receiving request abort errors, please let me know and I'll investigate it further.
