### ISSUE TITLE
Persist authStore in React Native (Expo)

### ISSUE THREAD

**Issue by bencreynolds** [pocketbase/js-sdk#37]
I am specifically using Expo, but this question probably applies to general React Native as well.

My authStore does not persist between reloads. Reading the docs, this makes sense, since it is defaulting to runtime storage. I need to be able to persist this information, either with ExpoFileSystem, AsyncStorage, or Redux-Persist. As it stands now, it is impossible for me to push the app to production using the provided SDK.

Any help?

**Comment by ganigeorgiev** [comment]
@bencreynolds You can always create a new Expo auth store and pass it to the client constructor, eg:

```js
import PocketBase, { BaseAuthStore } from 'pocketbase';

class ExpoAuthStore extends BaseAuthStore {
    save(token, model) {
        super.save(token, model);
        // your custom business logic...
    }
}

const client = new PocketBase('http://127.0.0.1:8090', 'en-US', ExpoAuthStore());
```

The only requirement is to extend `BaseAuthStore`. More info could be found in the "AuthStore" section of the readme - https://github.com/pocketbase/js-sdk#authstore.

**Comment by bencreynolds** [comment]
Hey thanks for the reply. Could you go into a bit more detail. I’m not sure I really understand what the custom business logic is supposed to be in this context. When I call super.save() should I be storing the model object somewhere that has data persist? What about clears and updates? What if my token dies between sessions, my persisted store won’t know that. 

I’m really not sure what to do with that information.

**Comment by ganigeorgiev** [comment]
>  When I call super.save() should I be storing the model object somewhere that has data persist?

Yes. It's up to the developer to decide which storage mechanism to use and where to persist the data. The `BaseAuthstore` is just an abstract class. It has 2 main methods that  users need to implement - `save` (for persisting the token and auth model somewhere) and `clear` for deleting the previously stored state.

Or in other words. you minimal custom auth store could look like this:

```js
class CustomAuthStore extends BaseAuthStore {
  // you can define a constructor if your store requires some initialization options
  constructor(someCustomProp) {
    super();

    this.someCustomProp = someCustomProp;
  }

  save(token, model) {
    super.save(token, model);

    // @todo save to your custom storage of choice...
  }

  clear() {
    super.clear();

    // @todo clear from your custom storage of choice...
  }
}
```

To the BaseAuthStore definition for more details what methods you can overwrite - https://github.com/pocketbase/js-sdk/blob/master/src/stores/BaseAuthStore.ts.

---

> What if my token dies between sessions, my persisted store won’t know that.

**PocketBase API is fully stateless - it doesn't have sessions (even the tokens aren't stored in the database).** The JWT token has `exp` payload that you could check if you need to loosely check whether the stored token is valid or not.

**Comment by bencreynolds** [comment]
Thanks for the reply, this is informative. 2 questions:

1) is there a way that I can model with with functional components? I have next to no experience working with classes or “extending” components. More specifically, I would prefer to use redux-toolkit and redux-persist for state storage and manipulation, which uses Hooks. As far as I understand it, Hooks cannot be called from class components. 

2) If a JWT token expires, and a notice this in my custom business logic, do I need to clear the user’s authStore and make them log in again, or can I just refresh using client.users.refresh()?

**Comment by ganigeorgiev** [comment]
1. The SDK doesn't really know anything about react or its functional components. The AuthStore is just a regular Javascript class/object and you can do anything inside it and call it in your react components (class or functional) just like any other js object.

2. You don't have to manually clear the token from the auth store, because when you call `client.users.refresh()` it internally will trigger `client.authStore.save(...)` for you and will update the store with the latest state.

The store will be auto updated after calling successfully one of this methods:
- `client.users.authViaEmail()`
- `client.users.authViaOAuth2()`
- `client.users.confirmPasswordReset()`
- `client.users.confirmVerification()`
- `client.users.confirmEmailChange()`

**Comment by bencreynolds** [comment]
Interesting. Thank you for all this information, I will poke around with this this morning and like come back with more questions.

**Comment by ganigeorgiev** [comment]
Could you provide a code sample how you are initializing the client and registering the authstore?

Make sure that you are actually passing an instance of the store, not just the class name. Something like this should work:

```js
import PocketBase, { BaseAuthStore } from "pocketbase";

class CustomAuthStore extends BaseAuthStore {
  constructor() {
    super();

    // @todo load the token and model from your custom storage of choice...
    this.baseToken = '...';
    this.baseModel = null; 
  }

  save(token, model) {
    super.save(token, model); // this will save the token and model in the local baseToken and baseModel props

    // @todo save to your custom storage of choice...
  }

  clear() {
    super.clear(); // this will reset the local baseToken and baseModel props

    // @todo clear from your custom storage of choice...
  }
}

const client = new PocketBase("http://127.0.0.1:8090", "en-US", CustomAuthStore());
```

**Comment by bencreynolds** [comment]
Hey, yeah I got that figured out actually. I had to throw a “new” in front of the instance for it to work.

but I guess I have a new issue. This isn’t directly related to pocketbase, but I basically can’t access my store inside the constructor. Using store.getState().auth.token (this is redux boilerplate) fails inside the constructor function, but doesn’t inside, for example, the save function. I can get the state from there, but I cannot when I initialize the instance with the constructor. This just goes back to my inexperience with class components. 

If you have any tips for how something like this could be achieved, it would be much appreciated.

**Comment by ganigeorgiev** [comment]
This depends a lot of when the client is initialized and whether the store is accessable from there.

You can try passing as a constructor argument during initialization, eg. something like this:

```js
import PocketBase, { BaseAuthStore } from "pocketbase";

class CustomAuthStore extends BaseAuthStore {
  constructor(store) {
    super();

    this.store = store;

    // @todo load the token and model from your custom storage of choice...
    this.baseToken = this.store.getState().auth.token;
    this.baseModel = this.store.getState().auth.user; 
  }

  save(token, model) {
    super.save(token, model); // this will save the token and model in the local baseToken and baseModel props

    // this is just an example...
    this.store.setState({ auth: { token: token, user: model } });
  }

  clear() {
    super.clear(); // this will reset the local baseToken and baseModel props

    // this is just an example...
    this.store.setState({ auth: null });
  }
}

// ... fetch the store instance from somewhere ...

const client = new PocketBase("http://127.0.0.1:8090", "en-US", new CustomAuthStore(store));
```

---

But this implies that the store could be updated by the PocketBase client. You can go the other way around, aka. by attaching a listener and updating your redux/app store manually. Something like this:

```js
import PocketBase from "pocketbase";

const client = new PocketBase("http://127.0.0.1:8090");

// initialize the client with your redux store state
client.authStore.save(
  store.getState().auth.token,
  store.getState().auth.user
);

// everytime when the PocketBase client store changes, update the redux store
client.authStore.onChange((token, model) => {
  // (this is just an example; adjust to your specific store update method)
  store.setState({ auth: { token: token, user: model }})
});
```

**Comment by bencreynolds** [comment]
Ah, your second option worked well. Thank you for the information. Here's the code I ended up using, which is located in my Navigator component, which checks for isLoggedIn and hasUserData (profile info like username, firstname, lastname) to progress the navigator past the Auth Stack.

```
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [hasUserData, setHasUserData] = useState(false);

  const reduxModel = useSelector((state) => state.auth.model)
  const reduxToken = useSelector((state) => state.auth.token)

  const initialLoad = () => {

    const checkUserData = (model) => {
      return(model.profile?.firstname?.length > 0 && model.profile?.lastname?.length > 0 && model.profile?.username?.length > 0)
    }
    
    const authModel = JSON.parse(JSON.stringify(client.authStore.model))
    const authToken = JSON.parse(JSON.stringify(client.authStore.token))

    if (authModel && authToken.length > 0) {
      //There is a current auth model found
      console.log('Current Auth Model Found!')
      const currentJwt = parseJwt(authToken)

      //Check if current JWT is valid
      const isValid = client.authStore.isValid

      if (isValid) {
        //JWT is Valid
        console.log('Is Valid!')
        
        //Check if Redux Model/Token are the same as Auth Model/Token
        console.log({
          reduxModel,
          authModel,
          reduxToken,
          authToken
        })
        if (_.isEqual(reduxModel, authModel) && _.isEqual(reduxToken, authToken)) {
          //Check if Redux Token is the same as the Auth Token
            console.log('The Redux Model/Token and Auth Store Model/Token Match!')
            setHasUserData(checkUserData(reduxModel))
            setIsLoggedIn(true)
            //Check if User has User Data
        } else {
            console.log('The Redux Model/Token and Auth Store Model/Token do NOT Match!')
            dispatch(updateModel(authModel))
            dispatch(updateToken(authToken))

            setIsLoggedIn(true)
            setHasUserData(setHasUserData(checkUserData(reduxModel)))
        }
      } else {
        //JWT is not Valid
      }
      
    } else {
      //There is a current auth model found
      console.log('Current Auth Model NOT Found!')

      //Check if there is a Redux Model/Token
      if (reduxModel && reduxToken) {
        //There is a Redux Model/Token
        client.authStore.save(reduxToken, reduxModel)
        setIsLoggedIn(true)
        setHasUserData(true)
      } else {
        //There is not a Redux Model/Token
        setIsLoggedIn(false)
        setHasUserData(false)
      }
      
      //Check if there is a Model/Token in the Redux Store
      
    }

    client.authStore.onChange((token, model) => {
      console.log({model, token})
      // (this is just an example; adjust to your specific store update method)
      dispatch(updateModel(model))
      dispatch(updateToken(token))
    });

  }



  useEffect(() => {
    initialLoad();
  }, [reduxToken, reduxModel])
```

If you don't check for "hasUserData" or equivalent, you can ignore that part of the code. Hopefully this code isn't too bad, lol.

**Comment by ganigeorgiev** [comment]
I'm glad that you were able to make it work.

Just one side note - it may be better to move the `client.authStore.onChange(...)` outside of the `initialLoad()` function in order to avoid accidentally binding multiple times to the same listener in case the effect get triggered more than once.

I'll close the issue for now, but if you are still having difficulties working with the SDK, feel free to comment (or open a new issue) and I'll try to help.

**Comment by bencreynolds** [comment]
Quick question, are JWT's always valid until expiration? As in, if a user logs out and logs in again, does that kill the previous JWT?

**Comment by ganigeorgiev** [comment]
> if a user logs out and logs in again, does that kill the previous JWT?

PocketBase doesn't really have logout because there are no sessions. If you call `client.authStore.clear()` this will just remove the token and auth data from the store.

The JWT token itslef is always valid, unless it is expired OR the user for example has changed their password (we invalidate previously issued tokens on password change).
