### ISSUE TITLE
Android Bundling Failure

### ISSUE THREAD

**Issue by justinorringer** [pocketbase/js-sdk#39]
Hello! We are making a small alarm app for a hackathon using expo/react native. 

You all's package works great on the web build, but for running it in expo go we get an Android Bundling error. Since we are making an alarm app, we need to access the android alarm manager. We have tried modifying the metro.config to no avail (following [these sorts of threads](https://stackoverflow.com/questions/60124435/however-this-package-itself-specifies-a-main-module-field-that-could-not-be-r/60126739#60126739)).

![image](https://user-images.githubusercontent.com/87503474/192002364-c2b429fb-8e7c-4979-858c-b37cb3c0470c.png)

The Login page can be found [here](https://github.com/justinorringer/SleepCycles/blob/main/app/pages/Login.js).

We are planning to work around it with regular api calls, but this nice library would be great to have for similar cases :)

**Comment by ganigeorgiev** [comment]
The error message indicates that `node_modules/pocketbase/dist/pocketbase.es.mjs` doesn't exist for some reason.
Could you verify that the file exist?

Googling the issue I found this that looks similar to the reported error - https://github.com/react-native-camera/react-native-camera/issues/2626:

> Have you checked if the file is in fact there? This normally happens when installing/updating libraries. Just close all your metro bundlers / consoles and start fresh.

**Comment by ganigeorgiev** [comment]
If the above suggestion doesn't work, you could also make sure that expo can load `.mjs` files. Similar issue could be found in https://github.com/portabletext/react-portabletext/issues/6.

I'll close the issue since I don't think we can do anything from our end and it is probably something specific to the local env configuration.

**Comment by ganigeorgiev** [comment]
Just for info since this was recently reported in #47, to allow loading the `.mjs` extension you can create a `metro.config.js` (if you haven't already) and add the extension to the allowed list:

```js
// metro.config.js
const { getDefaultConfig } = require('expo/metro-config');
const config = getDefaultConfig(__dirname);
config.resolver.sourceExts.push('mjs');
module.exports = config;
```
