### ISSUE TITLE
does it work in react native?

### ISSUE THREAD

**Issue by Brunowilliang** [pocketbase/js-sdk#4]
I have a project in react native and I would like to test it

**Comment by ganigeorgiev** [comment]
The JavaScript SDK is implemented on top of [axios](https://github.com/axios/axios), so it should work in browser and node environments (including react native).

Unfortunately, @linktohack has reported an issue with node.js environments in #3 but I still haven't got the time to investigate it more thoroughly.

**Comment by ganigeorgiev** [comment]
The node.js issue is fixed in v0.1.2 release. See the [Installation section](https://github.com/pocketbase/js-sdk#installation) for more details how to load the SDK.
