### ISSUE TITLE
Improvement/Suggestion: Better error handling

### ISSUE THREAD

**Issue by mnorlin** [pocketbase/js-sdk#40]
When working with collections, you need to verify the resolved response and look for errors (eg. HTTP 404).

```js
  client.records.getOne("vault", "o4fq5kwf00amj7x")
    .then((record) => {
      if (record.code == 404) {
        handleError(record)
      }
      else {
        doSomething(record)
      }
    });
```
In my opinion, this is:
1. A bit cumbersome
2. Error-prone, as the expected record could have fields overlapping with the error object (eg. code, message)

## Suggestion 1
An alternative could be that an error rejects the promise, resulting in:
```js
  client.records.getOne("vault", "o4fq5kwf00amj7x")
    .then(doSomething)
    .catch(handleError)
```

This solves both issue **1** and **2** in my opinion, but has the drawback when using async/await syntax, as you would need to wrap everyting in a try/catch

```js
  try {
    const record = await client.records.getOne("vault", "o4fq5kwf00amj7x")
  }
  catch(e) {
    handleError(e)
  }
```

## Suggestion 2
another approach, could be something similar to Svelte Query (https://sveltequery.vercel.app/guides/queries), that you always return the same type of object, wrapping the returned data:

```js
  const result = await client.records.getOne("vault", "o4fq5kwf00amj7x")
  
  result.code // always present, on success, a 200, on error 404
  result.error // an error object (message, data)
  result.data // the expected record
```
This does not really solve issue **1**, but it does prevent possible errors in user code.

**Comment by ganigeorgiev** [comment]
@mnorlin The first example is incorrect. On any response with status code >= 400 the SDK throws a `ClientResponseError` exception (see https://github.com/pocketbase/js-sdk#errors-handling), aka. **we currently implement "Suggestion 1"**.

I don't agree with Suggestion 2, since it is non-idiomatic JS. In JS errors are usually thrown and not returned as value. In addition, Suggestion 2 also doesn't work well when the Promise based syntax is used because now you have to check for errors in 2 places - once in the `then()` callback and once in the `catch()` (in case something else has thrown in `then()`).

**Comment by ganigeorgiev** [comment]
@mnorlin Just tested it and I cannot reproduce your first example. I'm not sure how you were able to access the error response object within the `then` callback. Or in other words, the following should work:

```js
client.records.getOne("vault", "o4fq5kwf00amj7x").catch((err) => {
    console.log(err)
})
```

Here is the code where we throw and wrap the response errors - https://github.com/pocketbase/js-sdk/blob/master/src/Client.ts#L306-L318.

If the above doesn't work for you, feel free to let me know and I'll try investigate it further.

**Comment by mnorlin** [comment]
This is actually an error on my part, I only read the documentation in the "Preview API" in PocketBase, which does not mention the `ClientResponseError`. I should have done a more thorough read of your docs, and maybe tested my simple example before posting this issue... Thanks for the quick reply, and keep up the amazing work!
