### ISSUE TITLE
unable to create a record even if authenticated

### ISSUE THREAD

**Issue by rajesh6161** [pocketbase/js-sdk#44]
using this API rule in create record: @request.user.id!=""

**Comment by rajesh6161** [comment]
Getting this reponse each time:
{"code":400,"message":"Failed to create record.","data":{}}

**Comment by ganigeorgiev** [comment]
Could you provide a code sample how you send the request?

You can check in the Admin UI > Logs the failed request for more detailed errors (or start the executable with `--debug` to log the error in the console).

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce the error:

```js
client.records.create("test", { someField: "test123" });
```

How are you sending the request?

**Comment by rajesh6161** [comment]
try {
      const record = await client.records.create('demo', {
        title: 'Test',
        empID: 123,
      });
      console.log(record);
    } catch (e) {
      console.error(e);
    }
this is how I sending the data.
API rule: @request.user.id != ""

**Comment by ganigeorgiev** [comment]
I've just tested it both locally and on the live demo and I'm not able to reproduce it.
Are you sure that you are authenticated? Could you try temporary removing the API rule and see if you can submit the request?

**Comment by rajesh6161** [comment]
@ganigeorgiev I can create a record if there's none API rule but if I put the API rule and authenticate I can't create plus its not giving proper error response
and if token isn't there its still giving same response:
```
{"code":400,"message":"Failed to create record.","data":{}}
```

**Comment by rajesh6161** [comment]
I can create a record without API rule

**Comment by ganigeorgiev** [comment]
The error reporting could definitely can be improved (I'll update it in v0.8) but I'm not able to reproduce your issue.

I'm doing the following:

```js
const client = new PocketBase("http://localhost:8090");

await client.users.authViaEmail("test@example.com", "123456789");

await client.records.create("demo", { title: "123" });
```

**Comment by rajesh6161** [comment]
let me try it again with fresh collection

**Comment by rajesh6161** [comment]
Getting same error @ganigeorgiev

**Comment by ganigeorgiev** [comment]
> is that an issue with unverified email?

No. Its up to the developers whether they want to allow unverified users to have access to the collection. If your create API rule is only:

```
@request.user.id != ""
```
then this allow every registered user. To allow only registered and verified users, your API rule should look something like this:

```
@request.user.id != "" && @request.user.verified = true
```

---

> Getting same error @ganigeorgiev

I don't know how to reproduce it. I've create a demo collection with create rule `@request.user.id != ""` and with the following js call:

```js
const client = new PocketBase("http://localhost:8090");

await client.users.authViaEmail("test@example.com", "123456789");

await client.records.create("demo", { title: "123" });
```

What version of the JS SDK and PocketBase are you using?

**Comment by rajesh6161** [comment]
@ganigeorgiev Hey 👋 thanks for the support man! I figured it out by by your last comment. As I was not exporting the token in cookie, I was getting errors.
Thanks! it work now.
