### ISSUE TITLE
RealtimeDB having issues

### ISSUE THREAD

**Issue by rajesh6161** [pocketbase/js-sdk#45]
```
import PocketBase from 'pocketbase';
import { useEffect, useState } from 'react';

function App() {
  const client = new PocketBase('http://127.0.0.1:8090');
  const [data, setData] = useState({});
  const [title, setTitle] = useState('');

  useEffect(() => {
    client.realtime.subscribe('sample/36p2v9dpch3p1rf', function (e) {
      console.log('realtime', e.record);
      setData(e.record);
    });
  });
  const getData = async () => {
    const record = await client.records.getOne('sample', '36p2v9dpch3p1rf');
    setData(record);
  };

  const updateData = async () => {
    await client.records.update('sample', '36p2v9dpch3p1rf', { title: title });
  };
  useEffect(() => {
    getData();
  }, []);

  client.realtime.unsubscribe('sample/36p2v9dpch3p1rf');
  return (
    <div className="App">
      <h1>My App</h1>
      <p>
        {data.title}
        {'   '}
        <b>{data.id}</b>
      </p>
      <input
        type="text"
        placeholder="Update Data"
        onChange={(e) => setTitle(e.target.value)}
      />
      <button onClick={updateData}>Update</button>
    </div>
  );
}

export default App;

```
This is my simple code for testing the realtime DB, and I am facing an issue here, that is I can only update the data in realtime once and I need to refresh the page to again update the data.
But in case of Dashboard of pocetbase I can update the data and it reflects instantly on the client side. Why is this so?

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand the above code (I'm not much familiar with react either).

Why do you need to wrap `client.realtime.subscribe` in  a `useEffect`? Wouldn't that register a new listener every time the effect get triggered?

Additionally, you have `client.realtime.unsubscribe` right before the jsx template. Is this intended?

**Comment by rajesh6161** [comment]
1. I wrapped `client.realtime.subscribe` in a `useEffect` because its not getting triggered, so I thought of running it continuously, so that it listens to the changes.
2. Should I not unsubscribe?

**Comment by rajesh6161** [comment]
Without wrapping the `client.realtime.subscribe` in useEffect it is not registering for new listeners.

**Comment by rajesh6161** [comment]
And it works perfectly when triggered any changes from the pocketBase dashboard

**Comment by ganigeorgiev** [comment]
> Without wrapping the client.realtime.subscribe in useEffect it is not registering for new listeners.

Thats because you are unsubscribing. When you wrap in useffect it probably attach a new subscriptions after that call.
Unwrap the subscription from the use effect and remove the unsubscribe call.

If you want to unsubscribe on component unmount you can return a destroy function to the useEffect hook, eg. something like:

```js
useEffect(() => {
  // executed when the component unmounts
  return () => {
    client.realtime.unsubscribe();
  };
});
```

**Comment by rajesh6161** [comment]
@ganigeorgiev thanks buddy! I got the idea, it works now 🎊

**Comment by rajesh6161** [comment]
I am making a good project using Pocketbase, which can server as tutorial for other learners.
