### ISSUE TITLE
why is it throwing error even if correct user field is sent in the request

### ISSUE THREAD

**Issue by rajesh6161** [pocketbase/js-sdk#46]
I have created a collection as follows:
field  type
title - text, content - text, imgurl - URL, user - usertype

My Request:
`{"title":"test","content":"contents","imgurl":"https://images.freeimages.com/images/large-previews/256/spring-1376144.jpg","user":{"id":"7cfcsyq777bzv1d","created":"2022-10-09 16:23:04.149","updated":"2022-10-09 16:23:04.149","email":"hello@gmail.com","verified":false,"lastResetSentAt":"","lastVerificationSentAt":"","profile":{"id":"f17g1qtdan7nfgh","created":"2022-10-09 16:23:04.149","updated":"2022-10-09 16:23:04.149","@collectionId":"systemprofiles0","@collectionName":"profiles","avatar":"","name":"","userId":"7cfcsyq777bzv1d","@expand":{}}}}`

Server Response:
`{"code":400,"message":"Failed to create record.","data":{"user":{"code":"validation_required","message":"Missing required value."}}}`

what is wrong with the `user` field?

**Comment by ganigeorgiev** [comment]
You have to pass only the user id, not the whole object. Or in other words, your request body should be:

```js
{
    "title": "test",
    "content": "contents",
    "imgurl": "https://images.freeimages.com/images/large-previews/256/spring-1376144.jpg",
    "user": "7cfcsyq777bzv1d"
}
```

**Comment by ganigeorgiev** [comment]
I'll close the issue since I've tested it locally and it works as expected when the user id is provided (we also have integration and unit tests for each field types).
