### ISSUE TITLE
authStore.onChange missing types for TypeScript

### ISSUE THREAD

**Issue by Ti7oyan** [pocketbase/js-sdk#50]
I'm working on a web app that needs to refresh the authenticated model to reflect changes on profile's update (for example, when verifying, changing profile picture and username) but the `authStore.onChange` doesn't match the example detailed in the SDK's readme, because even if the `onChangeCallbacks` array accepts only functions that follow the pattern
```ts
(token: string, model: User|Admin|null) => void 
```
The method provided by the BaseAuthStore's class requires an `() => void` callback, making it difficult to work with it.

https://github.com/pocketbase/js-sdk/blob/f575bd23d762a6af0ff736c0c6a86619f5937188/src/stores/BaseAuthStore.ts#L146

Taking in consideration that the SDK is almost entirely typed, this minor change would be beneficial for the codebase.

**Comment by ganigeorgiev** [comment]
This is already changed in https://github.com/pocketbase/js-sdk/pull/43. Sometime later today I'll update the tests related to the PR and will push a minor release.

**Comment by Ti7oyan** [comment]
Great! Thank you 🙏
