### ISSUE TITLE
This does not work with nest js

### ISSUE THREAD

**Issue by DenisVASI9** [pocketbase/js-sdk#52]
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/hermione/cd-market-backend/node_modules/pocketbase/dist/pocketbase.es.mjs not supported.
Instead change the require of /home/hermione/cd-market-backend/node_modules/pocketbase/dist/pocketbase.es.mjs to a dynamic import() which is available in all CommonJS modules.

**Comment by ganigeorgiev** [comment]
I'll test it later today with nest, but most likely this a transpiler (eg. TypeScript) misconfiguration, so make sure that your nest project can load ES modules.

The easiest workaround for your error would be to load the CommonJS PocketBase bundle like:

```
const PocketBase = require('pocketbase/cjs');
```

The above should work because it is a native CommonJS module.

**Comment by DenisVASI9** [comment]
This kind of connection will work, but will block eslint. It doesn't look uniform. I tried to fix it, but my skills are lacking.

**Comment by ganigeorgiev** [comment]
@DenisVASI9 i'm not sure that I understand what do you mean by _" but will block eslint"_.

PocketBase is ESM by default. The legacy CJS bundle is `pocketbase/cjs`.

**If you want to use CommonJS, use `pocketbase/cjs`. There is no other way around without extra configuration.**

The error indicates that you are using `import` statements with CommonJS and this is "wrong" since it is just a syntax sugar. What actually is happening under the hood is that TypeScript (or whatever other transpiler you are using) based on the error is generating a plain js file and converts your `import ....` statements to `require(...)` (you can inspect the generated nest js files in your `/dist` folder). This will not work with PocketBase (or any other ESM library).

Currently nestjs doesn't seem to support ESM by default (see https://github.com/nestjs/nest/issues/10267#issuecomment-1243065177, https://github.com/nestjs/nest/pull/8736, etc.). If you want to use ES modules without the hacky interop, you'll have to:

1. Add in you `package.json` the following line:
   ```js
   "type": "module",
   ```

2. Enable `esnext` in your `tsconfig.json` under the `compilerOptions`, eg.:
    ```js
    "module": "esnext",
    "moduleResolution": "node",
    "target": "esnext",
    ...
    ```
    _(you can learn more about the available module resolution strategies in https://www.typescriptlang.org/docs/handbook/module-resolution.html#module-resolution-strategies)_


3. Add `.js` suffix to all your **local** file imports, for example:
    ```js
    import { AppModule } from './app.module';
    // change to 
    import { AppModule } from './app.module.js';
    ```
    
In any case, this is not related to PocketBase and you'll stumble on the same error if you try to import any other ESM package.

**Comment by DenisVASI9** [comment]
Thank you!

**Comment by DenisVASI9** [comment]
@ganigeorgiev 
I have that error with "pocketbase/cjs": TS2307: Cannot find module 'pocketbase/cjs' or its corresponding type declarations.

**Comment by ganigeorgiev** [comment]
@DenisVASI9 What option did you end up using? `require("pocketbase/cjs")` or you've decided to go with the ESM route?

Once again, this is not related to the SDK and I'm not sure how to help without any information on your setup (eg. `tsconfig.json`) and how you are loading the library.

My advice would be to apply the listed 3 steps from above and start using ESM and import the SDK just by:
```js
import PocketBase from "pocketbase";
```
_If you want to allow loading other CJS modules with ESM you can also add `"esModuleInterop": true,` to your tsconfig `compilerOptions`._

**Comment by DenisVASI9** [comment]
@ganigeorgiev I've been using import PocketBase from "pocketbase/cjs". 
I was hoping to use cjs without changing the nest tranpiler settings.
Yes, I understand that this is not an sdk problem.
Thank you for your time.

**Comment by DenisVASI9** [comment]
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "Node",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "lib": ["ESNext"],
    "target": "ESNext",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "strict": true,
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": true,
    "noImplicitAny": true,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}

**Comment by ganigeorgiev** [comment]
@DenisVASI9 You can use `import PocketBase from "pocketbase/cjs"` only if you change your `moduleResolution` to `nodenext` (there is an open issue for that in the TypeScript repo - https://github.com/microsoft/TypeScript/issues/50794). Or in other words, you could try changing your tsconfig to:

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "nodenext",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "lib": ["ESNext"],
    "target": "ESNext",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "strict": true,
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": true,
    "noImplicitAny": true,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}
```

**Comment by ArjunAtlast** [comment]
Hi, in case someone is stuck with this issue -  I was able to do an unorthodox fix for this issue using `eval`. This method is explained in a StackOverflow answer. Attaching the link to the answer as well.

[Compile a package that depends on ESM only library into a CommonJS package](https://stackoverflow.com/a/70546326)

This is my code for a NestJS Service class with pocketbase instance as a property:
```ts
import { Injectable, OnModuleDestroy, OnModuleInit } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import { Cron, CronExpression } from "@nestjs/schedule";
import type Pocketbase from "pocketbase";

@Injectable()
export class PocketbaseService implements OnModuleInit, OnModuleDestroy {
  private _client: Pocketbase;

  constructor(
    private readonly config: ConfigService
  ) {}

  get client() {
    return this._client;
  }

  async onModuleInit() {
    // create client
    const pocketbase = await (eval(`import('pocketbase')`) as Promise<typeof import('pocketbase')>);
    const PocketbaseClass = pocketbase.default;
    this._client = new PocketbaseClass(this.config.get('POCKETBASE_URL'));
    // login as admin
    await this.client.admins.authWithPassword(this.config.get('POCKETBASE_ADMIN_EMAIL'), this.config.get('POCKETBASE_ADMIN_PASSWORD'));
  }

  async onModuleDestroy() {
    // logout
    this.client.authStore.clear();
  }

  @Cron(CronExpression.EVERY_5_MINUTES)
  async reAuth() {
    // re-authenticate every 5 minutes
    await this.client.admins.authRefresh();
  }
}
```

**Comment by laravellously** [comment]
> Hi, in case someone is stuck with this issue - I was able to do an unorthodox fix for this issue using `eval`. This method is explained in a StackOverflow answer. Attaching the link to the answer as well.
> 
> [Compile a package that depends on ESM only library into a CommonJS package](https://stackoverflow.com/a/70546326)
> 
> This is my code for a NestJS Service class with pocketbase instance as a property:
> 
> ```ts
> import { Injectable, OnModuleDestroy, OnModuleInit } from "@nestjs/common";
> import { ConfigService } from "@nestjs/config";
> import { Cron, CronExpression } from "@nestjs/schedule";
> import type Pocketbase from "pocketbase";
> 
> @Injectable()
> export class PocketbaseService implements OnModuleInit, OnModuleDestroy {
>   private _client: Pocketbase;
> 
>   constructor(
>     private readonly config: ConfigService
>   ) {}
> 
>   get client() {
>     return this._client;
>   }
> 
>   async onModuleInit() {
>     // create client
>     const pocketbase = await (eval(`import('pocketbase')`) as Promise<typeof import('pocketbase')>);
>     const PocketbaseClass = pocketbase.default;
>     this._client = new PocketbaseClass(this.config.get('POCKETBASE_URL'));
>     // login as admin
>     await this.client.admins.authWithPassword(this.config.get('POCKETBASE_ADMIN_EMAIL'), this.config.get('POCKETBASE_ADMIN_PASSWORD'));
>   }
> 
>   async onModuleDestroy() {
>     // logout
>     this.client.authStore.clear();
>   }
> 
>   @Cron(CronExpression.EVERY_5_MINUTES)
>   async reAuth() {
>     // re-authenticate every 5 minutes
>     await this.client.admins.authRefresh();
>   }
> }
> ```

Worked perfectly. Thanks.

**Comment by adebisi-fa** [comment]
> Hi, in case someone is stuck with this issue - I was able to do an unorthodox fix for this issue using `eval`. This method is explained in a StackOverflow answer. Attaching the link to the answer as well.
> 
> [Compile a package that depends on ESM only library into a CommonJS package](https://stackoverflow.com/a/70546326)
> 
> This is my code for a NestJS Service class with pocketbase instance as a property:
> 
> ```ts
> import { Injectable, OnModuleDestroy, OnModuleInit } from "@nestjs/common";
> import { ConfigService } from "@nestjs/config";
> import { Cron, CronExpression } from "@nestjs/schedule";
> import type Pocketbase from "pocketbase";
> 
> @Injectable()
> export class PocketbaseService implements OnModuleInit, OnModuleDestroy {
>   private _client: Pocketbase;
> 
>   constructor(
>     private readonly config: ConfigService
>   ) {}
> 
>   get client() {
>     return this._client;
>   }
> 
>   async onModuleInit() {
>     // create client
>     const pocketbase = await (eval(`import('pocketbase')`) as Promise<typeof import('pocketbase')>);
>     const PocketbaseClass = pocketbase.default;
>     this._client = new PocketbaseClass(this.config.get('POCKETBASE_URL'));
>     // login as admin
>     await this.client.admins.authWithPassword(this.config.get('POCKETBASE_ADMIN_EMAIL'), this.config.get('POCKETBASE_ADMIN_PASSWORD'));
>   }
> 
>   async onModuleDestroy() {
>     // logout
>     this.client.authStore.clear();
>   }
> 
>   @Cron(CronExpression.EVERY_5_MINUTES)
>   async reAuth() {
>     // re-authenticate every 5 minutes
>     await this.client.admins.authRefresh();
>   }
> }
> ```

This is gold! Worked so perfectly.  Thank you.
PS: Node must be at 16+.
