### ISSUE TITLE
Getting ClientResponseError even though response is 200

### ISSUE THREAD

**Issue by kidus-tiliksew** [pocketbase/js-sdk#55]
I'm executing this simple query in a function with React

`const contactNumber = await PocketBaseClient.records.getOne(
          'contact_points',
          organization.telecom
        );
  `

Looking at the network call as well as the Request logs in the admin, the response is 200 and I do get correct results, but it throws ClientResponseError

Following are screenshots of the error and network call respectively 

[https://drive.google.com/file/d/11ax2L7hJuD3yXvy5hA5u6IuvKRfBpSTC/view?usp=sharing](url)
[https://drive.google.com/file/d/1-5XR-np4brJkj2pFkmt_SlAxdUZFeQzA/view?usp=sharing](url)

**Comment by ganigeorgiev** [comment]
"ClientResponseError 0" indicates that this is most likely a result of autocancellation of pending requests, aka. this means that your react function is triggered multiple times before waiting the previous request to complete (or the same request is executed by some other component).

Autocancellation is a mechanism to prevent async bugs in userland code, but if you don't want this behavior you can disable it by passing `'$autoCancel': false` as query paramer, eg:

```js
const contactNumber = await PocketBaseClient.records.getOne( 'contact_points', organization.telecom, { '$autoCancel': false });
```

In the next SDK version there will be also a helper to disable it globally. More info on autocancellation could be found in https://github.com/pocketbase/js-sdk#auto-cancellation.
