### ISSUE TITLE
not working, authStore.onChange function, users.refresh() call after.

### ISSUE THREAD

**Issue by heoyongun** [pocketbase/js-sdk#58]
The Auth refresh function is called.

The authStore.onChange function does not recognize it.

node v18
pocketbase sdk : "^0.7.3"

![스크린샷, 2022-11-02 10-11-48](https://user-images.githubusercontent.com/6076067/199371495-e9e0bde0-5a1e-4a50-8f8f-acfc6cb49317.png)

**Comment by ganigeorgiev** [comment]
@heoyongun You have to register the `onChange` listener before the refresh call.
