### ISSUE TITLE
Wrong property name in example on https://pocketbase.io/

### ISSUE THREAD

**Issue by Lex-2008** [pocketbase/js-sdk#6]
Thanks for a nice project!

I did a quick "realtime chat" app based on this, in 20 lines of javascript, just by copypasting examples from main page of https://pocketbase.io/!

However, one example seems to be incorrect. It says:
````
// subscribe to changes in any record from the "demo" collection
client.Realtime.subscribe("demo", function (e) {
    console.log(e.data);
});
````

While in my experience, the `e` argument didn't have a `data` property - instead, I used `record` property to get the new/modified record, like this:
```
client.Realtime.subscribe("messages", (e)=>{addMessage(e.record)});
```

**Comment by ganigeorgiev** [comment]
Yes, that's correct. The callback argument has `action` (create, update, delete) and `record` property.

I'll update the examples.

**Comment by ganigeorgiev** [comment]
The typos are fixed in the latest release.
