### ISSUE TITLE
Error in documentation - missing ','

### ISSUE THREAD

**Issue by PeterAlfonsLoch** [pocketbase/js-sdk#60]
In the documentation there is an example:

```js
const pageResult = await client.logs.getRequestsList(1, 20, {
    filter: 'status >= 400'
    sort: '-created'
```

it is missing a comma:
```js
const pageResult = await client.logs.getRequestsList(1, 20, {
    filter: 'status >= 400', //here
    sort: '-created'
```

Site in question: https://pocketbase.io/docs/api-logs under 'List request log'.

**Comment by ganigeorgiev** [comment]
Thank you. I've fixed it locally. It will be available with the new documentation changes for the upcoming v0.8.0 release.
