### ISSUE TITLE
Error 400 "ClientResponseError 400: Failed to authenticate." but still works - Next.JS

### ISSUE THREAD

**Issue by PeterAlfonsLoch** [pocketbase/js-sdk#61]
### Issue:
When hardcoding the e-mail and password for authentication it works without error. But when using enviroment variables it throws an error but is still able to fetch the data.

### Provided information:
Marked in red is the wanted results:
<img width="748" alt="Bildschirm­foto 2022-11-02 um 14 06 04" src="https://user-images.githubusercontent.com/2743562/199502747-5a470b95-b2ce-4d30-9b04-2c6d8034df87.png">
Thus it works, but it still throws an error. O.o

code:
```js
...
const client = new PocketBase('https://example.com');
const adminAuthData = await client.admins.authViaEmail(process.env.USERNAME, process.env.PASSWORD);
console.log(adminAuthData);
const resultList = await client.records.getList('forums', 1, 50, {
  filter: 'created >= "2022-01-01 00:00:00"',
});
...
<div>
        {resultList.items.map((item, i) => (
                <div key={i}>
                  // Show all things which you want
                  <br/>
                  {i}
                  <br/>
                  {item.title}
                  <br/>
                  {i}
                  <br/>
                  {item.description}
                </div>
            ))
        }
      </div>
```

### Temporary solution idea i tried:
catching the error and ignoring it, but this could lead to a later issue where authentication actually does not work and I would not get the necessary error.

### Result of temporary fix idea:
~~Yet this just shoves the const variable out of scope and nothing works~~
As it is a promise i made it ignore the error with:
```js
const adminAuthData = await client.admins.authViaEmail(process.env.USERNAME, process.env.PASSWORD).catch((error) =>{});
````
I do not like this temprorary solution because of the mentioned probable issue later on.

**Comment by ganigeorgiev** [comment]
I don't think this is related to the SDK.

I assume you execute the above in a server-side action, right?
Are you sure that you have access to the env variables?
You could add  a `console.log` right before the call and check if their value is correct and non empty.

Additionally, if the action is triggered multiple times, before the previous request was able to complete, make sure that auto cancellation is not triggered - https://github.com/pocketbase/js-sdk#auto-cancellation (but I doubt that this is the case here because the status code would be 0).

**Comment by PeterAlfonsLoch** [comment]
> I don't think this is related to the SDK.
> 
> I assume you execute the above in a server-side action, right? Are you sure that you have access to the env variables? You could add a `console.log` right before the call and check if their value is correct and non empty.
> 
> Additionally, if the action is triggered multiple times, before the previous request was able to complete, make sure that auto cancellation is not triggered - https://github.com/pocketbase/js-sdk#auto-cancellation (but I doubt that this is the case here because the status code would be 0).

I did that, and it works as intended. As shown in the screenshot it does show what I called for but still throws an error. Only when hard coding there is no error. In both cases the data gets retrieved from the database. So the error is show even tho it works. According to the logs it just sends out a code 400.

The enviroment variables can be read before the call.
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/2743562/199510550-9c907bda-40e1-4ae4-a28c-aef60614594b.png">

### Code used:
```js
console.log("username:" + process.env.USERNAME);

const client = new PocketBase('https://backend.saachen.lu');
const adminAuthData = await client.admins.authViaEmail(process.env.USERNAME, process.env.PASSWORD).catch((error) =>{console.log("It be a feature")});
```

**Comment by PeterAlfonsLoch** [comment]
> I'm not sure how to reproduce it.
> 
> It is also possible that the above is executed in both server-side and client-side (where you probably don't have access to the variables) depending on where it is located in your react/next.js code. Could you provide a minimal repo where this could be reproduced?

I do not have a repo as I am only experimenting right now. PocketBase is running in a docker on my plesk and the files are all local. But why would it run twice? The local webserver gets called.

I used a fresh next.js app and only added pocketbase via npm and added the mentioned lines.

### Exact part that was changed in index.js:
```js
import PocketBase from 'pocketbase'
import styles from '../styles/Home.module.css'

console.log("username:" + process.env.USERNAME);

const client = new PocketBase('https://backend.saachen.lu');
const adminAuthData = await client.admins.authViaEmail(process.env.USERNAME, process.env.PASSWORD).catch((error) =>{console.log("It be a feature")});
//console.log(adminAuthData);
const resultList = await client.records.getList('forums', 1, 50, {
  filter: 'created >= "2022-01-01 00:00:00"',
});
//console.log(resultList);

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>hihi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*{console.log(adminAuthData)}*/}
      <div>
        {resultList.items.map((item, i) => (
                <div key={i}>
                  // Show all things which you want
                  <br/>
                  {i}
                  <br/>
                  {item.title}
                  <br/>
                  {i}
                  <br/>
                  {item.description}
                </div>
            ))
        }
      </div>
```

I will build it and try on my webserver.

**Comment by ganigeorgiev** [comment]
@PeterAlfonsLoch The above code will execute twice - once in your node-server and second time in the browser (to verify add a `console.log('hello')` and open the browser console).

You have to wrap it in a server-only handler.

**Comment by PeterAlfonsLoch** [comment]
You are right.

In my eagerness to get to use pocketbase I did not correctly use my brain. I am sorry to have wasted your time.
