### ISSUE TITLE
Issues with Node 17/18

### ISSUE THREAD

**Issue by apikee** [pocketbase/js-sdk#62]
Hello, I ran into a problem with node in both version 17 and 18. When I try to send any request through SDK I get this error (see screenshot). Of course I am using all the polyfils that are mentioned in the README. As soon as I downgraded the Node version to 16, everything started working. Have you encountered this before? I'm on a Mac M1. Thanks.
<img width="937" alt="Screenshot 2022-11-02 at 22 51 05" src="https://user-images.githubusercontent.com/88746971/199609400-859adae8-4557-4909-8cc2-2dad0d8c8f97.png">

**Comment by ganigeorgiev** [comment]
I believe this is the same as in https://github.com/pocketbase/js-sdk/issues/21.

Try to change your the `localhost` address to `127.0.0.1` in your node application.
You could find a little more details in the above issue, but in short - Node 17+ has different dns resolver and prioritize the ipv6 address (eg. converts localhost -> ::1), while in Go, the dns resolver will return first ipv4 address (aka. `127.0.0.1`). That's also the reason why in all examples we are now using `127.0.0.1`.

**Comment by apikee** [comment]
@ganigeorgiev  You are obviously right, thanks for quick reaction!
