### ISSUE TITLE
Not able to set return type

### ISSUE THREAD

**Issue by SanderCokart** [pocketbase/js-sdk#66]
# Problem
So in this image you can see that the return type of getList for example is always `<ListResult<Record>` with the inability to set the record to something else e.g:
```ts
type PricesRecord = {
	tag: string
	price: number
	name: string
	description?: string
}
```

We need generics.

![image](https://user-images.githubusercontent.com/45256817/200056693-7e984d18-cc4e-4682-b0f2-dadeabdb6e5c.png)

**Comment by SanderCokart** [comment]
Workaround: 

```ts
    return await db.records.getList(Collections.Prices) as unknown as PricesRecord[];
```

**Comment by ganigeorgiev** [comment]
You can check this issue with other workarounds for v0.7.x- https://github.com/pocketbase/js-sdk/issues/38.

Support for generics was already added in the latest [v0.8.0-rc release](https://github.com/pocketbase/js-sdk/releases/tag/v0.8.0-rc1).
You could check the readme in the `rc` branch for examples and more specifically - https://github.com/pocketbase/js-sdk/tree/rc#custom-record-types

_Stable v0.8.0 will be available within the next 1-2 weeks._
