### ISSUE TITLE
What does the user of bang operator on member variables accomplish?

### ISSUE THREAD

**Issue by gamedevsam** [pocketbase/js-sdk#67]
I haven't seen this syntax before, mind explaining what it accomplishes?

https://github.com/pocketbase/js-sdk/blob/d3704619fb7b03f31c2bd6872f392a6bca083987/src/models/User.ts#L5

**Comment by ganigeorgiev** [comment]
This is a _definite assignment assertion_. You could find more info about it in https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#definite-assignment-assertions.

In short, it tells the TS checker that this variable is not `undefined` and will have an assigned value (eg. probably defined inside a constructor or factory function(s)).

**Comment by gamedevsam** [comment]
Ahh now I understand, without it TS expects all vars to be initialized in the constructor, otherwise it errors out. Thanks for the explanation!
