### ISSUE TITLE
Suggestion : make record.getOne() able to filter over other fields than id 

### ISSUE THREAD

**Issue by Mathys-Rituper** [pocketbase/js-sdk#68]
Hi,

The current prototype of the `record.getOne` methods only allows filtering over the ID only since it is a mandatory parameter of the function, however one might want to use this function with another unique & required field of the collection, for example a slug, but doing so is currently impossible with `record.getOne`.

One workaround I found was to use `record.getFullList()` with a filter on the desired field, but it seems kind of counter-intuitive and imperfect to use the method that queries the whole collection and is expected to return multiple results when you actually want a single record. This workaround also causes a problem when someone wants to set different permissions on the `list` and `view` actions on the API for their collection but is forced to use `record.getMultiple` to compensate for the limitation of the current implementation of `record.getOne`.

I would therefore suggest changing the signature + implementation of the `record.getOne` function or adding a new one to give users an option to allow for searching over other unique+required fields than the id of the record.

Thanks in advance for your consideration ! :)

**Comment by ganigeorgiev** [comment]
In the upcoming v0.8.0 there is a new helper `getFirstListItem(filter, queryParams = {})` that could be used for fetching the found found record matching the filter. As the name suggest, the above for now works only with the "List API rule".

Please note that v0.8.0 will have some breaking changes and will work only with PocketBase v0.8+. You can check the `rc` branch with the updated records methods in https://github.com/pocketbase/js-sdk/tree/rc#recordservice.

SDK changelog with the future changes could be found in https://github.com/pocketbase/js-sdk/blob/rc/CHANGELOG.md.

**Comment by goknsh** [comment]
Why is `filter` required in `getFirstListItem`?

**Comment by ganigeorgiev** [comment]
@goknsh Because that's most likely how people most likely are going to use it, otherwise the returned record from the collection will be arbitrary and you'll rely on whatever is the first row in the db query `select * from yourCollection limit 1;`.

In the rare cases where you don't need a filter and don't care what record is returned, you can use just `getList(1, 1)`

**Comment by goknsh** [comment]
Completely unrelated, but is there a way to do `COUNT(*)`, other than using `getList(1, 1)` and using `totalItems`'s value?

**Comment by ganigeorgiev** [comment]
@goknsh Aggregation queries at the moment can be performed only if you use PocketBase as framework and using the `app.Dao()` service - https://pocketbase.io/docs/db-queries/ (there will be more detailed documentation with the v0.8.0 release).

Eventually in the future we may add support for readonly computed collection fields that will allow you to run SQL statements like count, concatenations across multiple fields, etc. (you can watch this issue - https://github.com/pocketbase/pocketbase/issues/311).
