### ISSUE TITLE
Export `RecordSubscription`

### ISSUE THREAD

**Issue by benallfree** [pocketbase/js-sdk#73]
I noticed this one wasn't exported, but it would be nice to use for callback param typing when building wrappers around realtime subscriptions.

**Comment by ganigeorgiev** [comment]
Hm, it should be already exported https://github.com/pocketbase/js-sdk/blob/rc/dist/pocketbase.es.d.ts#L408.

I guess you may need to import as "type" style import because it is not a JS object but only a TS interface/type, eg.:

```js
import type { RecordSubscription } from "pocketbase";

let sub: RecordSubscription;
```

**Comment by ganigeorgiev** [comment]
My mistake, it is not exported (the export statement is at the bottom of the definition file).
It needs to be registered also in https://github.com/pocketbase/js-sdk/blob/rc/src/index.ts.

I've also just learned that in newer TS version you can also do the type import in a single line:
```js
import PocketBase, { type RecordSubscription } from "pocketbase";
```

I'll export the types before the final v0.8.0 release (_most like the end of the next week_).

**Comment by karniv00l** [comment]
Why we're here, would you also consider exporting following types?

```ts
AuthProviderInfo
AuthMethodsList
```
and maybe for the function `authWithOAuth2` (argument `provider`) we could have some kind of type (could be an enum)

**Comment by ganigeorgiev** [comment]
I've added the types to the exports list in the latest [v0.8.0-rc3 release](https://github.com/pocketbase/js-sdk/releases/tag/v0.8.0-rc3).

About the enum for the `authWithOauth2` provider parameter - for now I left as a `string`, because defining it as enum will require an SDK update on every new OAuth2 provider.
