### ISSUE TITLE
Unclear on how to expand relationships

### ISSUE THREAD

**Issue by mkhatib** [pocketbase/js-sdk#75]
Pocketbase seems to support expand field to expand relationships when viewing or listing records. I am not sure if I am using it right but here's my setup:

galleries (has many sections)
sections (belongs to one gallery) (has gallery_id relation field)
This is how I tried viewing the gallery record with sections expanded in the response:
```
  const pb = new PocketBase("http://127.0.0.1:8090/");
  const data = await pb.records.getOne(
    "galleries",
    context.params!.id as string,
    {
      page: 1,
      perPage: 100,
      expand: "sections,sections.gallery_id, sections.gallery, gallery.sections",
    }
  );
```
None of these worked. @expand field still comes empty. Am I using this correctly or is expand suppose to work on the reverse relationship. Like it would expand a gallery inside a section but not vice versa??

**Comment by Samuelseidelc2518** [comment]
Check the collections settings into API Rules for permissions. Make sure that you have permission for listing for the main collection, and the collections that are used for the expand.

**Comment by ganigeorgiev** [comment]
@mkhatib There will be more documentation on this with the upcoming v0.8.0 release, but when expanding relations:

- you need to use the relation field name, not the collection name (aka. in your case that would be `sections.gallery_id`)
- as the other users suggested, make sure that you have **View API Rule** access for each expanded relation.

**Comment by ganigeorgiev** [comment]
@mkhatib On second read, when you said:

> Like it would expand a gallery inside a section but not vice versa??

Do you mean that you don't have a relation field in the `galleries` collection pointing to `sections`? If that's the case then you'll have to use "Indirect expansion" but this is supported only in PocketBase v0.8.0-rc (stable v0.8.0 will be available next week). You can find more info in https://github.com/pocketbase/pocketbase/issues/312#issuecomment-1242893496.

**Comment by ganigeorgiev** [comment]
@mkhatib With the v0.8.0 release there is now more documentation and examples how to expand relations in https://pocketbase.io/docs/expanding-relations/.

**Comment by mkhatib** [comment]
THank you so much! This works really well!
