### ISSUE TITLE
"Files upload and handling" should mention how to edit (replace) uploaded files

### ISSUE THREAD

**Issue by Lex-2008** [pocketbase/js-sdk#8]
I'm talking about this page: https://pocketbase.io/docs/files-handling/.

I would suggest adding a section about "Editing files" explaining that you can use "client.Records.update" with "formData", just like "client.Records.create". Yes, it's mentioned in the very beginning under the first screenshot, but it might be easy to miss, so a separate section might be useful for those who missed it like me.

The section can be used to explain that if a field with "file" type has "max files" set to 1 - then existing file will be replaced with uploaded one.

But if it has "max files" set to something else - then new files will be added there until the limit, and after hitting the limit requests will fail with response code 400. In that case you first need to delete some of old files and then add new ones. New ones are always added to the end, even if you deleted files in the middle.

And there is no way to reorder files other than to delete them and upload again in correct order.

Assuming that you're not planning to change this, of course :)

**Comment by ganigeorgiev** [comment]
@Lex-2008 Hi again, I've updated the docs and applied some of your tips.

I'm afraid adding too much information may actually make the documentation harder to read and assimilate and therefore I've omitted some of the explanations and tried to make it a little more compact.

If you think that the updated version is still not clear, let me know and later this evening I'll have more time and will try to improve it.
