### ISSUE TITLE
Batch Uploading Files

### ISSUE THREAD

**Issue by mkhatib** [pocketbase/js-sdk#83]
Hey folks, I have a `photos` collection and I am trying to create multiple records once the user select multiple files to upload. It looks like the first file gets successfully uploaded but then the subsequent request fails. Looking at the logs this is what I see:
```
{   "errorDetails": "multipart: NextPart: EOF",   "errorMessage": "Failed to load the submitted data due to invalid formatting." }

```

It looks like the next requests are cancelled. 

After further investigation it looks like I have to wait for the previous request to finish in order to start a new one. Is batch creation not supported?

This works
```
      for (const file of files) {
        const formData = new FormData();
        formData.append("src", file);
        formData.append("gallery", gallery.id);
        formData.append("section", section.id);
        await pb.records.create("photos", formData);
      }
```

But not this

```
      await Promise.all(files.map(file => {
        const formData = new FormData();
        formData.append("src", file);
        formData.append("gallery", gallery.id);
        formData.append("section", section.id);
        return pb.records.create("photos", formData);
      }));
```

**Comment by ganigeorgiev** [comment]
@mkhatib This is probably due to autocancellation. You can confirm it by catching the error and check if `err.isAbort` is true.

You can adjust the autocancellation behavior per request using the special `$autoCancel` and `$cancelKey` query params OR disable it completely using `pb.autoCancellation(false)`. You can find more information and examples about the autocancellation in https://github.com/pocketbase/js-sdk#auto-cancellation.

**Comment by ganigeorgiev** [comment]
Also please note that you seems that you are using PocketBase SDK v0.7.x. If you are using PocketBase v0.8.0 you should update the SDK version also to v0.8.0.

For a v0.7.x to v0.8.0 migration guide you could check https://github.com/pocketbase/pocketbase/blob/master/CHANGELOG.md#migrate-from-v07x.

Changelog with breaking changes specific to the JS SDK could be found in https://github.com/pocketbase/js-sdk/blob/master/CHANGELOG.md

**Comment by ganigeorgiev** [comment]
I've just tested it locally and I wasn't able to reproduce the issue with disabled auto cancellation.

If after disabling/tweaking the auto cancellation behavior you are still experiencing the same issue, please post the `Promise.all` error and I'll investigate it in more details.

_btw. You can also start the executable with `--debug` to print additional debug and error information in the terminal._
