### ISSUE TITLE
extending record type instead of defining a base interface for record models

### ISSUE THREAD

**Issue by jNaimXIII** [pocketbase/js-sdk#87]
In the README, there's an example for how to add custom types for records. There, we're passing a generic to functions like `getOne` to have type definitions for the returned object.

Doing this does give us the autocomplete we want, but only for the properties we defined, and not the predefined methods a `Record` type holds e.g `export()`.

In my implementation, I extended the `Record` type and then implemented the interface. That way, I get the definitions for the custom types I defined, as well as the predefined `Record` type methods.

```typescript
interface Task extends Record {
  name: string;
}
```

If this is a valid way of doing it, I guess the readme should include this snippet of code.

[Custom Record Type Example In README](https://github.com/pocketbase/js-sdk/blob/47f5014e3d2f293e15f576d8c07131caf4bd7d3f/README.md?plain=1#L266)

**Comment by ganigeorgiev** [comment]
As mentioned in the PR, let's keep it as simple as possible. At the end, it is just an example that you can pass a resolving type/interface and developers are free to implement it however they seems it fit in their project.
