### ISSUE TITLE
can't setup a login in NextJs

### ISSUE THREAD

**Issue by Trongar** [pocketbase/js-sdk#90]
I'm trying to make an app whit Nextjs and Pocketbase, when I make the login and i create the pockedbase instance it goes ok, 
```jsx
const login = async (e: any) => {
    e.preventDefault()
    const email = e.target.email.value
    const pass = e.target.password.value
    const pb = new PocketBase('http://127.0.0.1:8090/')
    const authData = await pb.collection('users').authWithPassword(email, pass)
    console.log(pb.authStore.isValid)
    console.log(pb.authStore.token)
  }
```
it works properly, but it just work in this session, if i reload the page the session is lost, and the authentication fails, so, in the documentation I found this `https://github.com/pocketbase/js-sdk#ssr-integration` and it says that i have to save the auth in a cookie and then load it every time I have to make a new session, so I try to implement it, but i don't understand how to pass the credentials to the server to use them in the serverSideProps function
```jsx

export const getServerSideProps: GetServerSideProps = async (context) => {
  const pb = await initPocketBase(context.req, context.res)
  const isAuth = pb.authStore.isValid
  return {
    props: {
      test: true,
      isAuth
    },
  }
}
```

**Comment by ganigeorgiev** [comment]
_This is similar to https://github.com/pocketbase/js-sdk/issues/69._

As mentioned in the above issue, you first need to decide where and how you want to interact with PocketBase:

- only server-side through some nextjs server handler (eg. getServerSideProps)
- only client-side in the browser (eg. in case of static SPA or prerendered site)
- mixed, both in the browser and node server

The SSR examples in the readme all uses the first option, aka. expect that you'll interact with PocketBase only through the node server.

In order to authenticate a user in this case, you can define an [API route](https://nextjs.org/docs/api-routes/introduction) in your nextjs app that will read the request body (eg. `req.body`) and will make the `authWithPassword()` call.

**Comment by ganigeorgiev** [comment]
_I'll close the issue because this is not related to the SDK and there is already an open one for nextjs, but feel free to comment or open a [discussion in the main repo](https://github.com/pocketbase/pocketbase/discussions) if you need further help._

**Comment by tiagoapp** [comment]
> _This is similar to #69._
> 
> As mentioned in the above issue, you first need to decide where and how you want to interact with PocketBase:
> 
> * only server-side through some nextjs server handler (eg. getServerSideProps)
> * only client-side in the browser (eg. in case of static SPA or prerendered site)
> * mixed, both in the browser and node server
> 
> The SSR examples in the readme all uses the first option, aka. expect that you'll interact with PocketBase only through the node server.
> 
> In order to authenticate a user in this case, you can define an [API route](https://nextjs.org/docs/api-routes/introduction) in your nextjs app that will read the request body (eg. `req.body`) and will make the `authWithPassword()` call.
> 
> (_you can also check the nextjs13 beta docs - https://beta.nextjs.org/docs/data-fetching/api-routes_)

Regarding the "mixed, both in the browser and node server"...

Is it possible to login on the client and then get logged into the node server as well or the other way around (login in node via a api type request and then login on client).

I'm using SvelteKit and I've setup the `hooks.server.ts` and can get logged in in the server with the actions, but can't seem able to login on client afterwards with the cookies. 

I know I could pass for example the user object from the `hooks` via `event.locals` but that wouldn't allow me to use the SDK directly on client?

**Comment by ganigeorgiev** [comment]
@tiagoapp 

> Is it possible to login on the client and then get logged into the node server as well or the other way around (login in node via a api type request and then login on client).

Yes, but you need to:

1. Export the cookie with `httpOnly: false`
2. Load and set the cookie from `document.cookie` when in the browser (or use an abstraction library that will normalize cookie get/set access for both in the node server and in the browser)

Also note, that `hook.server.ts` executes only on the server. You can have a mixed hook with conditional cookie loader OR create a separate sdk instance only for the browser, eg: 

```js
// src/browserClient.js
import PocketBase from 'pocketbase';

const client = new PocketBase("http://127.0.0.1:8090");

client.authStore.loadFromCookie(document.cookie);

client.authStore.onChange(() => {
    document.cookie = client.authStore.exportToCookie({ httpOnly: false });
})

...

export default client;
```
