### ISSUE TITLE
Link OAuth2 account to existing user

### ISSUE THREAD

**Issue by Ponkhy** [pocketbase/js-sdk#93]
Hello,

I would like to link a OAuth2 account like Discord and Twitch to a already existing user (E-Mail and Password) independed of the E-Mail address.
I've already looked at this issue https://github.com/pocketbase/pocketbase/issues/276, but not quite sure how to realize it, since I also cannot find a similar function like `SaveExternalAuth`.

Is there currently a way to do this with the JS-SDK?

Many thanks

**Comment by ganigeorgiev** [comment]
In order to be able to link an existing user with a OAuth2 provider that doesn't return an email (or return a different one), you need to be already authenticated with the user that you want to link, aka.:

```js
await pb.collection('users').authWithPassword('YOUR_EMAIL', 'YOUR_PASSWORD');

...

await pb.collection('users').authWithOAuth2(
    'google',
    'CODE',
    'VERIFIER',
    'REDIRECT_URL',
);
```

The 2 calls are not required to happen on the same page, because the auth token is stored in the LocalStorage.

**Comment by Ponkhy** [comment]
Thanks for the quick reply!
Just to confirm, that means I don't need to worry about anything and it's directly linking it to the already logged in user if exist?

**Comment by ganigeorgiev** [comment]
Yes, the only requirement is the already authenticated user to be from the same collection (eg. "users").

Note that if the OAuth2 user was already linked to another account the above will not work.
To change the OAuth2 linked user, you can either call with the SDK:

```js
await pb.collection('users').unlinkExternalAuth(pb.authStore.model.id, 'google');
```

Or manually remove the linked provider from the:
Admin UI > pick the user you want to edit > delete the provider from the "Authorized providers" tab.

**Comment by Ponkhy** [comment]
Perfect, thank you very much!
