### ISSUE TITLE
Deno & SDK

### ISSUE THREAD

**Issue by Fractal-Tess** [pocketbase/js-sdk#94]
Hey there,

Disclaimer: This is more of a question than an issue.

Do you know how and if it is possible to use this SDK with Deno via an npm package specifier?
I tried doing this today :
```ts
import Pocketbase from 'npm:pocketbase@0.8.1'

const pb = new Pocketbase()

console.log(pb)
``` 
And although it prints out the correct Pocketbase object, Deno (or typescript for that matter) cannot infer the types for the imported symbol and marks it as any.  

Any advice on that?

**Comment by ganigeorgiev** [comment]
I'm not familiar with Deno and I'm not sure how the module resolution works.
Going through their issue trackers shows that the npm package specifier was added recently but there are still  a lot of tasks left in their roadmap - https://github.com/denoland/deno/issues/15960, including several related to the LSP and `@types` handling, so they maybe related to your issue.

It could also be a code editor issue. See for example - https://github.com/pocketbase/js-sdk/issues/92.

Alternatively, you can try loading manually the type definitions using for example the [`@deno-types` annotation](https://deno.land/manual@v1.28.3/advanced/typescript/types#providing-types-when-importing). The definition file should be located at `package_path/dist/pocketbase.es.d.ts`.

**Comment by ganigeorgiev** [comment]
I'm closing the issue since I'm not sure if there is anything we can do in the SDK in this case.

Please note that it is possible that although you are using Deno, your editor LSP server probably uses Node, so if the types are not inferred only inside the editor, then this probably means that it is a lsp/editor issue.

**Comment by Fractal-Tess** [comment]
Well, that certainly sucks, but I managed to solve the issue - be it with glue and tape.

I went ahead and copy-pasteed the definition file into the root of my project and then annotated the pocketbase import with ```// @deno-types="../pocketbase.d.ts"```. 

Might be dirty, but it certainly works and gets the job done!

**Comment by MrBns** [comment]
what is the stat of using Pocketbase after 2 years ?

**Comment by tuniverspinner** [comment]
@MrBns 
> what is the stat of using PocketBase with Deno after 2 years ?

also wonderin...

@Fractal-Tess 
> Well, that certainly sucks, but I managed to solve the issue - be it with glue and tape.
> 
> I went ahead and copy-pasteed the definition file into the root of my project and then annotated the pocketbase import with `// @deno-types="../pocketbase.d.ts"`.
> 
> Might be dirty, but it certainly works and gets the job done!

could u please explain step-by-step?

**Comment by tigawanna** [comment]
recently used ,it works just fine you can even define different versions of the SDK and the types will be correct

**Comment by darthhiggy** [comment]
> recently used ,it works just fine you can even define different versions of the SDK and the types will be correct

interesting. I'm still having issues with this. trying to reference it and it won't work for me.

**Comment by tigawanna** [comment]
![20241222_124036.jpg](https://github.com/user-attachments/assets/5f244f7f-f9d8-48e2-b814-988b3932i 


i used it like this , you can also run

``` sh
deno install ppcketbase
```
Which will add a node_modules and add import aliases in the deno.json
