### ISSUE TITLE
Separate Error and Data handling

### ISSUE THREAD

**Issue by Ponkhy** [pocketbase/js-sdk#96]
Hello,

is it possible to handle errors for each request separately, like in the following example?

```
const { data: createData, error: createError } = await db.collection('test').create({
       "test1": "testdata1",
       "test2": "testdata2"
});

if (createError) throw new Error("Failed to create test");
```

This is helpful because now I can throw a custom error messages for the enduser without having to reveal any backend details.

I have already tried this, but it seems like `.code` isn't always send with every kind of error.
```
const create = await db.collection('test').create({
       "test1": "testdata1",
       "test2": "testdata2"
});

if (create.code) throw new Error("Failed to create test");
```

Many thanks

**Comment by ganigeorgiev** [comment]
Like any other native JS method, the SDK _throws_ errors, it doesn't return them as value. The `Promise` value will be always a result of a success call.

Or in other words, you have to `catch` the error:

```js
try {
    const create = await db.collection('test').create({
        "test1": "testdata1",
        "test2": "testdata2"
    });
} catch (err) {
    console.log(err.data);
}
```

All SDK errors are normalized and wrapped as `ClientResponseError`.

You can find more information about the error handling and all available error fields in https://github.com/pocketbase/js-sdk#error-handling.

**Comment by Ponkhy** [comment]
Hmm okay, thank you again for the very quick reply!
