### ISSUE TITLE
Can't create user in v0.8

### ISSUE THREAD

**Issue by Snaddyvitch-Dispenser** [pocketbase/js-sdk#98]
Hi there,

sorry to bother you with this as it's probably just a silly mistake on my part, but I have just upgraded to v0.8 and using both POST /api/users and the create function on the users table doesn't appear to work. I have updated both my JS and Go libraries.

![cantcreateuser](https://user-images.githubusercontent.com/28988626/205514126-6ebe700f-ccd0-4db0-8370-5f07c011ffa7.png)

Every time I run that or the POST /api/users, I get this response

![useresponse](https://user-images.githubusercontent.com/28988626/205514231-de583d4c-73aa-4a5e-978a-34a976245834.png)

What am I missing here?

Thanks.

**Comment by ganigeorgiev** [comment]
In v0.8 there is no longer `POST /api/users` endpoint. The create equivalent now should be `POST /api/collections/users/records`.

Did you follow the v0.7 -> v0.8 migration guide - https://github.com/pocketbase/pocketbase/blob/master/CHANGELOG.md#migrate-from-v07x?
(_note that the `pb_data` also need to be updated to accommodate the new internal structure_)

**Comment by Snaddyvitch-Dispenser** [comment]
Ahh, thanks.
