### ISSUE TITLE
OAuth2 Token SSR

### ISSUE THREAD

**Issue by Ponkhy** [pocketbase/js-sdk#99]
Hello,

I'm currently trying to implement OAuth2 for my Nuxt 3 (v3.0.0) application. I'm able to request a valid token, login goes through and everything is set properly in the localStorage. Once I refresh the site the localStorage will be cleared `{"token":"","model":null}`.

I'm using the provided example https://github.com/pocketbase/js-sdk#ssr-integration

Any idea how to prevent it from clearing on a refresh?

Many thanks!

**Comment by ganigeorgiev** [comment]
How you are requesting the token? Did you follow the https://pocketbase.io/docs/authentication/#web-oauth2-integration example?

---

When integrating with SSR, usually there are 3 approaches:

- only server-side through some node/nuxt server handler

- only client-side in the browser (eg. in case of static SPA or prerendered site)

- mixed, both in the browser and node server

**All SSR examples uses the first option**, meaning that the browser doesn't communicate directly with PocketBase (aka. browser <-> node <-> PocketBase).

When using the first option you no longer have access to the `LocalStorage` and this is why the cookie flow is used in the SSR examples.
If you want a mixed approach (aka. both browser and node can communicate with PocketBase and you want both to have auth information), then you'll need to create a separate browser instance of the SDK where `document.cookie` is used, eg. something like:

```js
import PocketBase from 'pocketbase';

const client = new PocketBase("http://127.0.0.1:8090");

client.authStore.loadFromCookie(document.cookie);

client.authStore.onChange(() => {
    document.cookie = client.authStore.exportToCookie({ httpOnly: false });
})

export default client;
```
_(note that in the mixed case the cookie need to be exported with `{ httpOnly: false }`)_

**Comment by Ponkhy** [comment]
Yes I'm requesting it like in this example https://pocketbase.io/docs/authentication/#web-oauth2-integration.

Client-Side only would probably be fine for my use case.

**Comment by Ponkhy** [comment]
I've modified now the Nuxt plugin and it seems to hold the token and user infos even after refreshing.
Do you @ganigeorgiev  think this is a good practice?

```JavaScript
import PocketBase from 'pocketbase';

export default defineNuxtPlugin(async (nuxtApp) => {
  const config = useRuntimeConfig()
  const authCookie = useCookie('pocketbase_auth', { httpOnly: false });

  const pb = new PocketBase(config.public.pocketbase);

  pb.authStore.loadFromCookie(authCookie.value || '');

  pb.authStore.onChange(() => {
    authCookie.value = pb.authStore.exportToCookie({ httpOnly: false });
  });

  try {
    pb.authStore.isValid && await pb.collection('users').authRefresh();
  } catch (_) {
    pb.authStore.clear();
  }

  return {
    provide: { pb }
  }
});
```

**Comment by ganigeorgiev** [comment]
It is fine as long as you understand what your code is doing.

I'm not sure what `useCookie` is. Is this an abstraction for reading cookies from `document.cookie` and the ssr server request context?

If yes, then I guess it is fine. But please note that you are reading and setting a cookie of a cookie because `loadFromCookie` and `exportToCookie` works with raw cookie strings (aka. has the cookie key pb_auth with them) so technically the exported cookie attributes from the `exportToCookie` are ignored and those from useCookie are used.

**Comment by Ponkhy** [comment]
Yes `useCookie` is an SSR-friendly way to read and write cookies as reactive component.
Thank you very much, then I will remove the unnecessary `httpOnly` from `exportToCookie` and just keep the `useCookie` one.

**Comment by ganigeorgiev** [comment]
@Ponkhy _Just make sure that the final cookie has also `SameSite=Strict` and `Secure` attributes set (exportToCookie sets them by default)._

**Comment by ganigeorgiev** [comment]
I'm sorry, I'm not sure that I understand what do you mean by "_authRefresh() is still clearing it_".

The store `onChange` callback should be triggered on any change of the store auth state (including `clear`). You can add a breakpoint or a `console.log` inside the `onChange` callback to verify it.

In the above `pb.authStore.clear()` will be called only if the auth refresh call fails to validate the token. You can also try console.log the `catch` error to see if the block is executed.

**Comment by ganigeorgiev** [comment]
We also have [integration tests](https://github.com/pocketbase/js-sdk/blob/master/tests/stores/LocalAuthStore.spec.ts#L145) that `onChange` is always called.

My guess is that the cooke value loaded with the initial `ob.authStore.save` is not valid.
Make sure that `autoCookie.value.token` and `authCookie.value.model` actually exists (_btw. you can remove the the default model fallback, aka. `|| ''`_).

**Comment by Ponkhy** [comment]
When you call `authRefresh()` it does clear the token and model from the localStorage and cookie. It also doesn't call `onChange` which I've just verified and there is no error in the `catch`.

**Comment by Ponkhy** [comment]
I'm really confused now, for some reason it does work now, but I've changed nothing.
I tested it so many times and it didn't call `onChange`, but now it does...

**Comment by ganigeorgiev** [comment]
@Ponkhy It depends where your code is executed. The above plugin will run both in the browser and in the node server, so it is possible when adding a `console.log` in the `onChange` callback to get different results (but you'll always have at least one log either in the browser console or in the terminal).

**Comment by ganigeorgiev** [comment]
@Ponkhy I'm not able to reproduce the issue. Just tested your code with a new nuxt3 project (aka. `npx nuxi init myapp`) and it woks fine and the correct cookie is set both client and server side.

Are you authenticating as app user or admin? If the latter then it is possible that the authRefresh call will fail, since it is for the `users` collection only.

**Comment by ganigeorgiev** [comment]
> Question on the side, is it possible to create a API Rule to check for the Discord User ID?

You can use the `@request.auth.id` filter, eg.:

```
@request.auth.id != "" && ownerId = @request.auth.id
```
(_this translates to - allow only an authenticated user which id matches with the ownerId value to perform the API action_)

You can find more info and examples in https://pocketbase.io/docs/api-rules-and-filters/

**Comment by Ponkhy** [comment]
Ohh sorry I should have specified it, the "ownerId" is similar to the ID which the user has in Discord itself.

**Comment by ganigeorgiev** [comment]
PocketBase doesn't know how this token was generated and whether it is a result of OAuth2 sign-up (you can also have different OAuth2 providers linked to the same user).
Or in other words, you can't access the OAuth2 id in an API rule unless you store it upfront in the user collection as a custom field (eg. `discordId`). Then, similar to the above, you can have a rule like:

```
@request.auth.discordId != "" && ownerId = @request.auth.discordId
```

**Comment by Ponkhy** [comment]
Alrighty thank you, then I will implement a new field to the user collection.
Maybe that would be a nice feature in the future for the API Rules to be able to access the ID :)
